### ISSUE TITLE
Implement a dry run

### ISSUE THREAD

**Issue by lucamolteni** [Gabriel439/Haskell-Turtle-Library#100]
It would be nice to have a way to dry run the script, by printing the commands instead of executing them.

Given the declaratively nature of Turtle it would be probably easy... Maybe I should start it as a side project :)

**Comment by Gabriel439** [comment]
This isn't possible without losing the ability for `Shell` to implement `MonadIO`.  However, you can definitely define your own syntax tree that you can dry-run and then transform to `turtle` commands.  See [this post](http://www.haskellforall.com/2012/07/purify-code-using-free-monads.html) for an explanation of how to do this.

**Comment by lucamolteni** [comment]
Thanks @Gabriel439, I will take a look at it
