### ISSUE TITLE
Add utility for explaining non-zero exit codes

### ISSUE THREAD

**Issue by Gabriel439** [Gabriel439/Haskell-Turtle-Library#101]
The utility would have this name and type:

```haskell
excuse :: Text -> ExitCode -> IO ()
```

If the `ExitCode` was an `ExitFailure` it would throw an exception with the given error message.  This is a simple way to provide a user-friendly error message when an external command fails.

Also, for the special case of `proc` and `shell`, you could use it on the same line as:

```haskell
proc cmd args input >>= excuse msg
```

**Comment by 3noch** [comment]
Since "excuse" can also be a [verb with a different meaning](http://dictionary.reference.com/browse/excuse), I think it's ambiguous in this context.

**Comment by Gabriel439** [comment]
That's actually the meaning I intended: to "excuse" the subcommand's failure by providing an explanatory message

**Comment by 3noch** [comment]
In that case, it's a superb name!

**Comment by Gabriel439** [comment]
So I actually decided in #121 that the idiomatic way to do this should be:

```haskell
proc cmd args input .||. die "Message"
```

I added an FAQ to the tutorial which explain this trick in 92ea29284a3364ce41dafd6decf56f0b425d49f0, so I will mark this fixed.
