### ISSUE TITLE
lnghc: fd:15: hClose: resource vanished (Broken pipe)

### ISSUE THREAD

**Issue by epsilonhalbe** [Gabriel439/Haskell-Turtle-Library#102]
Hey I think I found a bug in the Turtle-Library.

I wrote the following script in order to easily switch between the ghc-versions I use (provided by [hvr's-ppa repository](https://launchpad.net/~hvr/+archive/ubuntu/ghc)).

```haskell
{-# LANGUAGE OverloadedStrings #-}

module Main where

import Turtle
import Prelude hiding (FilePath)
import Data.Either (rights)
import qualified Control.Foldl as F
import qualified Data.Text as T
import Data.Text()

main :: IO ()
main = sh $ do
          args <- arguments
          available_ghcs <- map filename <$> (fold (ls "/opt/ghc/") F.list)
          Just home <- need "HOME"
          case args of
            (a:_) -> if (fromText a) `elem` available_ghcs
                        then do _ <- unlink  $ home <> "/bin/ghc"
                                _ <- symlink ("/opt/ghc/" <> a <> "/bin") $ home <> "/bin/ghc"
                                echo $ "...successfully changed GHC ["<>a<>"]"
                        else do echo $ "'"<> a <>"' is no valid GHC version"
                                list available_ghcs
            _ -> do echo "USAGE: lnghc ${GHC VERSION}"
                    list available_ghcs
    where unlink trgt = proc "unlink" [trgt] ""
          symlink src trgt = proc "ln" ["-s",src,trgt] ""


list :: [FilePath] -> Shell ()
list versions = do current_ghc <- lastMay . T.words <$> inproc "ghc" ["--version"] ""
                   echo "available GHC versions: "
                   mapM_ (echo . highlight current_ghc) $ rights $ map toText versions



highlight :: Maybe Text -> Text -> Text
highlight hi str = if hi == Just str
                     then "[" <> str <> "]"
                     else " " <> str <> " "

lastMay :: [a] -> Maybe a
lastMay [] = Nothing
lastMay xx = Just $ last xx
```

the corresponding cabal file contains

```
...
  build-depends:       base >= 4.7 && < 5
                     , turtle
                     , foldl
                     , text
                     , system-filepath
...
```
and I've used stack with the current resolver (lts-3.0) and ghc version 7.10.2 to compile it.

When running the script multiple times I get the error above - I think the culprit may be the `unlink`/`link` usages of `proc`.

If I can help fixing this somehow, I will be glad to do so.

KR Martin

**Comment by epsilonhalbe** [comment]
Here is some sample calls from my terminal which include timestamps

```
~ > lnghc 7.6.3                      2015-09-01 12:58:34 epsilonhalbe pts/2
...successfully changed GHC [7.6.3]
⟨epsilonhalbe@wendigo⟩-/home/epsilonhalbe
~ > lnghc 7.6.3                      2015-09-01 12:58:36 epsilonhalbe pts/2
...successfully changed GHC [7.6.3]
⟨epsilonhalbe@wendigo⟩-/home/epsilonhalbe
 ~ > lnghc 7.6.3                      2015-09-01 12:58:37 epsilonhalbe pts/2
...successfully changed GHC [7.6.3]
⟨epsilonhalbe@wendigo⟩-/home/epsilonhalbe
~ > lnghc 7.6.3                      2015-09-01 12:58:37 epsilonhalbe pts/2
lnghc: fd:15: hClose: resource vanished (Broken pipe)
```

**Comment by Gabriel439** [comment]
I will be a bit busy this week with CUFP but I will look into this as soon as I can.

**Comment by epsilonhalbe** [comment]
no problem - it is no urgent issue!

I have made a minimal working example for reproducing the bug

{-# OPTIONS_GHC -fno-warn-unused-do-bind #-}
{-# LANGUAGE OverloadedStrings #-}


module Main where

import Turtle
import Prelude hiding (FilePath)


```haskell
main :: IO ()
main = sh $ do touch "./bug.txt"
               unlink  "./bug"
               symlink "./bug.txt" "./bug"
    where unlink trgt = proc "unlink" [trgt] ""
          symlink src trgt = proc "ln" ["-s",src,trgt] ""
```

**Comment by Gabriel439** [comment]
I found the problem.  The issue is that you were trying to feed the `unlink` and `ln` commands no input, but you were accidentally feeding them a single input line containing the empty string.  What you wrote is equivalent to:

```haskell
unlink trgt = proc "unlink" [trgt] (return "")
symlink src trgt = proc "ln" ["-s",src,trgt] (return "")
```

The `unlink` and `ln` commands close their input pipe because they do not expect to receive any input, so when you tried to write a single empty line to their input pipe you get a broken pipe error message.

The solution is to use `empty` to signal that you want to feed no input at all to the commands:

```
unlink trgt = proc "unlink" [trgt] empty
symlink src trgt = proc "ln" ["-s",src,trgt] empty
```

If you make that change then it fixes the problem.

As a side note, if you were using `""` because you wanted a shorter synonym for `empty`, you can instead use `0`, which is also equivalent to `empty` although perhaps less readable to others.

**Comment by epsilonhalbe** [comment]
Thanks - I simply didn't know about empty, this solves the problem.
