### ISSUE TITLE
Tutorial: add information about using on Windows

### ISSUE THREAD

**Issue by mantkiew** [Gabriel439/Haskell-Turtle-Library#108]
Turtle could be a great cross-platform scripting solution. To achieve that, scripts should run on every platform unchanged. I figured out how to run a turtle script on Windows. 

Using `stack  Version 0.1.5.0 I386`, windows 8.1, and GHC 7.10.2. 

Following instructions from [windows shebangs](http://whitescreen.nicolaas.net/programming/windows-shebangs), I changed the file association of `.hs` to `stack`.

1) open `cmd` as administrator. One cannot use PowerShell because both assoc and ftype commands are not visible.

2) execute 

```
assoc .hs=Haskell
ftype Haskell="C:\Users\<your user name>\AppData\Roaming\local\bin\stack.exe" "%1" %*
```

3) now run your script

```
.\hello.hs
```

Alternatively to step 2, file associations can be changed in file explorer (they somehow seem to override the ones done with `assoc/ftype` combo):

1. right-click on `hello.hs`
2. in the tab `General`, change `opens with` to `C:\Users\<your user name>\AppData\Roaming\local\bin\stack.exe`.

**Comment by Gabriel439** [comment]
I have almost the exactly same development environment on one of my laptops so I will take a stab to see if I can get `stack` working on windows.  I may not be able to get to this until this weekend, if that's okay

**Comment by mantkiew** [comment]
It is working for me now. The issue is about testing and adding the instructions for Windows to the tutorial/docs. Sorry, I edited the issue a few times (it wasn't working at first, then I figured it out...).

**Comment by Gabriel439** [comment]
Oh, okay, then I'll update the tutorial with the instructions that you got to work
