### ISSUE TITLE
Add a helper function for `sed -i`

### ISSUE THREAD

**Issue by Gabriel439** [Gabriel439/Haskell-Turtle-Library#109]
In-place substitution is common enough that it's worth adding a specialized utility for this purpose

**Comment by codygman** [comment]
I was just trying to do this. Here's what I ended up with writing it inline:

```haskell
(return (using (return (input "file.txt")))) >>= \fc -> output "file.txt"
```

my first attempt was destined to fail:

```haskell
λ> (output "file.txt" (input "file.txt"))
*** Exception: file.txt: openFile: resource busy (file is locked)
```
However I feel like many people will repeat my mistake.

**Comment by codygman** [comment]
hlint led me through these iterations and showed me I don't understand the left identity law:

```haskell
sediexample fileName = return (using (return (input fileName))) >>= \fc -> output fileName (join fc)
sediexample' fileName = (\ fc -> output fileName (join fc)) (using (return (input fileName)))
sediexample'' fileName = (output fileName . join) (using (return (input fileName))
```

**Comment by codygman** [comment]
Nevermind, I'm done for now... all of those got the same resource busy error.

**Comment by codygman** [comment]
```haskell
sedi :: Turtle.FilePath -> Pattern Text -> Shell ()
sedi fileName pat = do
  h <- using (readonly fileName)
  fc <- using (strict (inhandle h))
  liftIO (output fileName (sed pat (return fc)))

-- λ> view $ sedi "password.txt" ("hunter1" *> return "hunter2")
```

I thought I had it, but not quite :/

**Comment by Gabriel439** [comment]
The issue is that you can't read and write from a file at the same time.  You have to write to a temporary file and then do a swap afterwards

**Comment by codygman** [comment]
I assumed that the managed monad closed the filehandle after strictly reading. At least solution seems pretty obvious in that case.

**Comment by Gabriel439** [comment]
The `Managed` monad is not using any fancy tricks to detect how long you need a resource.  When you do:

```haskell
handle <- using (readonly file)
foo
```

... it's exactly equivalent to:

```haskell
withFile file ReadOnly (\handle -> foo)
```

... meaning that the `Handle` is still acquired for all subsequent commands.  A simple way to close the `Handle` is to use `sh`/`runManaged`.
