### ISSUE TITLE
Add test -e equivalent

### ISSUE THREAD

**Issue by maoe** [Gabriel439/Haskell-Turtle-Library#111]
It would be nice if there was a test -e equivalent in turtle something like:

```haskell
testxxx :: MonadIO io => FilePath -> io Bool
testxxx path = do
  file <- testfile path
  if file
    then return file
    else testdir path
```

I didn't make a pull request because I couldn't come up with a good name..

**Comment by Gabriel439** [comment]
How about `testpath`?

**Comment by maoe** [comment]
Sounds good to me. Shall I make a pull request?

**Comment by maoe** [comment]
I just noticed `testpath` happens to work exactly like `test -e` but `testfile` isn't the same as `test -f`. `test -f` checks if the file is a regular file, but `testfile` returns True even for a device file. Is it intentional?

**Comment by Gabriel439** [comment]
That wasn't intentional.  I just used the behavior provided by the `system-fileio` library, but I'd be happy to change it to match `test -f`
