### ISSUE TITLE
No way to capture stderr

### ISSUE THREAD

**Issue by honza** [Gabriel439/Haskell-Turtle-Library#115]
It would be awesome if I could capture stderr in my program.

**Comment by yogsototh** [comment]
+1

Maybe something like 

~~~
stream:: Process.CreateProcess
    -- ^ Command
    -> Shell Text
    -- ^ Lines of standard input
    -> Shell (Either Text Text)
    -- ^ Lines of standard error / standard output
~~~

**Comment by honza** [comment]
My temporary workaround is to redirect the shell command's stderr to stdout by appending `2>&1`.

**Comment by yogsototh** [comment]
@honza thanks!

**Comment by Gabriel439** [comment]
My only concern is the growing number of functions for dealing with sub processes.  I think what I may end up doing is adding a new `Turtle.Process` module that provides a more modern wrapper around `System.Process` (i.e. `Text` instead of `String`, for example) and also provide these more general `stderr`-capturing variants in this module instead of `Turtle.Prelude`.

**Comment by Gabriel439** [comment]
However, I definitely like the idea of using `Either` to store the output.  You can then select one side or the other using a failing pattern match and it will do the right thing:

```
example = do
    Left err <- stream "foo" ["arg] empty
    ...
```

**Comment by 3noch** [comment]
Some apps log to both stderr and stdout. Wouldn't using `Either` preclude such use cases?

**Comment by PierreR** [comment]
I think `Either` is a bifunctor so you can still use the two sides if you wish so.

**Comment by 3noch** [comment]
That does not compute. But how would `Either` even carry both sides?

**Comment by Gabriel439** [comment]
`Either` is for the streaming case (i.e. every time the app writes a line to `stdout` you wrap that line in `Right` and every time the app writes a line to `stderr` you wrap that line in `Left`).  For the non-streaming case you would return a pair of values (one containing all of `stdout` and another containing all of `stderr`).

**Comment by 3noch** [comment]
:bulb:

**Comment by honza** [comment]
@Gabriel439 Thanks! :sparkles:

**Comment by Gabriel439** [comment]
You're welcome! :)
