### ISSUE TITLE
How can I `Shell a -> IO [a]`?

### ISSUE THREAD

**Issue by Wizek** [Gabriel439/Haskell-Turtle-Library#117]
Hi,

I'm in the process of learning to use the Turtle library by writing a program that does `ls` on a directory and filters the result to items older than a specified date.

The easiest way I can think of to achieve this would be to convert a `Shell a` into `[a]`, after which I could use my good old, trusted `map`, `filter` functions and the like.

But I can't seem to find a function such as `toList :: Shell a -> IO [a]`.

What could I do to achieve such a conversion?

**Comment by Gabriel439** [comment]
So there are two answers: the *direct* answer to your question and the *idiomatic* answer.

The direct answer is to implement `toList`, like this:

```haskell
import qualified Control.Foldl as Fold

toList :: Shell a -> IO [a]
toList s = fold s Fold.list
```

... actually the inferred type of that is slightly more general:

```haskell
toList :: MonadIO io => Shell a -> io [a]
```

That solution is probably good enough for your purposes, but I want to point out that there is another approach which lets you `map` and `filter` the stream without materializing the entire list into memory.

If you want to `map` over a `Shell` stream, just use `fmap` from the `Functor` type class:

```haskell
fmap :: Functor f => (a -> b) -> f a -> f b
```

... which has this type when specialized to `Shell`:

```haskell
fmap :: (a -> b) -> Shell a -> Shell b
```

If you want to `filter` a stream, just use this generalized `filter` function that works for any type that implements `MonadPlus` (including lists, just like the original `filter` function you know and love):

```haskell
filter :: MonadPlus m => (a -> Bool) -> m a -> m a
filter predicate as = do
    a <- as
    guard (predicate a)
    return a
```

If you specialize that `filter` function to `Shell`, you get this type:

```haskell
filter :: (a -> Bool) -> Shell a -> Shell a
```

To make this example concrete, suppose that I want to list the contents of a directory, filter out children that are directories, and then add a `.exe` suffix to each one.  I would just write this:

```haskell
example :: Shell FilePath
example = do
    file        <- ls "someDirectory"
    isDirectory <- testdir file
    guard (not isDirectory)
    return (file <.> "exe")
```

You could even shorten that to:

```haskell
example :: Shell FilePath
example = do
    file  <- ls "someDirectory"
    False <- testdir file
    return (file <.> "exe")
```

That solution will run in constant space, never materializing more than a single `FilePath` into memory at a time, no matter how many children the directory has.

**Comment by 3noch** [comment]
**I LOVE HASKELL** (and Turtle). :grin:

**Comment by Wizek** [comment]
Thanks for the quick response!

I've tried the direct answer, and it seems to work like a charm!

About space-efficiency: Wouldn't the conversion to `Data.List` still keep the program's space complexity constant? I mean, AFAIK both `Data.List` and `Turtle.Shell` can have the same laziness characteristics when it comes to forcing element thunks. Or is there some `seq`ing going on during conversion? And even if there is `seq` in there, couldn't there be an implementation without `seq` to achieve constant space usage?

**Comment by Gabriel439** [comment]
The list version doesn't run in constant space for the same reason that `replicateM` / `sequence` / `mapM` don't run in constant space: they have to read all the elements of the list before they assemble the list.  The act of reading in all the elements of the list ahead of time is what causes the problem.  There are no `seq`s involved in any of this code.

**Comment by 3noch** [comment]
Some comments: Lists are not *inherently* lazy. The list constructor `(:)` is lazy. Often inside of monadic code (like `IO`), the each element of the list must be constructed before the monadic code can move on to the next action in the sequence; thus you end up with an entire list by the end of your action. It may be that the *elements* in the list are still thunks, but the list itself is evaluated.

@Gabriel439 There is probably room for correction in this description.
