### ISSUE TITLE
What would you think about `(Show Size)` returning the string in human readable format instead of bytes?

### ISSUE THREAD

**Issue by Wizek** [Gabriel439/Haskell-Turtle-Library#118]
Wouldn't that be a nice default to have?

```
s <- du "foo.bar"
return (show s) -- "1.1 MB"
```

**Comment by 3noch** [comment]
`Show` instances are *usually* meant to be parsable Haskell. A better way would be to introduce a human-readable version of `show` for `Size`s: `showReadableSize :: Size -> String`.

**Comment by int-index** [comment]
I believe we should add combinators for `Size` to `Turtle.Format`.

**Comment by Gabriel439** [comment]
Yeah, this should be a `Format` in `Turtle.Format`.  I'm thinking of naming this `sz` since that seems like an abbreviation that's unlikely to overlap with any other names.

**Comment by Gabriel439** [comment]
Also, I want to clarify that I agree with @3noch that `Show` instances should be valid Haskell code.  This is an extremely important property to preserve

**Comment by mitchellwrosen** [comment]
Want a PR for this?

**Comment by Gabriel439** [comment]
@mitchellwrosen Yes, if that's not too much trouble
