### ISSUE TITLE
Fixity of .||. and .&&.

### ISSUE THREAD

**Issue by mitchellwrosen** [Gabriel439/Haskell-Turtle-Library#120]
Should `.&&.` bind tighter than `.||.`? Currently they are both `infixr 2`. I believe bash's `&&` does bind tighter than `||`.

**Comment by Gabriel439** [comment]
Yeah, we can set the precedence of `(.&&.)` to 3.  Could you submit a pull request for this?

**Comment by Gabriel439** [comment]
Fixed by #122
