### ISSUE TITLE
-e equivalent?

### ISSUE THREAD

**Issue by mitchellwrosen** [Gabriel439/Haskell-Turtle-Library#121]
Is there a way to get `-e`-like semantics with `turtle`? If not, what about something like

```
shell' :: MonadIO m => Text -> Shell Text -> m ()
shell' cmd input = 
    result <- shell cmd input
    case result of
        ExitFailure n -> die (cmd <> ": " <> T.pack n)
        ExitSuccess -> pure ()
```

**Comment by Gabriel439** [comment]
This is very similar to #101 but I realized just now that you can do this using the `(.||.)` operator like this, very similar to Perl/Bash:

```haskell
shell cmd input .||. die "Error message here"
```

Would that solve your use case?

**Comment by mitchellwrosen** [comment]
It's a bit verbose - in Bash you can just throw a `set -e` at the top and not have to modify any code to get the added safety. It would be nice to have a similar level of effort put into turtle scripts. 

However, nothing is really coming to mind... save for having some Turtle free monad for interpreting `ExitCode`-returning actions in different ways. Seems a bit heavyweight for just `set -e`.

**Comment by Gabriel439** [comment]
You could do this, but then you would no longer be able to run `proc`/`shell` commands as ordinary `IO` commands

**Comment by mitchellwrosen** [comment]
Right, every main would have to be wrapped in `runTurtle`. That sounds worse than your solution above :)

**Comment by Gabriel439** [comment]
So there is another alternative, which is to do what Python does and throw an exception if the process returns a nonzero exit code and the user has to catch and handle the exception to provide a better error message.

**Comment by mitchellwrosen** [comment]
Would that make things like

```
if [ cmd ]; then 
    whatever 
end
```

harder to write? Bash seems to have an advantage here as well - `set -e` won't affect these actions, only "top level" ones. I think.

**Comment by Gabriel439** [comment]
You can still catch and handle exceptions, so the `if` in that example would be `catch` in Haskell

**Comment by Gabriel439** [comment]
On the other hand if we stick to explicit error codes + `(.||.)` + `die`, then the closest analog of `set -e` in Haskell would be the `-fwarn-unused-do-bind` flag + optionally `-Werror` to warn if you discard an exit code.

**Comment by mitchellwrosen** [comment]
Re: handling exceptions, I know - but my point is in Bash you get much nicer syntax.

```
if [ cmd ]
```
becomes
```
success <- catch (cmd >> pure True) (\(_ :: SomeException) -> pure False)
```

**Comment by mitchellwrosen** [comment]
I suppose it's not a totally fair comparison, since `[ ]` are like little functions :)

**Comment by mitchellwrosen** [comment]
Oh, and then all you might need is `test :: MonadIO m => m a -> m Bool`

**Comment by Gabriel439** [comment]
I decided to open up a Twitter poll to get a feel for whether users prefer to signal failure via exit code or exceptions: https://twitter.com/GabrielG439/status/662470232083005440

**Comment by 3noch** [comment]
Innocent unless proven guilty vs. Guilty until proven innocent.

Is `MaybeT` and such out of the question?

**Comment by Gabriel439** [comment]
I'd probably prefer throwing exceptions over `MaybeT`/`ExceptT` since we're already using `IO`.  Checked exceptions seem like overkill for shell scripting.

I'm generally trying to hew as close as possible to prior art with `turtle`, but the problem is that prior art is divided on this point: Python uses exceptions and Bash uses return codes.

**Comment by int-index** [comment]
Using `ExceptT` with `IO` is redundant. There are two useful properties of `ExceptT`:

* exceptions are in the type
* you can handle them in pure code

You lose both as soon as you start using `IO`: the code is no longer pure (by definition) and not all exceptions are in the type (and in this case, it's all or nothing: as soon as you get exceptions not reflected in the type, you have no guarantees about exception safety of your code). Having two mechanisms for exceptions is of no benefit.

I'm in favor of unchecked exceptions in this case, but there's a catch (pun intended). We'll need to provide `MonadBase` and `MonadBaseControl` instances for `Shell`, so users can handle exceptions in the `Shell` monad.

**Comment by Gabriel439** [comment]
Yeah, I agree that `ExceptT` without `UnexceptionalIO` is actually problematic because then you have to deal with both checked and unchecked exceptions in the same code.

I still haven't decided on exit code versus exceptions, but if we did exceptions my preference would be for `Shell` implementing `MonadCatch`

**Comment by Gabriel439** [comment]
So I decided in the short term to go with adding an FAQ section which mentions the `cmd .||. die "Message"` trick, but I'll leave this open with the goal of adding `Exception`-based variants in an upcoming `Turtle.Process` module

**Comment by bgamari** [comment]
In my opinion the lack of safety-by-default is something of a regression compared to Shelly or even bash. It feels wrong that I need to *remember* to handle errors in a Haskell library.

**Comment by 3noch** [comment]
:+1:

@Gabriel439 mentioned that he might implement parallel APIs for throwing/returning error codes.

**Comment by Gabriel439** [comment]
Yes, I will add exception-throwing variations of the subprocess runners named `procs` and `shells` and change the tutorial to recommend them instead
