### ISSUE TITLE
Implement ldir (for ls dir only)

### ISSUE THREAD

**Issue by PierreR** [Gabriel439/Haskell-Turtle-Library#125]
I would like to implement the equivalent of this zsh alias:
`alias ldir="ls -ladh (\.*|*)(/,@)"`
It only prints directories omitting all files.
Unfortunately I don't know how to (easily) filter (pattern match) on directory.

**Comment by Gabriel439** [comment]
You can do this using `testdir`:

```haskell
ldir :: FilePath -> Shell FilePath
ldir dir = do
    path <- ls dir
    True <- testdir path
    return path
```

**Comment by PierreR** [comment]
Oh thanks. This kind of clever trick always surprises me ;-)

**Comment by 3noch** [comment]
Is there an option that's less monadic, i.e. list comprehension, filter, etc? This reminds me of `continue` on other languages and I'm scared of `continue`. ;)

**Comment by PierreR** [comment]
I think I prefer ` guard =<< testdir path` to `True <- testdir path` but it is surely not less monadic.

**Comment by Gabriel439** [comment]
@3noch Sure, just turn on the `MonadComprehensions` extension and you can write:

```haskell
ldir :: FilePath -> Shell FilePath
ldir dir = [ path | path <- ls dir, True <- testdir path ]
```

As a side note, you use list comprehensions as an example of something monadic, but actually list comprehensions are the exact same thing as the list monad:

```haskell
[ (x, y) | x <- [1..3], y <- [4..6] ] = do x <- [1..3]; y <- [4..6]; return (x, y)
```

**Comment by 3noch** [comment]
@Gabriel439 :tada: Brilliant. I had forgotten how monadic lists comps were!
