### ISSUE TITLE
stack setup instructions don't always work?

### ISSUE THREAD

**Issue by averagehat** [Gabriel439/Haskell-Turtle-Library#129]
See https://www.reddit.com/r/haskell/comments/3h0lv3/help_installing_a_package_using_stack/cu389gg ; I was getting the mentioned "hidden package error" with the current installation instructions.

I had to do the following to import Turtle within gchi:
```bash
stack new turtle-proj
cd turtle-proj
#!! add turtle to build-depends in turtle-proj.cabal
stack setup
stack build
stack ghci
```

**Comment by Gabriel439** [comment]
There's a much simpler way that works even outside of a project:

```haskell
$ stack ghci turtle
```

**Comment by averagehat** [comment]
indeed. Do you think full stack installation instructions should be included in the tutorial, given this is kind of a "haskell newbie" project?

**Comment by Gabriel439** [comment]
Yeah, I think it's worth adding more detailed instructions on setting up `stack`

**Comment by Gabriel439** [comment]
So I was looking at the tutorial more closely and I was wondering what additional instructions you had in mind for `stack`.  As far as I can tell, the only remaining details are all operating-system-specific

**Comment by averagehat** [comment]
I was thinking that editing the cabal file will work in all cases where as
`stack install turtle` doesn't appear to always work.

**Comment by Gabriel439** [comment]
Oh, so perhaps I should clarify in the tutorial that `stack install turtle` is meant to be run outside of a Haskell project.
