### ISSUE TITLE
Provide easy to use arguments parsing

### ISSUE THREAD

**Issue by gleber** [Gabriel439/Haskell-Turtle-Library#13]
It looks like Turtle does not provide arguments parsing facilities. I'd love to see something similar to optparse integrated in easy-to-use way into Turtle

**Comment by codygman** [comment]
@gleber I know that the end of the tutorial says:

"The turtle library does not yet provide support for command line argument parsing, but I highly recommend the optparse-applicative library for this purpose. A future release of this library might include a simplified interface to optparse-applicative."

I guess this issue could be a good place to have a discussion of what an easy-to-use way with optparse-applicative might be. I struggle to see how we can really improve upon the optparse-applicative example below, but maybe I'm unimaginitive ;)

```haskell
data Sample = Sample
  { hello :: String
  , quiet :: Bool }

sample :: Parser Sample
sample = Sample
  <$> strOption
      ( long "hello"
     <> metavar "TARGET"
     <> help "Target for the greeting" )
  <*> switch
      ( long "quiet"
     <> help "Whether to be quiet" )

greet :: Sample -> IO ()
greet (Sample h False) = putStrLn $ "Hello, " ++ h
greet _ = return ()

main :: IO ()
main = execParser opts >>= greet
  where
    opts = info (helper <*> sample)
      ( fullDesc
     <> progDesc "Print a greeting for TARGET"
     <> header "hello - a test for optparse-applicative" )
```

**Comment by 3noch** [comment]
The only thing that bugs me about optparse is that it is restricted to the `String` type. I am forced to convert everything to `Text` before I want to use it.
