### ISSUE TITLE
Turtle.Format as a separate package?

### ISSUE THREAD

**Issue by joehillen** [Gabriel439/Haskell-Turtle-Library#134]
I've fallen in love with Turtle.Format, and now I want to use it everywhere!

Would you be interested in pulling that out into its own package or should I do it myself?

I'm not sure what to call it as the Turtle namespace wouldn't make sense and Data.Text.Format is already taken by [text-format](https://hackage.haskell.org/package/text-format).

**Comment by int-index** [comment]
https://hackage.haskell.org/package/formatting

**Comment by joehillen** [comment]
I think a prefer the single character formatter names from Turtle, but formatting has more convenience functions that make it more appropriate for general use. I guess I'll use formatting then.

**Comment by Gabriel439** [comment]
Yeah, I'd also recommend `formatting`.  You should also ask if the author is willing to add short-hand versions of the format specifiers in a separate opt-in module

**Comment by 3noch** [comment]
@Gabriel439 I noticed `formatting` has `printf` for standard out. Have you considered porting that to Turtle to gain the `echo . format` idea we wanted?

**Comment by Gabriel439** [comment]
@3noch Actually, you're right.  I think I spoke too soon and this may be possible after all.  I'll take a stab at it again

**Comment by Gabriel439** [comment]
@3noch Yay, it worked!  `printf` added in 09665d376e17b5b0659077f452e11849fc309e06

**Comment by 3noch** [comment]
:tada: Score!

At first I thought you were using `(>>-)` from semigroupoids. (Yet another thing to learn... :wink:)
