### ISSUE TITLE
Turtle.FilePath -> FilePath

### ISSUE THREAD

**Issue by codygman** [Gabriel439/Haskell-Turtle-Library#138]
Need this for using turtles find followed by readFile

**Comment by PierreR** [comment]
You might be interested in this so answer:

http://stackoverflow.com/questions/34659580/with-haskells-turtle-library-how-to-extract-filename-from-filepath/

**Comment by Gabriel439** [comment]
I think a better solution would be to re-export `Filesystem.readTextFile` from the `system-fileio` library.  How does that sound?

**Comment by codygman** [comment]
I think that's a great solution.
