### ISSUE TITLE
`rmtree` cannot remove files or symlinks.

### ISSUE THREAD

**Issue by aherrmann** [Gabriel439/Haskell-Turtle-Library#143]
The [documentation of `rmtree`](https://github.com/Gabriel439/Haskell-Turtle-Library/blob/master/src/Turtle/Prelude.hs#L848-L853) seems to be misleading. It says that `rmtree` would be equivalent to the shell command `rm -r`.

However, `rmtree` cannot delete files. Instead it produces the following error when called as `rmtree "file"`:

    *** Exception: file: listDirectory: inappropriate type (Not a directory)

And, `rmtree` cannot delete symlinks. Instead it produces the following error when called as `rmtree "symlink"`:

    *** Exception: symlink: removeDirectory: inappropriate type (Not a directory)

The behavior of `rm -r` is quite different (at least on Linux).

1. It removes files (i.e. not only directories)
2. If the given path is a symlink, then it will remove the symlink, but not the contents of the directory that the symlink points to.

**Comment by Gabriel439** [comment]
I think in this case the correct thing to do is to match the behavior of `rm -r`.  I'll write up a fix for this as soon as I can

**Comment by Gabriel439** [comment]
In fact, looking under the hood at how `Filesystem.removeTree` is implemented, it's not being as efficient as it could be.  It uses `listDirectory` which will not stream in constant space over large directories.  It's probably better to just implement the recursive removal directly within `turtle` using `lstree` and `rm`.

**Comment by aherrmann** [comment]
Thanks for the quick response. Unfortunately, it doesn't fully fix the issue. When the given path points to a symlink which itself points to a directory then `rmtree` still doesn't behave like `rm -r`. The latter would remove the symlink but leave the directory untouched. However, `rmtree` removes all the contents of the directory, and then fails to delete the symlink with the following error message:

    *** Exception: link: removeDirectory: inappropriate type (Not a directory)

The problem is that `Filesystem.isDirectory` resolves links first, before checking whether it is a directory or a file.
