### ISSUE TITLE
Strange freeze of `shell` action

### ISSUE THREAD

**Issue by paluh** [Gabriel439/Haskell-Turtle-Library#145]
Hi,

Thanks for this wonderful library!

I have strange problem with freezing turtle script (initially I've tried to use `chpasswd`, but I've rewritten it to use `grep`). When interpreted (runghc) it runs smoothly. When compiled it freezes on third action - `shell` usage.

    {-# LANGUAGE OverloadedStrings #-}

    import           Turtle (empty, sh, select, inshellWithErr, inshell, shellStrict, shell, view)

    main :: IO ()
    main = do
      view $ inshell "/usr/bin/grep foo" (select ["foo 1", "bar", "foo 2"])
      view $ inshellWithErr "/usr/bin/grep foo" (select ["foo 1", "bar", "foo 2"])
      x <- shell "/usr/bin/grep foo" (select ["foo 1", "bar", "foo 2"])
      print x

 I've tried to compile/run it under my Arch Linux and on the same machine in nspawn container (Debian Jessie). I've always tested it in isolated `stack` environments. I've tried different versions of lts (lates lts-5.6 <ghc-7.10.3> and some old, random one lts-3.0 <ghc-7.10.2>). I also tried to switch off optimization with -O0. I'm getting the same freezing behavior of compiled program (but no problems when script is interpreted).
Are you able to replicate my observations on your system? Is it only my machine related problem?

**Comment by lspitzner** [comment]
*points at #72*

**Comment by paluh** [comment]
@lspitzner - thanks! It works with `-threaded`!

**Comment by Gabriel439** [comment]
Actually, I'll keep this open to remind myself to document this issue in the FAQ section of the tutorial
