### ISSUE TITLE
`du` on directory

### ISSUE THREAD

**Issue by lxyu** [Gabriel439/Haskell-Turtle-Library#151]
The `du` on file works fine and the same as unix `du` on file. While the `du` on directory doesn't give the same result as `du` in unix, which will give a list of file size, and a total size at the end, but with `du -s` outputs a single total size of a directory.

Do you think it would be better to make `du` on directory match unix `du -s`?

**Comment by Gabriel439** [comment]
Could you provide the example unexpected output you got?  This might be a case of incorrect behavior in the underlying `Filesystem.getSize` function that `du` uses.

**Comment by lxyu** [comment]
For example, create a directory with a bin randomly generated:

```sh
$ mkdir -p /tmp/test
$ dd if=/dev/urandom of=/tmp/test/bin bs=16M count=1
```

The output in shell:

```sh
$ du -sb /tmp/test/bin
16777216	/tmp/test/bin
$ du -sb /tmp/test/
16777276	/tmp/test/
```

The output of turtle `du`:
```haskell
> du "/tmp/test/bin"
16777216
> du "/tmp/test"
60
```

**Comment by Gabriel439** [comment]
Okay, I see what you mean now.  After looking through the `du.c` it seems like it does not consult the `st_size` field of the `stat` struct associated with the directory and instead it traverses the recursive children to sum up the results.  I can modify `turtle`'s `du` to do the same.

**Comment by Gabriel439** [comment]
Alright, so the implementation I gave is nowhere near as fast as the Unix `du` and the results differ slightly, but at least it's in the right ballpark:

```bash
$ du -ms ~/proj
7766	/Users/gabriel/proj
```

```haskell
>>> s <- du "/Users/gabriel/proj"
>>> mebibytes s
7858
```
