### ISSUE TITLE
Description is too opaque

### ISSUE THREAD

**Issue by legrostdg** [Gabriel439/Haskell-Turtle-Library#154]
It doesn't seem possible to get a Description from a Text:

    mytext :: Text
    mytext = "blabla"

    subcommand "test" (Description ("my description with a text appended at the end" `T.append` mytext)) (pure Command)

    ...
    other uses of "mytext"

It would be great to have a "fromText :: Text -> Description" or to export the "Description" constructor.

**Comment by Gabriel439** [comment]
It technically is possible, albeit verbose, if you do `fromString . Text.unpack`, which you can use as a workaround for now.  However, I'll add the utility you described anyway.  I really wish the `IsString` class had a `fromText` method which would be an even better solution.

**Comment by int-index** [comment]
> I really wish the IsString class had a fromText method which would be an even better solution.

This would require `Text` in `base`.

**Comment by Gabriel439** [comment]
Yeah, I really wish `Text` were in `base`, too :)
