### ISSUE TITLE
add a way to get a shell script?

### ISSUE THREAD

**Issue by legrostdg** [Gabriel439/Haskell-Turtle-Library#157]
I'm not sure if it's possible, but it would be great to be able to get a shell script from a "turtle" script (for what it means...).

The final goal would be to use turtle in propellor:

https://propellor.branchable.com/todo/integrate_shell-monad/

What do you think about this?

**Comment by Gabriel439** [comment]
I don't think this is possible while still supporting arbitrary `IO` actions.  As far as I know there is no mechanical way to turn any `IO` action into a shell command

**Comment by legrostdg** [comment]
It makes sense.
