### ISSUE TITLE
Is there a way to parse list of arguments?

### ISSUE THREAD

**Issue by huseyinyilmaz** [Gabriel439/Haskell-Turtle-Library#158]
Hello,
Following is example usage for rync:

```
 rsync -avz --exclude file1.txt --exclude dir3/file4.txt source/ destination/
```

In this example, command has 2 exclude arguments given. Is there a way to to this in turtle library? If not this would be a very nice addition to library.

As far as I can see there is no way to accept multiple number of arguments with same argument name. So I implemented an rsync wrapper in following way:

```
parser = (,,) <$> (argText "source" "source directory to copy")
              <*> (argText "destination" "destination directory to copy")
              <*> (optText "exclude" 'e' "Exclude Following Paths(Coma separated List)")
```

It would be really nice to have an interface like this:

```
parser = (,,) <$> (argText "source" "source directory to copy")
              <*> (argText "destination" "destination directory to copy")
              <*> (argList (optText "exclude" 'e' "Exclude Following Paths(Coma separated List)"))
```
Thanks.

Original source : https://github.com/huseyinyilmaz/cscp/blob/9bb188e88fa3d3a9cbb6c5c3da34c5adb6e49c9d/src/Lib.hs#L9-L11

**Comment by Gabriel439** [comment]
Yes!  Since the `Parser` type implements the `Applicative` interface, you can use `many` to parse a list of arguments:

```haskell
many :: Alternative f => f a -> f [a]

-- Specialized to the `Parser` type:
many :: Parser a -> Parser [a]
```

So in your example, you would write:

```haskell
parser = (,,) <$> (argText "source" "source directory to copy")
              <*> (argText "destination" "destination directory to copy")
              <*> many (optText "exclude" 'e' "Exclude Following Paths(Coma separated List)")
```

`many` parses 0 or more values to form the list.  If you want to parse 1 more or values then use `some` instead

**Comment by huseyinyilmaz** [comment]
That really blew my mind. Thanks for the help it work perfectly.

**Comment by Gabriel439** [comment]
You're welcome! :)
