### ISSUE TITLE
Use Doc rather than Text for options header

### ISSUE THREAD

**Issue by mitchellwrosen** [Gabriel439/Haskell-Turtle-Library#160]
What do you think about 
```haskell
newtype Description = Description { getDescription :: Doc }
```
rather than
```haskell
newtype Description = Description { getDescription :: Text }
```
?

You still have an `IsString` instance, and moreover users can format headers to their liking. Currently, `Options.Applicative.Builder.header` just smashes all text fragments together, even they contain newlines and such.

**Comment by Gabriel439** [comment]
Yeah, I think that's a great idea!
