### ISSUE TITLE
Confusing sed functionality with prefix / suffix

### ISSUE THREAD

**Issue by unknownloner** [Gabriel439/Haskell-Turtle-Library#161]
When using the `sed` command from, for example, bash, a pattern ending with a $ can be used to replace something that occurs at the end of a line. For example, `echo "A B A" | sed 's/A$//g'` will result in `A B`.

Given that the documentations for Turtle's `suffix` states "Use this to match the suffix of a string", I figured I could do the same thing with Turtle like so: `sed (suffix (text "A") *> "")`.

However, because `suffix` is implemented as `suffix p = chars *> p`, it matches the entire line. As a result, rather than replacing just the end of the line with the replacement string, it replaces _the entire line_ with the replacement string.

Knowing how `suffix` is implemented, it makes complete sense why this is happening, but when trying to use Turtle's `sed` in place of command line sed this is pretty confusing behavior.

I haven't tested `prefix`, but since it's implemented as `prefix p = p <* chars` I'm assuming it has the same issue.

**Comment by Gabriel439** [comment]
So one way you can do it that's probably close to what you wanted is:

```haskell
>>> sed (ends ("A" *> mempty)) "A B A" & stdout
A B 
```

`ends` is very similar to `suffix`:

```haskell
ends p = char <> p
```

But you can actually simplify it further using equational reasoning:

```haskell
-- Definition of `ends`:
sed (chars <> ("A" *> mempty))

-- Definition of `(<>)` for `Pattern`:
= sed (do x <- chars; y <- ("A" *> mempty); return (x <> y))

--`Monad` laws:
= sed (do x <- chars; "A"; y <- mempty; return (x <> y))

-- Definition of `mempty` for `Pattern`
= sed (do x <- chars; "A"; y <- pure mempty; return (x <> y)

-- `Monad` laws:
= sed (do x <- chars; "A"; return (x <> mempty)

-- `Monoid` laws:
= sed (do x <- chars; "A"; return x)

-- ... according to the definition of `(<*)`
= sed (chars <* "A")
```

... so `sed (chars <* "A")` is the even shorter way to write this, which make sense.  You can read it as saying "Match everything, but don't return the final `"A"`".

**Comment by Gabriel439** [comment]
I'll go ahead and close this since I believe the original question was answered, but if you have any additional concerns feel free to reopen this
