### ISSUE TITLE
grep (and sed?) operate on whole Text contents, not individual lines.

### ISSUE THREAD

**Issue by unknownloner** [Gabriel439/Haskell-Turtle-Library#162]
Ran into this while trying to process some text I had generated outside of Shell.

Basically, I wrote `grep pattern (pure x)` where x is a multi-line Text value. Rather than getting only the lines containing `pattern`, I got the entire contents of `x` (or none of the contents if the pattern didn't match of course). This also broke things like `begins` and `ends`, since they were searching from the start/end of the Text, rather than each line.

To work around this I did `grep pattern . cat . map pure . lines $ x` which seems a bit clunky to say the least.

I know that the typical Shell Text producers like readTextFile generate the Text line by line, but I think grep/sed should probably also handle multi-line for cases like this.

Quick edit:
If the rest of Turtle also operates under the assumption that Text values only contain a single line, I realize this could present a bigger problem than just changing grep / sed. Maybe there should be another way to embed Text which handles splitting up the lines for the user, and warnings against using pure/return? I don't really have an answer there.

**Comment by Gabriel439** [comment]
Yeah, the library operates under the assumption that `Text` values only contain a single line.

A shorter way to convert to a `Shell` is:

```haskell
select . lines :: Text -> Shell Text
```

... or when combined with `grep`:

```haskell
grep pattern (select (lines x))
```

**Comment by Gabriel439** [comment]
I'll close this question since I believe it was answered, but you can reopen this if you still have any issues

**Comment by int-index** [comment]
@Gabriel439 Do you think it would be useful to have a wrapper `newtype Line = Line Text` that maintains the invariant?

**Comment by Gabriel439** [comment]
@int-index Yeah.  Let's open a pull request so that people can comment on this change, but I think it would help a lot to avoid this common source of confusion
