### ISSUE TITLE
find is so slow

### ISSUE THREAD

**Issue by 3noch** [Gabriel439/Haskell-Turtle-Library#167]
I'm trying to replicate the simple logic of `find . -name "*.orig" | xargs rm`, but my _compiled_ (with `-O2`) script takes 20 seconds as opposed to instantaneous. It's possible that `Turtle.find` is doing more work by recursing into hidden directories or something, but the performance is so stark I wonder if we need to at least document something:

``` haskell
#!/usr/bin/env stack
-- stack --install-ghc runghc --package turtle


{-# LANGUAGE OverloadedStrings #-}

import Turtle

main = do
    extension <- options "Remove all files with an extension" $
      optText "extension" 'e' "File extension to remove"

    sh $ do
      doomed <- find (ends $ text $ "." <> extension) "."
      liftIO $ do
        printf ("Removing "%fp%"\n") doomed
        --rm doomed

```

**Comment by 3noch** [comment]
I've confirmed that Turtle's `find` is finding far more files than Linux `find`.

```shell
(climate) ~/a/l/f/climate ❯❯❯ find . -name "*" | wc -l
    8173
(climate) ~/a/l/f/climate ❯❯❯ turtlefind | wc -l
  384676
```

**Comment by mitchellwrosen** [comment]
Turtle's `find` does recurse into hidden directories, but so does `find`.

**Comment by mitchellwrosen** [comment]
@3noch, compare find's output to `turtlefind | sed 's/FilePath /' | tr -d '"'` and see what the difference is. I tried your experiment and I'm seeing the same files output by both tools (except that `find` outputs `.` and turtle does not)

**Comment by 3noch** [comment]
I wonder if it could by symlinks.

**Comment by mitchellwrosen** [comment]
Ah, yes. `find` will list a directory that is a symlink, but not go into it.

**Comment by mitchellwrosen** [comment]
This is easy to fix - just change `lstree` to `lsif fileIsSymbolicLink`. Problem is, there's currently CPP that partitions windows/posix code for this case. I have a PR up that adds `unix-compat` as a dependency - if Gabriel wants to merge it, then this change will be able to leverage that library's `getSymbolicLinkStatus`.

**Comment by Gabriel439** [comment]
Yes, I'm totally fine with adding `unix-compat` as a dependency, since I believe we will need it for all symlink-related stuff

**Comment by Gabriel439** [comment]
Note that there are two possible reasons that `find` might be slow:

* differences in which files are traversed, as already discussed
* the `system-filepath` library uses an inefficient internal representation for the `FilePath` type (basically `String`s), plus `turtle`'s `Pattern` type is not that efficient at regular expression matching

I'd like to know if fixing the number of files scanned fixes the performance problem so I can know if I need to dig into the second issue
