### ISSUE TITLE
Possible resource leak

### ISSUE THREAD

**Issue by GregorySchwartz** [Gabriel439/Haskell-Turtle-Library#177]
I might just be using Turtle wrong or misinterpreting the code / tutorial, but with this skeleton example code I get a "too many open files" error. I was under the impression that all files were closed at the end of a call such as "output". In the source code for "output" I see that it uses "using", which should release resources at the end (or so I thought). No amounts of runManaged, sh nesting, or using can fix this issue. When "find" returns a stream of thousands of files and I want to write a different new file for each of those files, how can I close each written file as it is used?

-- someFuncWhichOnlyUsesOutputFunc returns IO () and uses the "output" function from Turtle to read in the file and write something to a separate output file (with inprocs leading up to the output call, so output saveFile . inshell stuff . inshell otherStuff $ empty).
 
```
import Turtle
import qualified Data.Text as T
import qualified Data.ByteString.Lazy.Char8 as CL

main :: IO ()
main = sh $ do
    mktree "data"
 
    reference <- liftIO . CL.readFile $ "aFile.csv"
 
    let parsed :: [[T.Text]]
        parsed = parseSomeFile reference
 
    sh $ do
        file      <- find (suffix ".txt") dir
        entry <- select parsed
 
        liftIO $ someFuncWhichOnlyUsesOutputFunc file (entry !! 2) (entry !! 1) (entry !! 0)
```

**Comment by Gabriel439** [comment]
`turtle` only provides that guarantee for the utilities it provides.  For example, if you use `Turtle.Prelude.input` or `Turtle.Prelude.readonly` they won't leak file handles in a loop like the `find` loop you wrote.

What I can say for sure is that `someFuncWhichOnlyUsesOutputFunc` is almost certainly the source of the leaked resources but I can't say more without knowing what it does with the `file` that you pass to it.  `find` itself does not do any resource acquisition so it's not responsible for the leak.

**Comment by GregorySchwartz** [comment]
You are absolutely right in that someFunc... is probably the issue, but I was attributing it to the thousands of output calls. The function would be something like this:

```
someFuncWhichOnlyUsesOutputFunc :: P.FilePath -> Text -> Text -> Text -> IO ()
someFuncWhichOnlyUsesOutputFunc file start stop name = do
    let fileHeader  = basename file
        saveFile = saveDir
               </> ( P.fromText
                   . (<>) name
                   . (<>) "_"
                   . format fp
                   . P.filename
                   . P.replaceExtension file
                   $ "csv"
                   )

    print saveFile
    output saveFile
        . sed ("_" *> return ("_" <> format fp fileHeader))
        . inshell "program3"
        . inshell "program2"
        . inshell (mconcat ["program1 ", start, " ", stop])
        $ empty
```

**Comment by GregorySchwartz** [comment]
The inshell programs are streaming with no other files being created, I should mention.

**Comment by Gabriel439** [comment]
Does the problem persist if you `output` some placeholder result without using `inshell`?

My suspicion is that `inshell` is the source of the problem and might have a resource leak

**Comment by GregorySchwartz** [comment]
Replacing the inshells with 'inshell "echo \"_test\"" successfully ran. I guess it must be one of the inshell calls which is weird, but I'll see what I can do. Thank you for this amazing library!

**Comment by GregorySchwartz** [comment]
Okay, it was definitely the inshell program. It apparently uses many, many temporary files (darn side effects).

**Comment by Gabriel439** [comment]
You're welcome!  Glad I could help :)
