### ISSUE TITLE
Deps on base >=4.5 is not explicit in turtle.cabal

### ISSUE THREAD

**Issue by PierreR** [Gabriel439/Haskell-Turtle-Library#18]
Tutle does not work out of the box with the default ghc from RHEL (ghc 7.0.4). It fails with this error:
```
cabal: cannot configure exceptions-0.6.1. It requires base >=4.5 && <5
For the dependency on base >=4.5 && <5 there are these packages: base-4.5.0.0
```
The turtle cabal file only mentions a deps with  `base >= 4 && < 5`.

Is the minimum ghc version specified somewhere else ?

**Comment by Gabriel439** [comment]
I would just raise the lower bound on `base` to `4.5`.  I usually don't support anything older than that anyway.

**Comment by PierreR** [comment]
That's ok by me.

I have had a go with the native ghc from RHEL because I saw `base  >= 4 && < 5`. I will try to install a more recent version on RHEL 6 with halcyon ;-)
