### ISSUE TITLE
ls with Pattern

### ISSUE THREAD

**Issue by reckbo** [Gabriel439/Haskell-Turtle-Library#184]
Is there a simple way to run `ls` with a glob pattern, e.g. analogous to shell version of

    ls *.txt

or do you have to use grep, ls, and convert from FilePath to Text and back?

**Comment by 3noch** [comment]
Well...in a hurry you can always do `inshell "ls *.txt" empty"`.

**Comment by Gabriel439** [comment]
@reckbo This is very similar to `find`, except just searching only the current directory.  You can just take the implementation of `find`:

```haskell
-- | Search a directory recursively for all files matching the given `Pattern`
find :: Pattern a -> FilePath -> Shell FilePath
find pattern dir = do
    path <- lstree dir
    Right txt <- return (Filesystem.toText path)
    _:_       <- return (match pattern txt)
    return path
```

... and modify it to use `ls` instead of `lstree`, so the final solution is something like this:

```haskell
files :: Shell FilePath
files = do
    here <- pwd
    path <- ls here
    Right txt <- return (Filesystem.toText path)
    _:_       <- return (match (suffix ".txt") txt)
    return path
```

This would be simplified further when I'm done reviewing #180 because then the solution would just be:

```haskell
files = do
    here <- pwd
    onFiles (grep (suffix ".txt")) (ls here)
```

**Comment by reckbo** [comment]
Thanks!

Looking forward to `onFiles`, that's the type of function I was originally looking for.

**Comment by joelmccracken** [comment]
I want to do the same thing, except paths would be read from an external file. I *could* do the following: 

```
pth <- select ["{,**/}*.hs", ...]
stdout $ inshell ("echo " + pth) Turtle.empty
```

...but this brings up shell injection dangers. I'm not worried about malicious users, but another person may.

**Comment by Gabriel439** [comment]
@joelmccracken: If paths are read from an external file, you could do:

```haskell
example = do
    line <- input yourFile
    let file = fromText (lineToText line)
    ...
```

It's not clear how this relates to globbing, though

**Comment by joelmccracken** [comment]
Say I had a config file with a list of directories. This file is user created, so the user probably doesn't want to type their home directory over and over again.

The file  would look something like this:

```
git ~/Projects/*
inbox ~/Inbox
inbox ~/Desktop
inbox ~/Downloads
```

I want to expand `~` to the user's home directory, and expand `*` to be everything below `~/Projects`. I could parse and expand myself, but it seems like there might be a better way.

**Comment by Gabriel439** [comment]
Probably the simplest approach is to use `shell`, which runs the text command line through a shell interpreter, including glob expansion.  It would look something like this:

```haskell
--  I haven't type-checked or ran this code

example :: Shell FilePath
example = do
    line <- input "yourFile.txt"
    case Data.Text.words (lineToText line) of
        [_, glob] -> do
            line' <- inshell ("ls -1d " <> glob) empty
            return (fromText (lineToText line'))
        _ -> die "Malformed line"
```

Another approach is to use the Haskell `Glob` library for doing glob expansion natively within Haskell without going through a shell interpreter

**Comment by ulysses4ever** [comment]
I wish the [solution posted above](https://github.com/Gabriel439/Haskell-Turtle-Library/issues/184#issuecomment-250525354) stood out more. It also requires an update changing `grep` for `grepText`. So, for posterity:

```
-- files ~= ls *.txt
--
files = do
    here <- pwd
    onFiles (grepText (suffix ".txt")) (ls here)
```
