### ISSUE TITLE
Default values for command line args/options

### ISSUE THREAD

**Issue by mitchellwrosen** [Gabriel439/Haskell-Turtle-Library#186]
What do you think about adding default values to the API? It might come out looking something like this:

```haskell
-- same as before
opt :: (Text -> Maybe a) -> ArgName -> ShortName -> Optional HelpMessage -> Parser a

-- show default value with Show instance
optDefault :: Show a => (Text -> Maybe a) -> ArgName -> ShortName -> a -> Optional HelpMessage -> Parser a

-- show default value with given func
optDefaultWith :: (Text -> Maybe a) -> ArgName -> ShortName -> (a -> Text) -> a -> Optional HelpMessage -> Parser a

-- other funcs get an additional Optional arg
optInt :: ArgName -> ShortName -> Optional Int -> Optional HelpMessage -> Parser Int
optDouble :: ArgName -> ShortName -> Optional Double -> Optional HelpMessage -> Parser Double
...
```

**Comment by Gabriel439** [comment]
I think at that point the user should probably be using `optparse-applicative` directly.  Think of `Turtle.Options` as sort of a starting point that teaches people how the pieces are supposed to fit together for `optparse-applicative`.  The goal was never for `Turtle.Options` to be a comprehensive alternative API for `optparse-applicative`

**Comment by mitchellwrosen** [comment]
Sounds good. I get that `Turtle.Options` isn't supposed to be all of `optparse-applicative`, but it is such a vastly superior API, in terms of both documentation and simplicity, that I might just not use default values rather than import `Options.Applicative.Builder.Extra` or whatever!

**Comment by lspitzner** [comment]
@mitchellwrosen this reminds me of an unannounced and severely undocumented/untested package of mine, [`butcher`](https://github.com/lspitzner/butcher). With it, you can write:

~~~~ .hs
import UI.Butcher.Monadic

main = mainFromCmdParser $ do
  addHelpCommand

  name       <- addFlagStringParam [] ["name"] "NAME" mempty
  age :: Int <- addFlagReadParam "" ["age"] "AGE" (flagDefault 42)

  addCmdImpl $ do
    echo (format ("Hello there, "%s) (Text.pack name))
    echo (format ("You are "%d%" years old") age)
~~~~

and get the following behaviour:

~~~~
> testprogram help
NAME

  testprogram

USAGE

  testprogram --name NAME [--age AGE] [help]

> testprogram
testprogram: error parsing arguments: could not parse --name NAME
at the end of input
usage:
testprogram --name NAME [--age AGE] [help]
> testprogram --name lennart
Hello there, lennart
You are 42 years old
> testprogram --name lennart --age 6
Hello there, lennart
You are 6 years old
~~~~

also see usage examples [no 1](https://github.com/lspitzner/brittany/blob/master/src-brittany/Main.hs#L42) and [no 2] (https://github.com/lspitzner/brittany/blob/master/src/Language/Haskell/Brittany/Config.hs#L35) from my project `brittany`, where I make use of butcher.

I dare to believe that butcher's interface is quite nice, but take into account the "evil monadic interface" (see the README).

(And i had to write some minor new functions in butcher just to make the above example work - you need butcher-0.2.0.0 which i will push in a few secs.)

**Comment by lspitzner** [comment]
(pushed)

I'd like to hear how you find this interface/if you consider this worth polishing up.

**Comment by mitchellwrosen** [comment]
I can poke around a bit after work, but re: the evil monadic interface - with `-XApplicativeDo` you can use `do` notation with an `Applicative` (such as an `optparse-applicative` `Parser`)

**Comment by lspitzner** [comment]
Oh indeed, I need to mention that in the README.. from my attempts with ApplicativeDo, i found it rather easy to accidentally write some pieces of code that break the compatibility with ApplicativeDo, leading to rather hard-to-track-down errors (you get some "hey, this is not a monad" in a random location). Of course it is likely that the compiler will improve on that front in the future. Apart from that, for subcommands the monadic interface is a bit more expressive in a way that I could not translate easily to an applicative interface.
