### ISSUE TITLE
No variant of proc/inproc returns stdout, stderr and exit code

### ISSUE THREAD

**Issue by paf31** [Gabriel439/Haskell-Turtle-Library#187]
I can use `inproc` if I want to keep `stdout`, or `inprocWithErr` if I'd also like `stderr`.

Or I can use `proc` if I'd like the exit code, but then I lose the ability to fold over `stdout` or `stderr` for the process.

It would be great to be able to capure all three, if possible.

**Comment by Gabriel439** [comment]
There is `procStrictWithErr` in `master` but not on Hackage yet:

https://github.com/Gabriel439/Haskell-Turtle-Library/blob/master/src/Turtle/Prelude.hs#L458

Would that solve your use case?

**Comment by paf31** [comment]
Yes, thanks! Most of the processes I'll run will yield little output, so this will work fine.
