### ISSUE TITLE
New release on Hackage

### ISSUE THREAD

**Issue by maoe** [Gabriel439/Haskell-Turtle-Library#189]
There are some nice features which haven't been published to Hackage. Would you mind making a new release?

**Comment by jb55** [comment]
:+1: would love to use the Bytes module

**Comment by Gabriel439** [comment]
Sorry for the delay!  I will upload this soon (hopefully this weekend).  I would just like to do one final pass over the library due to the large number of changes since the last release

**Comment by Gabriel439** [comment]
Alright, this is now up on Hackage as `turtle-1.3.0`.  Also, there's a newly added `CHANGELOG`, too: https://hackage.haskell.org/package/turtle-1.3.0/changelog

**Comment by jb55** [comment]
great, thanks!

**Comment by Gabriel439** [comment]
You're welcome!
