### ISSUE TITLE
1.0.2 release ?

### ISSUE THREAD

**Issue by PierreR** [Gabriel439/Haskell-Turtle-Library#19]
Would it be ok by you to release 1.0.2 ?

I am actually in the process to build a turtle script with Halcyon on CentOS 6 and it would be far easier to do it against a cabal version (I have already started using the `fp format specifier`).

Cheers

**Comment by Gabriel439** [comment]
Alright.  I'll do a release soon.

**Comment by Gabriel439** [comment]
Sorry for the delay.  I was sick for the last few days and I wanted to finish up a few more issues before the 1.0.2 release

**Comment by PierreR** [comment]
No problem. I have just a couple of turtle scripts to manage so I really don't mind the wait and use some workarounds in the meanwhile. Your support is fantastic and that's what matters. Thanks so much !

**Comment by Gabriel439** [comment]
You're welcome!  :)

**Comment by Gabriel439** [comment]
Alright, I cut a version 1.0.2 release, which is now on Hackage
