### ISSUE TITLE
No arguments or options with help text

### ISSUE THREAD

**Issue by dmp1ce** [Gabriel439/Haskell-Turtle-Library#190]
Is it possible to not use any arguments or options but still have help text from `--help`?

The only thing I could figure is to use a trivial option like `--verbose` or maybe use `hidden` from `Options.Applicative.Builder`.

**Comment by Gabriel439** [comment]
Yes:

```haskell
main = do
    options "Some description" (pure ())
    ...
```

**Comment by dmp1ce** [comment]
Thanks! I thought I had tried that but I was using `return ()`.

**Comment by Gabriel439** [comment]
`return ()` should also work, too.  Upcoming versions of GHC will require that `return = pure`

**Comment by dmp1ce** [comment]
That's what I thought. I must be on an older version. I just used what Stack gave me.
