### ISSUE TITLE
[Question] Empty subcommand ? 

### ISSUE THREAD

**Issue by PierreR** [Gabriel439/Haskell-Turtle-Library#198]
Hi,

In this working example, is there a way to avoid the extra `()` after `Console` ?
In other word, how can I have a working example with just `data Command = Console | Ping (Maybe Text)`
```
data Command
  = Console ()
  | Ping (Maybe Text)
  deriving (Show)

parser :: Parser Command
parser
  = Console <$> (subcommand "console" "Open the specialized salt console" (pure()))
  <|> Ping <$> (subcommand "ping" "Ping your nodes"
               (optional (argText "stack" "Name of a stack")))

main :: IO ()
main = do
  cmd <- options "Greeting script" parser
  case cmd of
        Console () -> putStrLn "Open console"
        Ping (Just x) -> printf ("Ping "%s%" stack\n") x
        Ping Nothing -> printf ("Ping default stack\n")
```

Thanks for your help

**Comment by Gabriel439** [comment]
You can do `Console <$ (subCommand ...)`, which is just a shorthand for `fmap (\_ -> Console) (subCommand ...)`

**Comment by PierreR** [comment]
Oh I see. Many thanks !

**Comment by Gabriel439** [comment]
You're welcome!

**Comment by PierreR** [comment]
Actually for the record I have tried `const Console <$>` which compile but didn't work as it still expect a output.

**Comment by PierreR** [comment]
I have just realized (it is related to `optparse-applicative` ):
```
data Command = Console | Ping
parser
  = Console <$ subcommand "console" "desc" (pure())
  <|> Ping <$ subcommand "ping" "desc" empty
```
both compile but only the first one is correct. Instinctively I would have jumped for the wrong/second option. For some reason, I guess `empty` is kind of related to Nothing while `pure()` expresses `()`. Still ...
