### ISSUE TITLE
[Question] How to spawn a (nix-shell) process ?

### ISSUE THREAD

**Issue by PierreR** [Gabriel439/Haskell-Turtle-Library#199]
Hi,

I can't figure out how to spawn a (nix-shell) process within a Turtle script.

So something like
```
proc "nix-shell" [nix_file] empty
```
Any idea ?

Thanks for your help.

**Comment by Gabriel439** [comment]
What's the error that you get?

**Comment by PierreR** [comment]
I have got a strange:
```
→ pep console prod
Invalid argument `*'

Orchestration command line utility

Usage: pep (console | ping)

Available options:
  -h,--help                Show this help text

Available commands:
  console                  Open the specialized salt console
  ping                     Ping your nodes
```
with the following program:

```
module Main where

import Turtle

projectDir = "/home/vagrant/projects/cicd/salt/salt-shell"

data Command
  = Console Text
  | Ping (Maybe Text)
  deriving (Show)

parser :: Parser Command
parser
  = Console <$> (subcommand "console" "Open the specialized salt console"
                (argText "zone" "ZONE such as dev, staging, testing or prod"))
  <|> Ping <$> (subcommand "ping" "Ping your nodes"
               (optional (argText "stack" "Name of a stack")))


nixCommand :: Text -> IO ()
nixCommand zone = do
  let nix_file = format (s%"/"%s%".nix") projectDir zone
  void $ proc "nix-shell" [nix_file] empty

run (Console zone) = nixCommand zone

run (Ping (Just x)) = printf ("Ping "%s%" stack\n") x
run (Ping Nothing) = printf ("Ping default stack\n")

main :: IO ()
main = options "Orchestration command line utility" parser >>= run
```

**Comment by Gabriel439** [comment]
I cannot reproduce the problem.  I had to add a `{-# LANGUAGE OverloadedStrings #-}` to your program, but then it parsed the command line correctly:

```
$ stack runghc test.hs -- --help
Run from outside a project, using implicit global project config
Using resolver: lts-6.3 from implicit global project's config file: /Users/gabriel/.stack/global-project/stack.yaml
Orchestration command line utility

Usage: test.hs (console | ping)

Available options:
  -h,--help                Show this help text

Available commands:
  console                  
  ping                     
$ stack runghc test.hs -- console prod
Run from outside a project, using implicit global project config
Using resolver: lts-6.3 from implicit global project's config file: /Users/gabriel/.stack/global-project/stack.yaml
error: getting status of ‘/home/vagrant/projects/cicd/salt/salt-shell/prod.nix’: No such file or directory
```

**Comment by Gabriel439** [comment]
However, that was using an older version of `turtle`.  What version are you currently using?

**Comment by PierreR** [comment]
I am using the latest ,`1.3.0` version

**Comment by PierreR** [comment]
As a note, I know that if the `nix ` file is not found it does indeed print the same exact error you show.

**Comment by Gabriel439** [comment]
I still cannot reproduce the problem using `master`

It sounds like this is not a problem with the script you pasted, but rather a problem with the `/home/vagrant/projects/cicd/salt/salt-shell/prod.nix` script that it is in turn calling.  Is that a `turtle` script, too?  Is that a `turtle` script, too?

**Comment by PierreR** [comment]
I just know it works if I simply do `nix-shell /home/vagrant/projects/cicd/salt/salt-shell/prod.nix` 
So I have tried to simply do   "void $ shell "nix-shell -p python" empty" instead. 
No error but it does not drop me into the shell ?

**Comment by Gabriel439** [comment]
This sounds very similar to https://github.com/Gabriel439/Haskell-Turtle-Library/issues/33

Try using the same solution from that issue, which is to wrap the `nix-shell` command in `exec`

**Comment by PierreR** [comment]
I am not sure if that is what you mean but I have tried:
`void $ shell "exec nix-shell -p ruby" empty` without success. I have also tried:
```
run (Console zone) = do
  void $ shell "nix-shell -p ruby" empty
  let cp = (Process.proc "bash" [])
            { Process.std_in  = Process.Inherit
            , Process.std_out = Process.Inherit
            , Process.std_err = Process.Inherit
            , Process.delegate_ctlc = True
            }
  (_, _, _, ph) <- Process.createProcess cp
  void $ Process.waitForProcess ph
```
but no luck either

**Comment by PierreR** [comment]
Just to summarize the minimal code I am trying to run is:
```
main = void $ shell "nix-shell -p ruby" empty
```
And I would like to be dropped in a nix-shell.

If I have get this first step right, I will go and try to use a xxx.nix file.

To put the use case in context I am trying to replace a bunch of zsh aliases (that spawn a interactive nix shell or execute some commands within such a shell) with an more friendly executable. I also need to do a bunch of sanity check that gets quickly messy in a shell script.

**Comment by 3noch** [comment]
@PierreR If you want to use Turtle to provide a shell, you'll actually have to build a minimal shell within Turtle and proxy the commands to a process that started.

**Comment by PierreR** [comment]
@3noch well in that case, I guess the easiest is to keep using some bash functions. That's a bit sad. Note that I don't need to interact with the `nix-shell` process whatsoever. All I want is to provide an utility command line, do some sanity check or initialization using some shell scripts, then spawn a `nix-shell` command.

So I just want to replace something that looks more or less like this (currently in a broken state):
```
check_zone () {
    if [ -z "$1" ]; then
        echo "Expect a zone like prod, staging, dev";
        return 1;
    fi
    echo "$1"
}

_salt-shell-cmd () {
    local zone=$(check_zone $1)
    local project_dir="$HOME/projects/cicd/salt/salt-shell"
    local cmd="$2"
    pushd $project_dir
    if ! [[ -f "${zone}.nix" ]]; then
        ./set_env.nix
    fi
    if [ -n $cmd ]; then
        nix-shell "${zone}.nix" --command "$cmd"
    else
        nix-shell "${zone}.nix"
    fi
    popd
}

pep-repl () {
    _salt-shell-cmd
}
pep-ping () {
    _salt-shell-cmd "ping"
}
```

**Comment by 3noch** [comment]
@PierreR Oh it looks like @Gabriel439 may have a neat solution in #33. @Gabriel439 I would personally love to have an `interactive` function so that I build augmented shells with Turtle more easily.

**Comment by PierreR** [comment]
@3noch well I have already tried it like this:

```
main :: IO ()
main = do
    void $ shell "nix-shell -p ruby" empty
    let cp = (Process.proc "bash" [])
            { Process.std_in  = Process.Inherit
            , Process.std_out = Process.Inherit
            , Process.std_err = Process.Inherit
            , Process.delegate_ctlc = True
            }
    (_, _, _, ph) <- Process.createProcess cp
    void $ Process.waitForProcess ph
```
 but without success

**Comment by 3noch** [comment]
I don't understand why you would run nix-shell and then bash. The bash instance will most certainly not have any nix dependencies.

**Comment by PierreR** [comment]
@3noch Well I really don't understand what I am doing there. I am just mimicking #33. What is your proposition ?

**Comment by PierreR** [comment]
@3noch Ok I finally understand what I was supposed to do with #33 I need to replace "bash" with "nix-shell" ;-)

I will try to go from there and see. Thans for your input.

**Comment by 3noch** [comment]
Yah I'd expect that to go better.

**Comment by PierreR** [comment]
@Gabriel439 so #33 has been working nicely for me:

```
interactive :: Text -> IO ExitCode
interactive c = do
    let
      c' = Text.unpack c
      cp = (Process.shell c')
            { Process.std_in  = Process.Inherit
            , Process.std_out = Process.Inherit
            , Process.std_err = Process.Inherit
            , Process.delegate_ctlc = True
            }
    (_, _, _, ph) <- Process.createProcess cp
    Process.waitForProcess ph
```
Shall I close this issue ? Do you think you will add something alike in Turtle.

**Comment by Gabriel439** [comment]
I think in this case it's probably best to use the `process` library directly since `turtle` doesn't really provide any specific value above and beyond what `process` already provides

**Comment by Gabriel439** [comment]
So, my reasoning for when to integrate something is that there should be some significant improvement over the old API (either by integration with `Pattern`, `Shell`, or `Fold`) or some elegant theoretical justification (like adding a new `Monad`).  The other issue with this is that there are at least four variations on this function if I add it (2 ways of supplying command line arguments and 2 ways of handling failures)

**Comment by PierreR** [comment]
Ok, sound reasonable to me, closing this then.
