### ISSUE TITLE
Question: What is the show of "FilePath"?

### ISSUE THREAD

**Issue by eccstartup** [Gabriel439/Haskell-Turtle-Library#2]
I just find the `show` of `FilePath` wired. It is all right to see that `pwd` returns `FilePath "somepath"`. However, it is inconvenient to see that `view (ls ".")` gives `FilePath "A", FilePath "N",...,FilePath "N"`. Is it impossible to avoid?

**Comment by Gabriel439** [comment]
You can use `toText`, which is one of the included exports.  `toText` gives you the path name and doesn't have the `FilePath` prefix.  I should have documented that somewhere.

**Comment by PierreR** [comment]
So to use a `FilePath` as a text we need to proceed as follow:
```
run (Options {role, zone, extraArgs}) = do
   Right basedir <- toText <$> pwd
   exitCode <- proc "docker" [ "run"
                             , "-w", mountpoint
                             , "-v", basedir <> ":" <> mountpoint
                             , "-t", dockerimg
                             , format cmd role zone (fromMaybe "" extraArgs)
                             ] empty
   exitWith exitCode
```
Is that correct ?

As a minor point I don't understand why there is an `exit` function in Prelude that accepts an `Int` whereas `proc` and `shell` returns an `ExitCode`.

**Comment by Gabriel439** [comment]
That's right.  The easiest way to ignore the `Left` value is to use a pattern match on a bind.

I like your point about `exit`.  I think you're right and it makes more sense for its argument to be a more strongly typed `ExitCode`.  I'll fix that in the next release.

The best solution in my mind would be a `Num` instance for `ExitCode` but that would require an orphan instance.

**Comment by Gabriel439** [comment]
I'm marking this as fixed now that we have the `fp` specifier that @PierreR added in #16, which automatically handles the failure case.

You can now just write:

```haskell
format fp :: FilePath -> Text
```

**Comment by eccstartup** [comment]
:+1:
