### ISSUE TITLE
Format with "%w" strange output

### ISSUE THREAD

**Issue by PierreR** [Gabriel439/Haskell-Turtle-Library#205]
I was using something like:
```
version :: String

foo :: Text -> Text
foo z = format (s%"-"%w%".nix") z version
```
And was quite surprised by the result:
if z == bar => `bar-"0.9.0".nix`

Is this the intended behaviour ?

It actually forces me go with instead: 
```
foo z = z <> "-" <> Text.pack version <> ".nix"
```

**Comment by int-index** [comment]
This is the correct behavior because `w` applies `show`, which for strings performs escaping and adds quotation marks. What you want is

```
format (s % "-" % s % ".nix") z (T.pack version)
```

**Comment by PierreR** [comment]
@int-index Thanks for the info.
