### ISSUE TITLE
It's difficult to work with functions that expect lazy ByteString.

### ISSUE THREAD

**Issue by crocket** [Gabriel439/Haskell-Turtle-Library#209]
Since `Shell ByteString` emits chunks of strict `ByteString`, it's difficult to marshal between `Turtle.Bytes` and functions expecting lazy `ByteString`.

I found it easier to ditch `turtle` and use `optparse-applicative` directly as below when I use functions expecting lazy `ByteString`.

```haskell
#!/usr/bin/env stack
{- stack --install-ghc runghc
   --package optparse-applicative
   --package charsetdetect-ae
   --package iconv
-}
{-# LANGUAGE OverloadedStrings #-}
import qualified Data.ByteString.Lazy.Char8 as C
import Codec.Text.Detect (detectEncodingName)
import Codec.Text.IConv (convert)
import Options.Applicative

optParser :: Parser FilePath
optParser = strArgument (metavar "FILE")

main :: IO ()
main = do
  let desc = "Converts the encoding of a file's content to UTF-8, "
        ++ "and remove carriage returns."
  file <- execParser $ info (helper <*> optParser) (progDesc desc)
  bs <- C.readFile file
  case detectEncodingName bs of
    Nothing -> putStrLn "Charcter encoding detection failed"
    Just "UTF-8" -> putStrLn "Character encoding is already UTF-8"
    Just ce -> do
      putStrLn $ "Detected character encoding : " ++ ce
      C.writeFile file $ C.filter (not . (=='\r')) $ convert ce "UTF-8" bs
```

In the above example, `detectEncodingName` and `convert` expect lazy `ByteString`.
If I used `Turtle.Bytes.input` and `Turtle.Bytes.output` instead of `C.readFile` and `C.writeFile`, verbose marshalling would be necessary.
I think `Turtle.Bytes` needs lazy variants.

**Comment by Gabriel439** [comment]
One solution would be to add a `Turtle.Prelude.lazy` and `Turtle.Bytes.lazy` which are identical to `Turtle.Prelude.strict` and `Turtle.Bytes.strict` except they return lazy `Text`/`ByteString`.  Would that solve your issue?

**Comment by crocket** [comment]
I have two questions.

1. How is lazy `Text` in `Turtle.Prelude.lazy` going to help?
2. Is there a use case for chunks of strict `ByteString` emitted by functions in `Turtle.Bytes`?

**Comment by Gabriel439** [comment]
`Turtle.Prelude.lazy` is just for symmetry since there needs to be feature parity between `Turtle.Prelude` and `Turtle.Bytes`

Chunks of lazy `ByteString`s don't really make sense for any streaming library.  All streaming libraries on Hackage work in chunks of strict `ByteString`s

**Comment by crocket** [comment]
If `Turtle.Bytes.Lazy` or `Turtle.Bytes.lazy` had functions emitting a single chunk of lazy `ByteString`, my issue would be solved. There are functions that expect lazy `ByteString`.

**Comment by Gabriel439** [comment]
I added `Control.Foldl.{Text,ByteString}.lazy` utilities in the latest version of the `foldl` library which fold a stream of strict chunks into a single lazy value.  For example, if you want to read in a file as a lazy `ByteString`, you can write:

```haskell
fold (input "yourfile") Control.Foldl.ByteString.lazy :: IO Data.ByteString.Lazy.ByteString
```

**Comment by crocket** [comment]
I think there better be an example in the tutorial.

**Comment by crocket** [comment]
I finally came to the conclusion that `Shell` is not suitable for charset detection and conversion because those are difficult to do on each line. They have to be done on the entire buffer or a large chunk of buffer.

**Comment by berewt** [comment]
May I  reopen this issue? I faced the same situation and would love to PR a `Turtle.ByteString.Lazy`. Eventhough, as ou said @Gabriel439, the notion of chunk does not make sense, here, nor the notion of `strict`. `strict` can keep is name (for symmetry), and still return a lazy ByteString, but what about `inhandle`? Should we consider a Shell result of one big ByteString?

**Comment by Gabriel439** [comment]
@berewt: Yeah, feel free to reopen this and submit a pull request to add the `lazy` variants
