### ISSUE TITLE
Feature request: parallel

### ISSUE THREAD

**Issue by michelk** [Gabriel439/Haskell-Turtle-Library#21]
It would be great, to have the facility to run e.g. external commands in parallel.

**Comment by 3noch** [comment]
@michelk Take a look at http://hackage.haskell.org/package/turtle-1.0.0/docs/Turtle-Prelude.html#v:fork

**Comment by Gabriel439** [comment]
Yeah, I like this idea.  Maybe generalize it to run arbitrary Haskell commands, which are a superset of external commands.

I'm thinking of perhaps this type:

```haskell
parallel :: [Shell a] -> Shell a
```

For example, this `parallel` shell command:

```
parallel echo ::: A B C :::: def-file
```

... would translate to this `turtle` command:

```haskell
example = do
    ys <- fold (input "def-file") Fold.list
    parallel (do
        x <- ["A", "B", "C"]
        y <- ys
        return (liftIO (print (x, y))) )
```

**Comment by 3noch** [comment]
@Gabriel439 So is this an abstraction of `fork` or is it something entirely different?

**Comment by Gabriel439** [comment]
It might use `fork` internally.  I haven't tried to implement this yet

**Comment by stschiff** [comment]
Unix automatically multithreads pipes, so `cmd1 | cmd2 | cmd3 > out` would run `cmd1`, `cmd2` and `cmd3` in parallel. Would this be possible with the `parallel` function you suggested above?

**Comment by Gabriel439** [comment]
`parallel` wouldn't help for your purposes.  It's intended more as an analog to GNU parallel

This is the one place that `turtle` deliberately departs from how the shell behaves.  `turtle` only spawns a new thread for external processes (i.e. using `inshell` or `inproc`).  `turtle` built-ins do not run in a separate thread.  Instead, they behave more like coroutines and when you compose them you just fuse the coroutines together without introducing any new threads or buffers.

**Comment by stschiff** [comment]
Right, I can see the benefit of a GNU parallel - like function. But regarding my example: I _am_ using `inproc` for the external commands, see example above (edited, forgot the quotes). You are saying that `inproc` spawns a new thread, so perhaps this already does behave like in Unix bash? Is it correct that the line from my example uses three threads?

**Comment by Gabriel439** [comment]
Oh yeah, for your specific example there would be one thread per `inproc`, so it would be equivalent to the shell's behavior

**Comment by stschiff** [comment]
Nice, thanks!

**Comment by domenkozar** [comment]
Here's what I'm using (actually based on @Gabriel439 comment on the blog):

```haskell
parallel :: [a] -> (a -> IO ()) -> Managed ()
parallel (first:rest) action = do
  async <- using $ fork $ action first
  parallel rest action
  liftIO (wait async)
parallel [] _ = return ()
```

Example that ssh using NixOps to each node, checks if it's responding and reboots otherwise:

```haskell
run =   sh $ using $ parallel ["node1" "node2"] rebootIfDown

rebootIfDown :: Text -> IO ()
rebootIfDown node = do
  x <- shell (nixops <> "ssh " <> args <> node <> " -o ConnectTimeout=5 echo -n") empty
  case x of
    ExitSuccess -> return ()
    ExitFailure _ -> do
      echo $ "Rebooting " <> node
      shells (nixops <> "reboot " <> args <> "--include " <> node) empty
```

**Comment by Gabriel439** [comment]
@domenkozar You could simplify the type a little bit further to:

```
parallel :: [IO ()] -> Managed ()
```

Other than that, I really like this!  Could you submit a PR?

**Comment by domenkozar** [comment]
Will do!

**Comment by domenkozar** [comment]
https://github.com/Gabriel439/Haskell-Turtle-Library/pull/196
