### ISSUE TITLE
[Question]: converting the shell 'install' command

### ISSUE THREAD

**Issue by PierreR** [Gabriel439/Haskell-Turtle-Library#211]
I am currently writing a lot of : 
```
shell "install -Dm600 afile.txt ${HOME}/.local/afile.txt" empty
```
Is there a more idiomatic way to convert such shell code ?

**Comment by PierreR** [comment]
As a more general concern, I am wondering how do to deal with string interpolation in general ?

```
# shell
echo "hello" > "$HOME/y.txt"

-- Turtle
testme :: Shell ()
testme = do
  home' <- home
  output (home' <>"/tmp/testme") (pure "hello")
```
Somehow anytime I want string interpolation I looks like I am better served with something alike
``` 
shells "cp $HOME/tmp/testme $HOME/tmp/test3" empty
```

**Comment by Gabriel439** [comment]
So there is a `neat-interpolation` package that you can use:

```haskell
{-# LANGUAGE QuasiQuotes #-}

import NeatInterpolation
import Turtle

testme :: Shell ()
testme = do
    _HOME <- home
    shells [text|cp $_HOME/tmp/testme $_HOME/tmp/test3"] empty
```

**Comment by PierreR** [comment]
@Gabriel439 Thanks for the tip.

I guess it is safer than `shells "cp $HOME/tmp/testme $HOME/tmp/test3" empty` for the same reasons `proc` is safer than `shell` ?

As a matter of fact, the difference between `shell` and `proc` on that matter could probably deserve a bit more explanation
```
  shells "echo $HOME" empty  --> /home/vagrant
  procs "echo" ["$HOME"] empty --> $HOME
```
What do you think ?

**Comment by PierreR** [comment]
Before closing the issue, I would like to ask one side question. In the following code, is `Filesystem.getHomeDirectory` calculated more than once ?

```
test1 = sh $ do
  _HOME <- home
  ...

test2 = sh $ do
  _HOME <- home
  ...

main = do
  test1
  test2

```

**Comment by Gabriel439** [comment]
@PierreR Yes.  The reason why is that the `home` command does not know whether or not the value of the `$HOME` environment variable has changed since the last time it was called

**Comment by PierreR** [comment]
Thanks for the quick reply.

**Comment by 3noch** [comment]
It might be a nice feature to have a frozen environment monad where env vars are cached when entering the monad.
