### ISSUE TITLE
Working on file trees and locking

### ISSUE THREAD

**Issue by passy** [Gabriel439/Haskell-Turtle-Library#215]
This is probably more of a support request than an actual issue, please close if this is not the right place.

I want to work on a file tree and can't quite figure out to work around locking. The simplest version of what I'm trying to do would be this:

```haskell
copyFiles :: FilePath -> FilePath -> Shell ()
copyFiles srcDir targetDir = do
  file <- lstree srcDir
  cp file $ targetDir </> file
```

If I try to evaluate this with `sh $ copyFiles a b`, however, I get a crash from the first item in the source directory:

```
file.hs: /path/to/file: openBinaryFile: resource busy (file is locked)
```

Is this intended behavior? Is there a way to work around this?

**Comment by passy** [comment]
I've just realized that there might actually be an overlap between `srcDir` and `targetDir` in which case this error is absolutely justified. I'll investigate that a bit more and reopen if this turns out to be wrong. :)

**Comment by Gabriel439** [comment]
Yeah, in that case you can just add `guard (srcDir /= targetDir)` before the `cp` (perhaps after canonicalizing them first using `realpath`)
