### ISSUE TITLE
Change `mkdir` so it does not error when the directory already exists ?

### ISSUE THREAD

**Issue by PierreR** [Gabriel439/Haskell-Turtle-Library#216]
I am wondering why `mkdir` is throwing an error when the directory already exists - making the following snippet a bit verbose:  
```
  found_dir <- testdir dir; unless found_dir $ mkdir dir
```
Is it to mimic the shell behavior (on the other hand it is easy to add '-p' in bash script) ? What would be the drawback of changing the [default](https://github.com/Gabriel439/Haskell-Turtle-Library/blob/master/src/Turtle/Prelude.hs#L975) ?

**Comment by Gabriel439** [comment]
You can use `mktree` (equivalent to `mkdir -p`) if you want it to unconditionally succeed

**Comment by PierreR** [comment]
Thanks for the tips !

**Comment by Gabriel439** [comment]
You're welcome!
