### ISSUE TITLE
Ignore certain subdirectories in find

### ISSUE THREAD

**Issue by int-index** [Gabriel439/Haskell-Turtle-Library#222]
I need functionality of `find`, but it'd be nice to ignore certain subdirectories. My use case is finding all `.hs` files but avoiding `.stack-work` and `dist`.

What's the best way to achieve that?

**Comment by mitchellwrosen** [comment]
How about
```haskell
lsif (\path -> pure (\path -> path /= "./.stack-work" && path /= "./dist") "."
```

**Comment by int-index** [comment]
Unlike `find`, it's not recursive. `find` is recursive and does not follow symlinks — I'd like to reuse that logic.

Under the hood `find` uses `lsif` — basically, the ability to add a custom predicate to it would solve my problem.

**Comment by 3noch** [comment]
Isn't `lsif` recursive?

**Comment by int-index** [comment]
Hm. You're right, it is. Then what's missing is a user-facing test for a symlink. Currently it's defined as `isNotSymlink` in a `where` clause in `find`.

**Comment by 3noch** [comment]
Ah it might be nice to export that.

**Comment by mitchellwrosen** [comment]
There is a user-facing test for symlink: 

```haskell
lstat :: MonadIO io => FilePath -> io FileStatus
isSymbolicLink :: FileStatus -> Bool
```

**Comment by int-index** [comment]
OK. Weird that `find` doesn't use it.
