### ISSUE TITLE
Use `stack script` instead of `stack runghc`

### ISSUE THREAD

**Issue by k-bx** [Gabriel439/Haskell-Turtle-Library#223]
Latest stack release brought a very convenient option for scripts `stack script`. See [docs](https://docs.haskellstack.org/en/stable/GUIDE/#writing-independent-and-reliable-scripts) for why it was needed.

**Comment by k-bx** [comment]
One caveat to consider: no way to provide `--ghc-options` that I could find to add `-threaded`

**Comment by Gabriel439** [comment]
This was fixed by https://github.com/Gabriel439/Haskell-Turtle-Library/commit/6d3a40979467ca9e63c6f6bdbad0b4232e3d6e73
