### ISSUE TITLE
Some nice helpers for environment variables

### ISSUE THREAD

**Issue by taktoa** [Gabriel439/Haskell-Turtle-Library#225]
I ended up writing these two functions while using Turtle recently. I'm too busy to make a PR but if you want to add them feel free (I also think there it might be interesting to use `Managed` here as well):

```haskell
import qualified Data.HashMap.Strict as HM

wrapEnv :: (MonadIO m) => m a -> m a
wrapEnv cb = do
  saved <- env
  result <- cb
  restoreEnv saved
  pure result

restoreEnv :: (MonadIO m) => [(Text, Text)] -> m ()
restoreEnv = go . HM.fromList
  where
    go desired = do
      current <- HM.fromList <$> env
      mapM_ unset (HM.keys (HM.difference current desired))
      mapM_ (uncurry export) desired
      after <- HM.fromList <$> env
      when (desired /= after) $ fail "restoreEnv: assertion failed"
```

**Comment by Gabriel439** [comment]
Why does `wrapEnv` not restore the environment exactly the way it was before?  i.e.:

```haskell
wrapEnv cb = do
    saved  <- env
    result <- cb
    mapM_ (uncurry export) saved
    return result
```

**Comment by taktoa** [comment]
Suppose you set a new variable `FOO`. Then `mapM_ (uncurry export) saved` won't unset `FOO`.

**Comment by Gabriel439** [comment]
Ah, I see!  Got it :)

**Comment by taktoa** [comment]
Just fixed a small bug in the assertion

**Comment by 3noch** [comment]
This seems like a somewhat dangerous way of achieving this. If you want to open a subprocess with different env then you can set the env when you fire up the process. If you want a different env in your own Turtle scripts, then you should likely use something like `Reader` or just pass them around. Setting env globally for a while is not at all thread-safe.

**Comment by taktoa** [comment]
That's a very good point, but I don't think Turtle has anything like `execve`; perhaps that would be a better addition?

**Comment by Gabriel439** [comment]
Also, what is the reason for the assertion at the end?  Under what circumstances would the environment rollback fail?

**Comment by taktoa** [comment]
Oh, that was just a CYA measure; assuming there are no bugs in my code (famous last words) it shouldn't fail.

**Comment by Gabriel439** [comment]
Given that this is not thread safe like @3noch mentioned, perhaps the scope of this should change to making it easier to fork a subprocess with a custom environment?

**Comment by taktoa** [comment]
Definitely agreed. The biggest helpful thing would be if `Turtle.Prelude.streamWithErr` was somehow exposed (maybe in a `Turtle.Internal` module?); as it is I had to copy it to my project to get a thread-safe `execve`.
