### ISSUE TITLE
Filtering a list of Lines - safe operations on Line

### ISSUE THREAD

**Issue by miguel-negrao** [Gabriel439/Haskell-Turtle-Library#227]
Filtering a list of Lines is safe with regards with introducing newlines. Currently to filter a list of lines one has to convert the list of Lines to list of Text, filter that, then convert back and concat, so we lose the information that the text didn't contain newlines.  How can this be solved ? Perhaps a filter :: (Text->Bool) ->  [Line] -> [Line] function could be added that just calls the generic filter internally ?

The same is probably true for other operations such as Data.Text.filter :: (Char -> Bool) -> Text -> Text.

**Comment by GregorySchwartz** [comment]
Converting back uses `textToLines`, right? So by definition they do not have newlines in them?

**Comment by int-index** [comment]
> Perhaps a filter :: (Text->Bool) -> [Line] -> [Line] function could be added that just calls the generic filter internally ?

Isn't it trivial to define? `filterLines p = filter (p . lineToText)`.

**Comment by miguel-negrao** [comment]
> Perhaps a filter :: (Text->Bool) -> [Line] -> [Line] function could be added that just calls the generic filter internally ?
> 
> Isn't it trivial to define? filterLines p = filter (p . lineToText).

Yes, it is... sorry, only thought about that one after posting.
Although, for Data.Text.filter I think that wouldn't work...
