### ISSUE TITLE
Unexpected newlines for Bytes

### ISSUE THREAD

**Issue by GregorySchwartz** [Gabriel439/Haskell-Turtle-Library#228]
I don't have a showable example file yet, but if the answer is not immediately obvious I can try to generate one.

I have .gz files which I thought I could read as a shell with Turtle using `join . fmap (select . textToLines . T.decodeUtf8) . Bytes.inproc "zcat" [] . Bytes.input $ "file.gz"`, but unfortunately while this worked very well with many lines in the file, there were a few that were divided `up` into several lines that should have just been one line (based on `zcat` in the terminal).

However, using `decompress` from the `zlib` library,

```
    contents <- liftIO
                      . fmap (T.decodeUtf8 . BL.toStrict . decompress)
                      . BL.readFile
                      . T.unpack
                      . format fp
                     $ file

    let fileLines = select . concatMap textToLines . T.lines $ contents
```

*did* work. Would you expect there to be a difference using the two? Is there some definition of "Line" in `Bytes` that is doing something that I would not expect (again it worked for many lines but not all)?

**Comment by Gabriel439** [comment]
The `Turtle.Bytes` module does not use line boundaries at all.  It uses arbitrary chunk sizes, since the notion of a line is encoding specific

**Comment by GregorySchwartz** [comment]
Well that answers everything then and your explanation appears in the documentation of the module as well.
