### ISSUE TITLE
shellStrict gives back stdout as Text while inshell gives it back as Line

### ISSUE THREAD

**Issue by PierreR** [Gabriel439/Haskell-Turtle-Library#230]
In order to stream one process to another when the first succeed, I will do something like:

```      
e <- loop 10 $ do
        o0 <- shellStrict cmd0 empty
        case o0 of
          (ExitFailure _, _) -> do
            echo "Retrying in 10 sec"
            liftIO $ threadDelay (10 * 1000 * 1000)
            continue
          (ExitSuccess, stdout) -> do
            shell cmd1 (pure $ unsafeTextToLine stdout)
            break
```
I am wondering why `shellStrict` returns `io (ExitCode, Text)` given that `inshell` returns `Shell Line` ?

**Comment by Gabriel439** [comment]
`shellStrict` and `inshell` are not supposed to behave the same.  `shellStrict` was written for people who did not want to use the streaming `Shell` API

Also, the better way to reinject the text returned by `shellStrict` is to use `select (textToLines stdout)`

**Comment by PierreR** [comment]
Is that correct to say that with `inshell` you get the streaming API but at the same time you lose the ability to care about the error code of the command that produces such stream ?

**Comment by Gabriel439** [comment]
That's correct.  That's because `Shell` does not provide a place to store the final return value of the stream

**Comment by PierreR** [comment]
Thanks for your help !

**Comment by Gabriel439** [comment]
You're welcome!
