### ISSUE TITLE
[Question] cp -r dir0 dir1

### ISSUE THREAD

**Issue by PierreR** [Gabriel439/Haskell-Turtle-Library#231]
There is a `cp` function in Turtle.Prelude. Is there something similar for `cp -r doc docdir/`.

I am currently using `proc "cp" ["-r", "doc", format fp docdir] empty`

Thanks for your help.

**Comment by Gabriel439** [comment]
There is now!  Let me know if this pull request is what you had in mind: https://github.com/Gabriel439/Haskell-Turtle-Library/pull/232

**Comment by PierreR** [comment]
Works nicely. Out of curiosity is `cptree` better performance wise compared to `proc "cp" ["-r", "doc", format fp docdir] empty` ?

Thanks

**Comment by Gabriel439** [comment]
@PierreR: My guess is that using Unix `cp` will probably be faster but I haven't benchmarked it.  It's very hard to beat Unix utilities for performance
