### ISSUE TITLE
executing shell instruction in bash

### ISSUE THREAD

**Issue by KasperJanssens** [Gabriel439/Haskell-Turtle-Library#234]
It seems that, when using 'shell' to execute an instruction, it goes to /bin/sh by default. I would like to use /bin/bash for this. Bash is my default shell, but somehow Turtle tries to use sh. Running inside a docker, ubuntu 16.04, stack lts-8.12.

**Comment by mitchellwrosen** [comment]
This is hard-coded in the `process` library, I think you'll have to use `system` to work around it.

**Comment by KasperJanssens** [comment]
Hmm, I checked System.Process a little but I don't really see how. Do you have an idea or do you suggest that I log an issue for the process library?

**Comment by mitchellwrosen** [comment]
Ah, you could still use `turtle` by manually calling `/bin/bash`, like so:

```
proc "/bin/bash" ["echo", "hi"] mempty
```

There's no way conveniently call `echo hi` using a shell other than `/bin/sh` without specifying it explicitly as above. You'd have to file an issue in the process library to solve that. It doesn't seem unreasonable to use `$SHELL` instead.

**Comment by KasperJanssens** [comment]
At the process library they indeed had the same discussion and concluded that keeping the current hard coded sh solution was best. Might it be an idea to create a helper function in turtle that runs bash? Right now I will likely be creating the helper function myself in most of my scripts otherwise. I understand of course that you cannot create helpers for all shells in existence, but bash is rather often used I'd think. Anyway, closing.
