### ISSUE TITLE
[Options]: Failing parser when both fields of a record are Nothing ?

### ISSUE THREAD

**Issue by PierreR** [Gabriel439/Haskell-Turtle-Library#236]
Given such a parser:
```
data Arg = Arg
  { _role :: Maybe Text
  , _group :: Maybe Text
  }
pArg = Arg <$> optional (optText "role" 'r' "role of x") <*> optional (optText "group" 'g' "group of x")
```
Is there a way to get back the help (by making the parser to fail somehow) when no input is entered by the user. So if the executable is called `foo`, display the help when the user enter `foo` alone.

I know I can easily workaround the problem by dealing with this case on the main function (outside of the parser) but I am quite curious to know if it is possible to keep all the validation rules inside the parser.

Sorry in advance if this question belongs to `optparse-applicative` ...

**Comment by Gabriel439** [comment]
Yes!  You can definitely do this.  The trick is to recognize that there are three valid states:

* Both `--role` and `--group` are defined
* Only `--role` is defined
* Only `--group` is defined


... and then define your parser as a choice between those three alternatives:

```haskell
parseRole  = optText "role" 'r' "role of x"
parseGroup = optText "group" 'g' "group of x"

parseArg = parseArg0 <|> parseArg1 <|> parseArg2

parseArg0 = adapt <$> parseRole <*> parseGroup
  where
    adapt role group = Arg { _role = Just role, _group = Just group }

parseArg1 = adapt <$> parseRole
  where
    adapt role = Arg { _role = Just role, _group = Nothing }

parseArg2 = adapt <$> parseGroup
  where
    adapt group = Arg { _role = Nothing, _group = Just group }
```

**Comment by PierreR** [comment]
I have to admit my real use case has 4 `Maybe` fields. That means 15 definitions, doesn't  ;-)

**Comment by Gabriel439** [comment]
Yep!  Pretty much :)

With an `Applicative`-only interface there is no way to check the state of all four fields and fail.  You'd have to do that outside of the `Parser` logic.  The reason why is that the `Parser` needs a way to render to the user all the permutations of options that are valid

For example, using the code I gave above the corresponding `--help` output would render something like this:

```
(--role TEXT --group TEXT | --role TEXT | --group TEXT)
```

... but the moment you introduce the ability to inspect the results of fields and fail on their values then there's no easy way for the `Parser` to auto-generate usage information that conveys to the user which permutations of flags are valid

However, it's also really strange to have a record where 1, 2, 3, or 4 fields may be present but not 0.  Do you have more context on why you require that invariant?  There might be a better way to model your input

**Comment by PierreR** [comment]
You might be right actually. Now that I think about it a bit more, all 15 permutations are not valid. I will give it a shot.

Thanks for your explanation !

**Comment by Gabriel439** [comment]
You're welcome! :)

**Comment by PierreR** [comment]
After trying this a bit, there are a couple of drawback.

The help is actually cluttered:
```
Header description

Usage: sandbox ((-r|--role ROLE) (-g|--group GROUP) | (-r|--role ROLE) |
               (-g|--group GROUP))

Available options:
  -h,--help                Show this help text
  -r,--role ROLE           role of x
  -g,--group GROUP         group of x
  -r,--role ROLE           role of x
  -g,--group GROUP         group of x
```
Then to my surprise, it doesn't work:
```
λ  pi3r/haskell/sandbox → ~/.local/bin/sandbox -g jenkins                                                                                                                                                                                
Missing: (-r|--role ROLE)
```
The code is a copy/paste:
```
data Arg = Arg
  { _role :: Maybe Text
  , _group :: Maybe Text
  }

parseRole  = optText "role" 'r' "role of x"
parseGroup = optText "group" 'g' "group of x"

parseArg = parseArg0 <|> parseArg1 <|> parseArg2

parseArg0 = adapt <$> parseRole <*> parseGroup
  where
    adapt role group = Arg { _role = Just role, _group = Just group }

parseArg1 = adapt <$> parseRole
  where
    adapt role = Arg { _role = Just role, _group = Nothing }

parseArg2 = adapt <$> parseGroup
  where
    adapt group = Arg { _role = Nothing, _group = Just group }

run (Arg r g) =
  putText (Text.intercalate " " (catMaybes [g, r]))

main = options "Header description" parseArg >>= run
```

**Comment by Gabriel439** [comment]
Yeah, at this point it is an issue with the `optparse-applicative` library (especially the fact that it doesn't work).  `turtle`'s option parser is just a very thin wrapper around `optparse-applicative`
