### ISSUE TITLE
optText with no ArgName, switch with no ShortName

### ISSUE THREAD

**Issue by PierreR** [Gabriel439/Haskell-Turtle-Library#237]
The [opt function](https://github.com/Gabriel439/Haskell-Turtle-Library/blob/master/src/Turtle/Options.hs#L163) takes a mandatory `ArgName` argument.

I have encountered several situations where I'd prefer to define a short name only (and the reverse for `switch`). 

I am actually facing a case where it is not just a nuisance ... Do you believe `ArgName` could be made 'optional' or is it too much of a breaking change at this point ?

Ideally it would be mandatory for users to specify either one of the two `ArgName`or `ShortName` or both. 

If I have to go and use `optparse-applicative` for this, that's quite ok by me.

Cheers

**Comment by Gabriel439** [comment]
Yeah, you will have to use `optparse-applicative` for this purpose.  The `Turtle.Options` module tries to be a little bit opinionated and this one of those things that it is opinionated on

**Comment by PierreR** [comment]
OK no problem ;-)
