### ISSUE TITLE
Question about fold vs Fold.fold signature

### ISSUE THREAD

**Issue by PierreR** [Gabriel439/Haskell-Turtle-Library#24]
Is there a reason why `fold` from `turtle` has the `Fold` in second position while `fold` from `foldl` has it at first position ?

```haskell
-- turtle
fold :: Shell a -> Fold a b -> IO b
-- foldl
fold :: Foldable f => Fold a b -> f a -> b
```
It seems a bit counterintuitive to me.

**Comment by Gabriel439** [comment]
I did this mainly for consistency with `Turtle.Shell.foldIO` (which is the newtype unwrapper for `Shell` and also takes the fold in the second position).

**Comment by PierreR** [comment]
Thanks for the answer.

I still need to take a deeper dive into the library to understand the `Shell` wrapper (why it is defined that way).

**Comment by Gabriel439** [comment]
Basically, `Shell` is the simplest type I could think of that could implement `select`, `using`, and `liftIO`.  Those three functions are the specification for what operations that `Shell` minimally had to support and the proof that `Shell` is implemented correctly is that the implementations of `select`/`using`/`liftIO` obey the laws outlined at the top of the `Turtle.Shell` module.  Also `Shell` has to obey any other relevant type class laws, too (like `Monad`/`MonadPlus`, etc.)
