### ISSUE TITLE
Add a `pathToLine` utility?

### ISSUE THREAD

**Issue by Gabriel439** [Gabriel439/Haskell-Turtle-Library#242]
One very common use case I run into for `unsafeTextToLine` is when dealing with `FilePath`s.  I'm not sure if paths can contain newline characters, but if they can't then it would be worth adding a safe `pathToLine` utility

**Comment by int-index** [comment]
Paths can contain newlines. See #203

**Comment by Gabriel439** [comment]
Oh, never mind, then! :)
