### ISSUE TITLE
Homogenous, arbitrarily-long list of positional arguments

### ISSUE THREAD

**Issue by deepfire** [Gabriel439/Haskell-Turtle-Library#243]
It seems like `Turtle.Options` is missing a way to allow the user to define parsers for arbitrarily-long positional argument lists, as can be illustrated by the following fictional command help:

```
foo.hs [--switch] [--option] CMD [ARGS...]
```

**Comment by Gabriel439** [comment]
Actually, if you wrap the positional parser for one `ARG` with `many` it should do the right thing and parse zero or more `ARG`s and also render the `--help` usage correctly, too

**Comment by deepfire** [comment]
Great!  Thank you!
