### ISSUE TITLE
Throw IO exception in `stream`

### ISSUE THREAD

**Issue by mitchellwrosen** [Gabriel439/Haskell-Turtle-Library#245]
Hello!

Is there a reason why `stream` ignores the `ExitCode` of the process? Since there is no room for a proper "return value" as in pipes, perhaps throwing an exception is preferable to doing nothing.

My use-case is logging the output of a process inside some larger script; if the sub-process fails, so should the whole script:

```haskell
runFoo :: Shell (Either Line Line)
runFoo = inshellWithErr "foo" empty

-- Flatten stdout and stderr
runFoo' :: Shell Line
runFoo' = fmap (either id id) runFoo

main :: IO ()
main = sh $ do
  output "logfile" runFoo'
  ...
  -- should not be reached if foo fails
  ...
```

Thanks!

**Comment by Gabriel439** [comment]
Oh, that was purely an oversight on my part.  I agree that it should not ignore the exit code.  I will submit a fix for this soon

**Comment by Gabriel439** [comment]
Alright, I have a fix for this up here: https://github.com/Gabriel439/Haskell-Turtle-Library/pull/248

Let me know if that's what you had in mind

**Comment by mitchellwrosen** [comment]
Looks good! I pushed a couple doc fixes to the branch
