### ISSUE TITLE
sed: `begins` matches pattern in middle of string

### ISSUE THREAD

**Issue by huggablemonad** [Gabriel439/Haskell-Turtle-Library#250]
Slightly modified example from #49:

```haskell
>>> view (sed (begins ("ABC" *> pure "123")) "DEFABC")
Line "DEF123"
```

Unix sed returns the string `DEFABC`, which was what I was expecting. Is there a way to have it behave like Unix sed?

I'm using turtle-1.4.1 and GHC-8.0.1.

**Comment by Gabriel439** [comment]
No, there is no way to get it to behave like Unix `sed` in this regard without changing the `sed` utility itself

The only solution that I can think of for this is to provide separate variations on `sed` for matching the prefix, suffix, or entirety of the string (i.e. `sedPrefix`, `sedSuffix`, and `sedEntire`).  Would that work for you?

**Comment by huggablemonad** [comment]
Yes, that would work! But wouldn't `inplace` need similar variations as well?

**Comment by Gabriel439** [comment]
Yes, I will add variations on `inplace`, too
