### ISSUE TITLE
Is there an elegant and concise way to turn `Pattern (a, b)` into `Map a b`?

### ISSUE THREAD

**Issue by crocket** [Gabriel439/Haskell-Turtle-Library#257]
Below is my sample code for parsing xorg options.

```haskell
import Turtle
import qualified Control.Foldl as Fold
import qualified Data.Map.Strict as M

fmap M.fromList $ flip fold Fold.mconcat $ do
  output <- inproc "blah" [] empty
  let key = between (char '"') (char '"') (plus letter)
      val = between (char '"') (char '"') decimal
      keyVal = (,) <$> (key <* spaces1) <*> val
      pat = spaces1 *> text "Option" *> spaces1 *> keyVal <* spaces
  return $ match pat (lineToText output)
```

The `do` block's type is `Shell [(Text, Num)]`.
`flip fold Fold.mconcat` removes empty matches and turns `Shell [(Text, Num)]` into `IO [(Text, Num)]`.

`fmap M.fromList` produces `IO (Map Text Num)`.

I wish `flip fold Fold.map` could replace `fmap M.fromList` and `flip fold Fold.mconcat`.
The following snippet is more verbose but still gets the job done.

```haskell
import Turtle
import qualified Control.Foldl as Fold
import qualified Data.Map.Strict as M

flip fold Fold.map $ do
  output <- inproc "blah" [] empty
  let key = between (char '"') (char '"') (plus letter)
      val = between (char '"') (char '"') decimal
      keyVal = (,) <$> (key <* spaces1) <*> val
      pat = spaces1 *> text "Option" *> spaces1 *> keyVal <* spaces
  case match pat (lineToText output) of
    [] -> empty
    m:_ -> return m
```

Does anyone know a concise and elegant way to do this?
I surmise

```haskell
listToAlternative :: Alternative f => [b] -> f b
listToAlternative [] = empty
listToAlternative m:_ = return m
```

can be a solution.

**Comment by crocket** [comment]
I figured out that `flip fold (Fold.foldMap (take 1) M.fromList)` or `flip fold (Fold.foldMap id M.fromList)` can replace `fmap M.fromList $ flip fold Fold.mconcat`. But, `Fold.foldMap` is more difficult to understand.

**Comment by Gabriel439** [comment]
There is a more succinct way to take the first result from a `match` if you are inside of a `Shell` `do`-block:

```haskell
flip fold Fold.map $ do
  output <- inproc "blah" [] empty
  let key = between (char '"') (char '"') (plus letter)
      val = between (char '"') (char '"') decimal
      keyVal = (,) <$> (key <* spaces1) <*> val
      pat = spaces1 *> text "Option" *> spaces1 *> keyVal <* spaces
  m:_ <- return (match pat (lineToText output))
  return m
```

This takes advantage of the fact that a pattern match failure when binding a value is equivalent to calling `fail`, and `Shell` defines `fail` to be `empty` (same as `Maybe` and `[]`)

**Comment by crocket** [comment]
Thanks.

**Comment by Gabriel439** [comment]
You're welcome!
