### ISSUE TITLE
implement `MonadCatch` for `Shell`

### ISSUE THREAD

**Issue by lynnard** [Gabriel439/Haskell-Turtle-Library#259]
I just started using turtle again after a while and run into situations where having a `MonadCatch` instance for `Shell` would make my life much simpler.

Essentially, some actions do still fail i.e., `input` when encoding is not UTF8.

Two ideas:

1. implement `MonadCatch` as in the subject
2. modify `Shell` to always run in `EitherT IO` (or `ExceptT`)

**Comment by Gabriel439** [comment]
The absence of `MonadCatch` is intentional.  See this comment which explains how `catch` is not well-behaved for `Shell`:

https://github.com/Gabriel439/Haskell-Turtle-Library/issues/139#issuecomment-192754360

**Comment by lynnard** [comment]
Thanks for the excellent explanation in the link. It appears `begin0` is indeed quite nasty in preventing us from writing a valid instance.

Although it makes me think - do we really need `begin` to be of type `m x`? Assume we can make a new type `FoldM1` i.e.,

```
data FoldM1 = FoldM1 (x -> a -> m x) x (x -> m b)
```

We can always translate `FoldM` to `FoldM1`

```
translate :: FoldM -> FoldM1
translate (FoldM step begin done) = FoldM1 step' Nothing done'
  where
    step' Nothing a = do
      x <- begin
      x' <- step x a
      return $ Just x'
    step' (Just x) a = step x a
    done' Nothing = begin >>= done
    done' (Just x) = done x
```

So at least we don't have to lose or break any existing functionality. 

With `FoldM1` you will have `Shell`'s '`return` defined as

```
return a = Shell $ \(FoldM1 step begin done) -> step begin a >>= done
```

And now we can define `catch` with the obvious implementation and `throw` with

```
throw e = Shell $ \_ -> throwIO e
```

And Monad law is *not* violated.

**Comment by Gabriel439** [comment]
Yeah, that would fix the problem, but then we wouldn't be able to use certain `FoldM`s such as `vectorM` or `random`/`randomN` from the `foldl` library.  More generally, it would be a pretty breaking change since users may also have their own custom `FoldM`s that they are using to fold `Shell`s

However, you can still properly acquire and dispose of resources in a `Shell` even without using `catch`.  For example, given the following acquisition and release functions:

```haskell
open :: IO A

close :: A -> IO ()
```

... you can wrap those in `bracket`:

```haskell
bracket open close :: (A -> IO r) -> IO r
```

... and then wrap that in `Managed` using `Control.Managed.managed`

```haskell
managed (bracket open close) :: Managed A
```

... and then promote that to a `Shell` with `using`:

```haskell
using (managed (bracket open close)) :: Shell A
```

If that doesn't fit your use case, another approach is to `fold` the `Shell` to turn it back into an `IO` action

Also, in many cases you do have access to the original `IO` action that you want to `catch`, in which case you just wrap that in `catch` instead of wrapping the `Shell` in `catch`

**Comment by lynnard** [comment]
OK, what I'm trying to do is to compose `Shell`s together easily with error catching. E.g.

```
import qualified Data.ByteString.Base64 as B64
import qualified Data.Text.Encoding as T

readFile :: FilePath -> Shell Line
readFile file = input file `catch` \_ -> unsafeTextToLine . T.decodeUtf8 . B64.encode <$> Bytes.input file
```

Right now I'm forced to unpack the `input` actions into `IO`, and catching at the `IO` level - it doesn't feel like composition and I'm surprised that a well-designed lib like turtle wouldn't allow me to compose `Shell a` as building blocks in this case.

I understand my idea before might feel like a sledgehammer for this problem; but if one really wants to go down that lane it's not impossible to keep all backwards compatibility:

```
data Shell = Shell { _foldIO1 :: forall r. FoldM1 IO a r -> IO r }

_foldIO :: Shell a -> (forall r. FoldM IO a r -> IO r)
_foldIO (Shell f) fd = f (translate fd)
```

This of course builds upon the idea that `FoldM` is always translatable to `FoldM1` as I previously mentioned.

**Comment by Gabriel439** [comment]
Alright, I'm convinced and I'll make the change.  I'll open up a pull request soon that you can review

**Comment by lynnard** [comment]
Wow, that's awesome and really quick :) Let me know if you need any help.

Gabriel Gonzalez writes:

> Alright, I'm convinced and I'll make the change. I'll open up a pull
> request soon that you can review
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.*


--
Lingnan Dai

**Comment by Gabriel439** [comment]
Alright, I have a pull request out with the proposed change: https://github.com/Gabriel439/Haskell-Turtle-Library/pull/268

Give that a test drive and let me know if that satisfies your use case.  If it does then I'll merge it

**Comment by lynnard** [comment]
Sorry for the late reply, it has been really busy for me for the past two weeks...

I just tried this out on my pet project and it worked brilliantly, thank you! I think this is good to merge.

**Comment by Gabriel439** [comment]
Thank you for the suggestion! :)
