### ISSUE TITLE
Q?: idiomatic translation of `test1 && test2`

### ISSUE THREAD

**Issue by PierreR** [Gabriel439/Haskell-Turtle-Library#27]
What is the idiomatic way for combining shell commands and fails as soon as one exits with a code > 0 ?

I have created 3 files "test1, test2, test3" each failing with `exit 1`, `exit 2` and `exit 3`:

```
test1 = shell "./test1" empty
test2 = shell "./test2" empty
test3 = shell "./test3" empty
main = do
  test1 >> test2 >> test3 -- return an exitcode of 3 (but I want 1)
```

**Comment by Gabriel439** [comment]
Probably the easiest way would be to create another utility similar to `shell`/`proc` that rethrows any non-zero exit code.  I just need a good name for this utility.

In the short-term, you can also do:

```haskell
example = do
    ExitSuccess <- test1
    ExitSuccess <- test2
    ExitSuccess <- test3
    ...
```

**Comment by 3noch** [comment]
As an analog: Shake's [`cmd`](http://hackage.haskell.org/package/shake-0.14.3/docs/Development-Shake-Command.html#v:cmd) will throw on non-zero exit codes, but only if the exit code is not captured by the program.

**Comment by Gabriel439** [comment]
Actually, it may be as simple as providing these two functions:

```haskell
(.&&.) :: IO ExitCode -> IO ExitCode -> IO ExitCode

(.||.) :: IO ExitCode -> IO ExitCode -> IO ExitCode
```

Then you could write:

```haskell
test1 .&&. test2 .&&. test3
```

The benefit of this approach is that it's backwards-compatible, works with both `shell` and `proc` and also resembles Bash syntax.

Would that solution be okay with you?

**Comment by PierreR** [comment]
Sounds good to me ;-)
