### ISSUE TITLE
Turtle.Prelude should contain a function to convert Turtle.FilePath to Prelude.FilePath 

### ISSUE THREAD

**Issue by michelk** [Gabriel439/Haskell-Turtle-Library#274]
I was just struggling a bit with that. And looking at stackoverflow, others as well.

**Comment by Gabriel439** [comment]
Yeah, I agree that it should.  I actually thought that it re-exported `System.FilePath.encodeString` but I just checked and it does not.  I'll update the package and mention this common issue in the FAQ section of the tutorial

**Comment by michelk** [comment]
Great, thanks.

**Comment by Gabriel439** [comment]
You're welcome! :)
