### ISSUE TITLE
Stackage `lts-10` and `Win32 < 2.4`

### ISSUE THREAD

**Issue by sgraf812** [Gabriel439/Haskell-Turtle-Library#278]
Appearently, `turtle-1.4.5` made it into Stackage LTS 10 (yay?!), which includes `Win32-2.5.4.1` in its package set. Unfortunately, that seems to be incompatible with turtle. This probably slipped CI because there isn't really a good free CI story for Windows.

**Comment by Gabriel439** [comment]
No problem.  I will try to fix this over the weekend.  I have a local Windows machine I can use for testing `turtle` on Windows

**Comment by Gabriel439** [comment]
Closing, since I assume that #279 fixes this issue.  Feel free to reopen if there is still more work to do
