### ISSUE TITLE
Simple use of fork fails with "Exception: thread killed"

### ISSUE THREAD

**Issue by peti** [Gabriel439/Haskell-Turtle-Library#303]
When I compile and run the following simple program

~~~
{-# LANGUAGE OverloadedStrings #-}

import qualified Control.Foldl as Fold
import Turtle

main :: IO ()
main = do
  hs <- toList $ do sec <- select [1..3]
                    fork (procs "sleep" [format u sec] empty)
  mapM_ wait hs

toList :: MonadIO io => Shell a -> io [a]
toList = flip fold Fold.list
~~~

then I get the following error:

    turtle: thread killed

Apparently, the `sleep` commad never even starts up successfully.I don't see it in the process list, at least. Anyway. I wonder what I'm doing wrong here? I'm using the latest turtle version with GHC 8.4.1 in Linux/x86_64.

**Comment by Gabriel439** [comment]
One way to explain this is that your code equivalent to:

```haskell
sleep sec = procs "sleep" [format u sec] empty

main = do
    h1 <- withAsync (sleep 1) (\h -> return h)
    h2 <- withAsync (sleep 2) (\h -> return h)
    h3 <- withAsync (sleep 3) (\h -> return h)
    mapM_ wait [ h1, h2, h3 ] 
```

The `Async`s named `h1`, `h2`, and `h3` have each already been disposed of after their respective `withAsync`s completed, so if you `wait` on them outside of the `withAsync` scope you get the `thread killed` exception.

The general rule of thumb is that the `Shell` type constructor is like the `Managed` type constructor: you don't want to return an acquired resource like a `Handle` or `Async` from the `Shell`.  There is also no need to do so: the acquired resource is already automatically disposed of by the `Shell`.

The above command also explains why the `sleep` command doesn't start up correctly.  Within the nested `withAsync`s you `return` the result immediately so the `sleep n` threads are all canceled instantly.

If you want to `wait` on each `Async`s to complete, you can change the code to:

```haskell
main = sh $ do
    sec <- select [1..3]
    h <- fork (procs "sleep" [format uu sec] empty)
    wait h
```

... which is equivalent to:

```haskell
main = do
    withAsync (sleep 1) (\h -> wait h)
    withAsync (sleep 2) (\h -> wait h)
    withAsync (sleep 3) (\h -> wait h)
```

If you want to do them in parallel then you need a parallel version of the `select` combinator, which doesn't exist yet but could be implemented

**Comment by mitchellwrosen** [comment]
A parallel `select` sounds like a really powerful scripting abstraction. I wonder what a parallel `Shell` might look like...

**Comment by peti** [comment]
Thank you very much for the comprehensive response. I did not realize that I cannot leave a `Shell` without terminating all allocated resources, but obviously this makes perfect sense. Now I am left wondering, however, how I could implement the following use-case:

Suppose a command `foo` performs some crazy expensive computation and prints a result to `stdout` every couple of minutes. Now, when that happens then I want to run some other command, `bar`, which needs that output as an argument. In plain Bourne shell, this would be similar to a construct like the following:

    foo | xargs --max-lines=1 --max-procs=0 bar

The point is that `foo` and `bar` really overlap each other; `bar`s are started up while `foo` is still running. How would I best implement something like that in `turtle`?

**Comment by Gabriel439** [comment]
@peti: Note that you can still acquire resources such as `Async`s inside the `Shell` and pass them out of the `Shell`.  You just can't use `Turtle.fork`, since `fork` is a wrapper around `withAsync`.  If you fixed your original example to use `async` instead of `fork`, then it would work:

```haskell
{-# LANGUAGE OverloadedStrings #-}

import Control.Concurrent.Async (async)
import Turtle

import qualified Control.Foldl as Fold

main :: IO ()
main = do
  hs <- toList $ do sec <- select [1..3]
                    liftIO (async (procs "sleep" [format u sec] empty))
  mapM_ wait hs

toList :: MonadIO io => Shell a -> io [a]
toList = flip fold Fold.list
```

So just switching from `fork` to `async` might be all that you need to do

**Comment by peti** [comment]
Yes, that works like a charm! Thank you very much for your help. :-)

**Comment by Gabriel439** [comment]
You're welcome! :)

**Comment by PierreR** [comment]
@Gabriel439 I am left wondering if `fork` is really a good name for the wrapper. Nothing is telling the user that is such a wrapper around `withAsync`.
