### ISSUE TITLE
dmenu (graphical menu program) doesn't show

### ISSUE THREAD

**Issue by miguel-negrao** [Gabriel439/Haskell-Turtle-Library#308]
The following code works fine in ghci, a (graphical) menu appears, but doesn't work on the binary compiled with cabal, the menu doesn't appear and the program stays blocked.

```
main :: IO ()
main = void $ T.procStrict "/usr/bin/dmenu" ["-l","20"] (T.select ["ola","mundo"])
```
I wonder what could be causing this...

**Comment by Gabriel439** [comment]
@miguel-negrao: Try compiling the binary with the `-threaded` option

**Comment by miguel-negrao** [comment]
@Gabriel439 yep, that fixes it. Is -threaded always needed for turtle scripts ?

**Comment by Gabriel439** [comment]
@miguel-negrao: Yes

**Comment by miguel-negrao** [comment]
> @miguel-negrao: Yes

Ah, had missed that detail. Thanks for the quick answers.

**Comment by Gabriel439** [comment]
You're welcome! 🙂
