### ISSUE TITLE
Case-insensitive patterns

### ISSUE THREAD

**Issue by massysett** [Gabriel439/Haskell-Turtle-Library#31]
Is there a simple way to make patterns case insensitive?  This is the one regexp feature that doesn't seem to me to have an (obvious) replacement in Turtle.Pattern.

**Comment by Gabriel439** [comment]
The best I can do is to implement a case insensitive analog of `text`:

```
insensitive :: Text -> Pattern Text
```

Would that be good enough for your purposes?

**Comment by massysett** [comment]
Yes, that does it perfectly, thanks!

**Comment by Gabriel439** [comment]
One more question: do you need this for anything other than ASCII text?  The reason that I ask is that it's difficult to implement this efficiently for Unicode in general because I need to know the length of the string to match, but case folding can change the length of a Unicode string.

**Comment by Gabriel439** [comment]
So I added `asciiCI` for case-insensitive comparison in 3ecc3d6ee77bc330768995a8a9e450cb754f01cf.  Just let me know if you need full Unicode support or not.

**Comment by massysett** [comment]
Full Unicode support would be nice.  But please don't add it on my account :) as I hadn't realized this was such a tricky issue.  It's something I can do without.

**Comment by Gabriel439** [comment]
Alright, then I will mark this resolved since there is at least `asciiCI` for now.
