### ISSUE TITLE
Support request: getting swanky Alternative help text when using `arg`

### ISSUE THREAD

**Issue by liammcdermott** [Gabriel439/Haskell-Turtle-Library#314]
I'm building a simple task runner using Turtle, it will take a command as an argument (and there will be a limited set of commands), and different Turtle shell code will be run depending on that command.

Looking at the [Command line options](https://hackage.haskell.org/package/turtle-1.5.9/docs/Turtle-Tutorial.html#g:18) section of Turtle.Tutorial, specifically the section on `subcommand`; something about the `parser` function makes Turtle generate really useful help text, where it knows about the two alternative commands, up and down:

```
Usage: options (up | down)
```

I'm assuming this is possible because `Parser a` implements `Alternative`, and the use of `<|>` in `parser`.

This is my own (very rough, WIP) code:

```Haskell
#!/usr/bin/env stack
-- stack --resolver lts-11.15 script

{-# LANGUAGE OverloadedStrings #-}

import Turtle

data Job = SayHello | Install deriving (Show)

jobParser :: Parser Job
jobParser = arg argToJob "job" "Which job to run."
  where
    argToJob "hello"   = Just SayHello
    argToJob "install" = Just Install
    argToJob _         = Nothing

main = do
  argy <- options "Some program." jobParser
  case argy of
    SayHello -> sayHello
    Install  -> install

sayHello = echo "Hello World!"

install = do
  echo "Installing NPM dependencies…"
  stdout (inproc "npm" ["install"] empty)
  echo "Finished installing NPM dependencies."
```

Is it possible to get nice help text for my `jobParser`? Is `arg` even the right parser to be using here?

**Comment by Gabriel439** [comment]
Maybe this is what you had in mind:

```haskell
{-# LANGUAGE OverloadedStrings #-}

import Turtle

data Job = SayHello | Install deriving (Show)

jobParser :: Parser Job
jobParser =
        subcommand "hello"   "Run hello"   (pure SayHello)
    <|> subcommand "install" "Run install" (pure Install)

main = do
  argy <- options "Some program." jobParser
  case argy of
    SayHello -> sayHello
    Install  -> install

sayHello = echo "Hello World!"

install = do
  echo "Installing NPM dependencies…"
  stdout (inproc "npm" ["install"] empty)
  echo "Finished installing NPM dependencies."
```

```bash
$ ./test --help
Some program.

Usage: test (hello | install)

Available options:
  -h,--help                Show this help text

Available commands:
  hello                    Run hello
  install                  Run install
```

**Comment by liammcdermott** [comment]
Yes! Thank you. After writing this issue, I wrote almost exactly your solution but tried using `return` instead of `pure` (of course `Parser a` doesn't have a Monad instance, so I gave up; should've checked for an Applicative instance).

Thanks for the answer and for taking the time to decipher my rather confused question. I hope this helps someone else too. :smile:

**Comment by Gabriel439** [comment]
You're welcome! 🙂
