### ISSUE TITLE
Counterintuitive Termination

### ISSUE THREAD

**Issue by skatenerd** [Gabriel439/Haskell-Turtle-Library#320]
I've noticed that some counterintuitive termination in my programs.  I'm often in a `Shell` context (because I'm using managed resources, or looping or whatever), and I want to do side-effecty things which produce no standard-output.

Consider the following:
```
fail :: Shell ()                                                                                                                              
fail = do
  inproc "curl" ["-o", "/tmp/foobar", "http://marxists.org"] empty
  liftIO $ print "Hello world"
```

I was surprised to see that this never outputted the text "Hello world".  Thinking back, it makes sense - the `inproc` call doesn't generate any standard output.  We could rewrite it as follows:

```
fail :: Shell ()                                                                                                                              
fail = do
  ignored <- inproc "curl" ["-o", "/tmp/foobar", "http://marxists.org"] empty
  liftIO $ print "Hello world"
```

Now it's clear - we're basically looping over an empty list and of course we'll never execute the print statement.

This is counterintuitive, because you can do a lot of side-effecty (no-return-value) things inside of this context!  For example, if i replaced `inproc ...` with `touch /some/path`, then the code would run to completion.  Thinking about it this way, the fix becomes obvious - we want a `Shell ()` instead of a `Shell Line`, so we have to use `liftIO $ sh $ inproc...`

The reason this felt like a gotcha is that there's a pretty subtle difference between `Shell ()` and `Shell Line` if you're just doing a drop-in replacement.  You can switch (e.g. between `touch` and `inproc "curl"`), and the code will still compile (but it will stop doing what you want).

Since the Turtle tutorial is really beginner-friendly, I wonder if it's worth maybe warning people that this can happen.  Maybe it'd be cool to supply a helper function (`runForSideEffects = liftIO . sh`), which could give a hint as to how to deal with this situation.

**Comment by Gabriel439** [comment]
Note that `liftIO . sh` is the same as `sh` so `runForSideEffects = sh`

I can add a note to the tutorial, but I'll probably just recommend using `sh` directly

**Comment by Gabriel439** [comment]
I also want to note that for this specific example you probably want to use `procs` instead of `sh` and `inproc`

**Comment by skatenerd** [comment]
@Gabriel439 that's great!  thank you!

**Comment by Gabriel439** [comment]
@skatenerd: You're welcome! 🙂
