### ISSUE TITLE
Stackage `lts-12` and `Win32 < 2.6`

### ISSUE THREAD

**Issue by klapaucius** [Gabriel439/Haskell-Turtle-Library#323]
Appearently, turtle-1.5.10 made it into Stackage LTS 12, which includes Win32-2.6.1.0 in its package set. Unfortunately, that seems to be incompatible with turtle.

**Comment by Gabriel439** [comment]
@klapaucius: Would you be able to check if `turtle` builds with the latest version of the `Win32` package if you relax the upper bound?

**Comment by cebaa** [comment]
@Gabriel439 It builds fine with Win32 < 2.7, lts-12.16, removal of optparse-applicative-0.13.0.0 from extra-deps:

```
$ git diff
diff --git a/stack.yaml b/stack.yaml
index 6264e40..af05bdd 100644
--- a/stack.yaml
+++ b/stack.yaml
@@ -1,3 +1,2 @@
-resolver: lts-7.24
-extra-deps:
-- optparse-applicative-0.13.0.0
+resolver: lts-12.16
+extra-deps: []
diff --git a/turtle.cabal b/turtle.cabal
index 769c2f9..ef940dc 100644
--- a/turtle.cabal
+++ b/turtle.cabal
@@ -73,7 +73,7 @@ Library
         optional-args        >= 1.0     && < 2.0 ,
         unix-compat          >= 0.4     && < 0.6
     if os(windows)
-        Build-Depends: Win32 >= 2.2.0.1 && < 2.6
+        Build-Depends: Win32 >= 2.2.0.1 && < 2.7
     else
         Build-Depends: unix  >= 2.5.1.0 && < 2.8
     Exposed-Modules:
```

I did have a lot of issues of this sort: https://github.com/commercialhaskell/stack/issues/1811, but I have a feeling that's unrelated.

**Comment by ndmitchell** [comment]
This issue means that `turtle` is unusable for me using the latest Stackage nightly - and likely lots of more recent ones. I solved it with `allow-newer: true`, meaning it almost certainly does build. Could a new version be released?

**Comment by Gabriel439** [comment]
@ndmitchell: Yeah, I can bump the upper bounds.  I was just waiting for somebody to confirm that it built against the latest version of Windows since I didn't have CI or my development environment set up to check

**Comment by Gabriel439** [comment]
This is also now up on Hackage as `turtle-1.5.14`

**Comment by ndmitchell** [comment]
Thanks!

**Comment by Gabriel439** [comment]
You're welcome!  Thank you for your patience 🙂
