### ISSUE TITLE
Interaction with shell it's launched from

### ISSUE THREAD

**Issue by houshuang** [Gabriel439/Haskell-Turtle-Library#33]
Typically I write shell scripts to modify the environment that I will continue to work with, such as .zshrc. However, commands executed by Turtle seem to happen in a separate shell, which is internally consistent, but does not have any effects on the shell it was launched from. That might make for more reproducible scripts for complex tasks (backups etc), however it precludes many utility scripts. Is there a way for Turtle to influence the "outer" shell? 

For example

```haskell
-- helper tool for git
{-# Language OverloadedStrings #-}

import Turtle

main = (export "hi" "hello") >> cd "/" >> (view $ ls ".")
```

Here, the `ls` runs in /, but when the program is run through `runhaskell`, after exit, I'm in the same directory, and my shell does not have the "hi" environmental variable set. 

My use case right now was writing a small script that enabled me to do g houshuang/folders anywhere on my computer, and have the result git clones to my ~/src folder, and then automatically place me in the resulting folder (something I do many times a week). The first part works, but not the second.

**Comment by houshuang** [comment]
It's a trivial example, but if I got it working, I was thinking of adding more details, for example using the Github API to search for a repo, display the candidates using something like [pick](https://github.com/thoughtbot/pick) (anything similar natively Haskell?), and then proceeding, so that I would be able to do gc turtle, and quickly choose the right turtle and have it cloned etc. To my mind this possibility to go seamlessly from something trivial to something a bit more complex is one of the advantages of shell-scripting in Haskell, rather than starting out with Bash and then if it gets complex enough, deciding to go to a "real" programming language...

**Comment by Gabriel439** [comment]
I figured out how to get this to work.  The trick is to have your script invoke `bash` at the end of the script, like this:

```haskell
#!/usr/bin/env runhaskell

{-# LANGUAGE OverloadedStrings #-}

import qualified System.Process as Process
import Turtle

main = do
    cd "/"
    let cp = (Process.proc "bash" [])
            { Process.std_in  = Process.Inherit
            , Process.std_out = Process.Inherit
            , Process.std_err = Process.Inherit
            , Process.delegate_ctlc = True
            }
    (_, _, _, ph) <- Process.createProcess cp
    Process.waitForProcess ph
```

Then that newly spawned Bash shell will inherit all changes that you made prior to launching it within the script.

If you want, I can add an `interactive` command that also inherits from `std_in` so that you can more easily run interactive shells like `bash` without having to do the above `System.Process` dance.

**Comment by Gabriel439** [comment]
You can also have the current script completely replace the current process.  Just wrap the script in the `exec` command:

```bash
$ exec ./script.hs
```

**Comment by Gabriel439** [comment]
I just wanted to check if this solved your problem

**Comment by houshuang** [comment]
This is a very neat solution, thank you!

On Sat, Mar 14, 2015 at 2:10 PM, Gabriel Gonzalez <notifications@github.com>
wrote:

> I just wanted to check if this solved your problem
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Gabriel439/Haskell-Turtle-Library/issues/33#issuecomment-80649841>
> .
>



-- 
http://reganmian.net/blog -- Random Stuff that Matters

**Comment by Gabriel439** [comment]
Alright, then I'll go ahead and mark this as closed.
