### ISSUE TITLE
`mv` behaves differently whether on Linux or OSX.

### ISSUE THREAD

**Issue by YoEight** [Gabriel439/Haskell-Turtle-Library#333]
Greetings,

Given that snippet:

```haskell
let myfile = "myfile" :: FilePath

mv myfile (bar </> myfile)
```

On OSX, it will work as expected (moving `myfile` in `bar` directory), as it uses `mv` under the hood. However, on Linux it doesn't work as `myfile` doesn't exist in `bar` directory. That weirdness is caused by `mv` using `rename` on Linux.

Is it possible to make `mv` really using `mv` on Unix based systems?

Thanks for your time.

**Comment by YoEight** [comment]
After more investigation, It turned out it wasn't an error from `turtle`, but a slight difference between two environments (a missing directory in that case).

Sorry for the noise.

**Comment by Gabriel439** [comment]
No worries 🙂
