### ISSUE TITLE
`inproc` resetting environment variables

### ISSUE THREAD

**Issue by freuk** [Gabriel439/Haskell-Turtle-Library#338]
Some of the shell commands inherit environment variables (`shell`, `proc`), and some don't (`inshell`, `inproc`, and most others I have tried to use). Is this a problem, or should this be documented somewhere? I'd submit a PR, but I would like to be sure of the intended behavior first.

**Comment by Gabriel439** [comment]
@freuk: That's not intended behavior.  I had intended all of them to inherit environment variables and I didn't realize that some of them didn't

**Comment by freuk** [comment]
Okay. `system` does inherit the environment, but `stream` and `streamWithErr` don't, for instance. They actually erase the 'env' record field of `CreateProcess`, but I can't figure out why.

**Comment by Gabriel439** [comment]
I cannot reproduce the original problem, meaning that `inproc` appears to inherit environment variables.  The way I reproduced this was:

```
$ cat ./foo
env | grep FOO

$ FOO=BAR cabal repl lib:turtle
...
*Turtle> :set -XOverloadedStrings
*Turtle> inproc "./foo" [] empty & stdout
FOO=BAR
```

**Comment by freuk** [comment]
Hi Gabriel, I was indeed wrong in my assessment. These do inherit the environment properly, nothing to see here. Sorry for the noise, frankly.

**Comment by Gabriel439** [comment]
No apology necessary 🙂
