### ISSUE TITLE
Under Windows "datefile dir" gets "permission denied" if 'dir' is a directory

### ISSUE THREAD

**Issue by hgolden** [Gabriel439/Haskell-Turtle-Library#35]
Running one of your examples under Windows, I get the following error:

C:\Users\hgolden\Documents\Automation\Haskell>ghci
GHCi, version 7.8.3: http://www.haskell.org/ghc/  :? for help
[snip]
Prelude> import Turtle
Prelude Turtle> dir <- pwd
[snip]
Prelude Turtle> time <- datefile dir
*** Exception: CreateFile "C:\\Users\\hgolden\\Documents\\Automation\\Haskell": permission denied (Access is denied.)
Prelude Turtle>

It appears that this problem only occurs if the file is a directory. For example, this works:

Prelude Turtle> time <- datefile $ fromString ".\\example.hs"
Prelude Turtle> print time
2015-03-16 21:40:36.697 UTC
Prelude Turtle>

**Comment by Gabriel439** [comment]
In this case `datefile` is just a synonym for `Filesystem.getModified`:

```haskell
-- | Get the time a file was last modified
datefile :: FilePath -> IO UTCTime
datefile = Filesystem.getModified
```

... and that comes from the `system-fileio` library so the error is further upstream.  You can report the error at:

https://github.com/fpco/haskell-filesystem/issues

**Comment by hgolden** [comment]
I agree with you. It appears that the following code in `system-fileio` should use a zero parameter instead of `Win32.gENERIC_READ`:

```haskell
#ifdef CABAL_OS_WINDOWS

withHANDLE :: FilePath -> (Win32.HANDLE -> IO a) -> IO a
withHANDLE path = Exc.bracket open close where
	open = Win32.createFile
		(encodeString path)
		Win32.gENERIC_READ
		(Win32.fILE_SHARE_READ .|. Win32.fILE_SHARE_WRITE)
		Nothing
		Win32.oPEN_EXISTING
		0
		Nothing
	close = Win32.closeHandle
```
