### ISSUE TITLE
Feature request: gzip

### ISSUE THREAD

**Issue by GregorySchwartz** [Gabriel439/Haskell-Turtle-Library#353]
All streaming operations are done on files it looks like. There's no way to handle a compressed stream like `cat file.gz | gzip -d -c | head` or the like. This is possible with http://hackage.haskell.org/package/streaming-commons-0.2.1.1/docs/Data-Streaming-Zlib.html or there can be a bytestring `input` that can be decompressed and converted to `Shell Line`.

**Comment by Gabriel439** [comment]
@GregorySchwartz: There is a `Turtle.Bytes` module which operates on arbitrary stream of bytes (i.e. not line-oriented and not necessarily UTF8)

**Comment by GregorySchwartz** [comment]
Ah, I did not see that module. Is it possible to efficiently convert from `Shell ByteString` to `Shell Line`?

**Comment by Gabriel439** [comment]
@GregorySchwartz: It's a bit tricky because the `ByteString` chunks generated by the `Shell ByteString` might not be aligned to UTF-8 character boundaries.  However, if you don't care about handling that case then you can do this:

```haskell
example :: Shell ByteString -> Shell Text
example bytestrings = do
    bytestring <- bytestrings

    case Data.Text.Encoding.decodeUtf8' bytestring of
        Left  _    -> empty
        Right text -> return text
```

**Comment by GregorySchwartz** [comment]
Does `Shell ByteString -> Shell Text` stream by line or by chunk?

**Comment by Gabriel439** [comment]
@GregorySchwartz: `Shell ByteString` streams by chunk, so the correspondending `Shell Text` will not necessarily be line-aligned

**Comment by GregorySchwartz** [comment]
Is it possible to add this feature? It would complement `textToLine` by ensuring `Shell Text -> Shell Line` without mapping `Just`s or anything like that.

**Comment by Gabriel439** [comment]
@GregorySchwartz: I could generalize the type of `textToLine` to:

```haskell
textToLine :: MonadPlus m => Text -> m Line
```

... and then you can convert any `Shell Text` to a `Shell Line` by doing `>>= textToLine`.  Would that work for your use case?

**Comment by GregorySchwartz** [comment]
@Gabriel439 Would that concatenate neighboring `Text`s in the stream until a newline is reached?

**Comment by GregorySchwartz** [comment]
Unfortunately I still get the same issue with `view . toLines . TB.toUTF8 . fmap (BL.toStrict . decompress . BL.fromStrict) . TB.input`. The issue is the input into `decompress`. I assume it's due to `decompress` (non-streaming) expecting some end to the stream in what is given, but if the file is big enough that end would be in another chunk.

**Comment by Gabriel439** [comment]
So I went ahead and merged #357, but I'll also make a separate change to implement streaming `decompress`/`compress` functionality

**Comment by GregorySchwartz** [comment]
As a heads up -- if you are testing / using streaming zlib from `streaming-utils`, it would be nice to support concatenated compressed streams (see https://github.com/haskell-streaming/streaming-utils/pull/7).

**Comment by Gabriel439** [comment]
@GregorySchwartz: I have `compress`/`decompress` support up here: https://github.com/Gabriel439/Haskell-Turtle-Library/pull/358

Could you clarify what you mean by supporting concatenating compressed streams?

**Comment by GregorySchwartz** [comment]
There are a few issues (resolved I believe) raised in streaming libraries with zlib about supporting archives generated by concatenating multiple archives (i.e. https://github.com/snoyberg/conduit/issues/254 and https://github.com/k0001/pipes-zlib/issues/16 and the fix I proposed above). The solution was to exhaust the stream by repeating decompression on the leftovers.

**Comment by Gabriel439** [comment]
@GregorySchwartz: The general rule of thumb for the `turtle` API is to roughly correspond to a Unix command.  For example, `compress`/`decompress` roughly correspond to `gzip`/`gunzip`.  So if `gzip`/`gunzip` handle concatenated archives then `turtle` should do, but they if they don't then `turtle` probably shouldn't either

**Comment by GregorySchwartz** [comment]
@Gabriel439 `gzip` does supported achives generated by concatenation of multiple `gzip` archives.
