### ISSUE TITLE
mv only works within the same filesystem

### ISSUE THREAD

**Issue by lievenm** [Gabriel439/Haskell-Turtle-Library#37]
mv uses Filesystem.rename which eventually calls rename(2). This will not work when src and dst are not on the same filesystem. The unix commando mv will do the right thing in these cases.

**Comment by Gabriel439** [comment]
Could you report the issue upstream [here](https://github.com/fpco/haskell-filesystem/issues)?  I would prefer to use `Filesystem.rename` for portability.

**Comment by lievenm** [comment]
https://github.com/fpco/haskell-filesystem/issues/9

**Comment by Gabriel439** [comment]
I just saw Michael's comment.  I'd be happy to catch the exception and handle it with a `cp` followed by a `rm` since I'd like to mirror the semantics of the Unix `mv`

**Comment by Gabriel439** [comment]
I'm just checking in: do you still want to change the semantics of `mv` to fall back to a `cp`+`rm` or keep the current semantics?

**Comment by lievenm** [comment]
I'd like it to do cp+rm if a rename fails. It seems more in tune with unix mv.

**Comment by Gabriel439** [comment]
Actually, could you let me know what the exception is that is thrown when you try to move a file to another file system?
