### ISSUE TITLE
Feature Request: Command-line option for version and default values

### ISSUE THREAD

**Issue by michelk** [Gabriel439/Haskell-Turtle-Library#370]
- It is not obvious how to set elegantly default values for command-line options; currently I use `optional` for that.  
- When trying to emit a `version` with `switch`, missing option-values error first appear and no version is shown

Any suggestions how to implement this? Thanks.

**Comment by Gabriel439** [comment]
@michelk: There is a more direct way to set a default value without using `optional`.  Given a parser of type that expects a mandatory command-line option:

```haskell
exampleParser :: Parser A
```

... and a default value of type:

```haskell
exampleDefaultValue :: A
```

... you can make the default value a fallback if the parser does not match like this:

```haskell
exampleParser <|> pure exampleDefaultValue
    :: Parser A
```

For a `--version` flag to work if other command-line options are required you would need to use the underlying `optparse-applicative` package.  There is a `flag'` utility that does what you want where you can define a switch that is required unless you provide an alternative:

https://hackage.haskell.org/package/optparse-applicative-0.15.1.0/docs/Options-Applicative.html#v:flag-39-

The alternative parser you then provide is your normal option parser and it would look something like this:

```haskell
data Options = Version | NormalOptions { … }

parseVersion :: Parser Options
parseVersion = flag' Version …

parseNormalOptions :: Parser Options
parseNormalOptions = NormalOptions <$> …

parseOptions :: Parser Options
parseOptions = parseVersion <|> parseNormalOptions
```

**Comment by michelk** [comment]
@Gabriel439 thanks for the very helpful reply. 

In [this](https://tech.fpcomplete.com/haskell/library/optparse-applicative) example a parser is generated with
```haskell
    optsParser :: ParserInfo Opts
    optsParser =
        info
            (helper <*> versionOption <*> programOptions)
            (fullDesc <> progDesc "optparse example" <>
             header
                 "optparse-example - a small example program for optparse-applicative")
``` 

In `Turtle.Options.options` I was also sometimes missing the opportunity to add header and epilogue information.. 

What to you think about exporting an extended version of `Turtle.Options.options` with the opportunity to define version, header, description, program-description and epilogue?

**Comment by Gabriel439** [comment]
@michelk: Sure, I'd accept a change to add that

**Comment by michelk** [comment]
Added in #374.

Thanks.

**Comment by Gabriel439** [comment]
@michelk: You're welcome! 🙂
