### ISSUE TITLE
missing readlink

### ISSUE THREAD

**Issue by zoranbosnjak** [Gabriel439/Haskell-Turtle-Library#376]
How do I implement an equivalent of bash `readlink`or `readSymbolicLink` with existing Turtle functions? If there is no such function or composition, I would suggest to add one which properly handles FilePath arguments.

There is a https://hackage.haskell.org/package/unix-compat-0.5.2/docs/System-PosixCompat-Files.html#v:readSymbolicLink, but the `FilePath` type does not match with the Turtle version.

**Comment by Gabriel439** [comment]
@zoranbosnjak: Is [`Turtle.realpath`](https://hackage.haskell.org/package/turtle-1.5.16/docs/Turtle-Prelude.html#v:realpath) what you are looking for?

**Comment by zoranbosnjak** [comment]
@Gabriel439: It's close. The problem is the scenario where a symlink is pointing to another symlink, for example:
`link1 ---symlink-to---> some_file.txt`
`link2 ---symlink-to---> link1`
In this case, the `realpath link2` will return `some_file.txt`. Is there a way to get `link1` as a result?

**Comment by Gabriel439** [comment]
@zoranbosnjak: Currently there is not such a function in the `turtle` API.  However, if you can find the equivalent function you are looking for in another Haskell package (e.g. `directory` or `unix` or `posix-compat`) then I can re-export that utility

**Comment by zoranbosnjak** [comment]
@Gabriel439: The equivalent functions are:
* `getSymbolicLinkTarget` from `directory` package;
* `readSymbolicLink` from `unix` and `unix-compat` packages (there is no `posix-compat` on hackage as you suggested);
