### ISSUE TITLE
Add stat :: FilePath -> IO FileStatus

### ISSUE THREAD

**Issue by maoe** [Gabriel439/Haskell-Turtle-Library#38]
It would be nice if we had `stat :: FilePath -> IO FileStatus`.  It doesn't seem to be too difficult if we can use `unix` for POSIX systems and `unix-compat` for others but it incurs an extra dependency (only for non POSIX systems). What do you think?

**Comment by Gabriel439** [comment]
I didn't even know `unix-compat` existed!  Thanks for pointing that out.

I will try to add this and several other functions from that package.

**Comment by Gabriel439** [comment]
This was fixed by #171
