### ISSUE TITLE
Recommended Example: Piping data between coreutils/other programs

### ISSUE THREAD

**Issue by codygman** [Gabriel439/Haskell-Turtle-Library#4]
Like restoring a database from a compressed database dump:

```bash
zcat file | mysql -uroot mydb
```

This is streamed right? A problem I had with shelly was -|- tried to read everything in at once and the api hard enough for me to forget about it and get busy on something else.

As an aside my use case is to do a few conditional checks/get user input with Haskell and then do mostly dumb piping between applications to update databases from different servers and other tasks like it.

**Comment by Gabriel439** [comment]
You would implement that as:

```haskell
sh (inproc "zcat" ["file"] (inproc "mysql" ["-uroot", "mydb"] empty))
```

I'll make sure to add an example of this to the tutorial.

**Comment by 3noch** [comment]
Any chance you could provide a combinator for this pattern?

**Comment by Gabriel439** [comment]
There are two that could work.  One is function composition:

```haskell
(inproc "zcat" ["file"] . "mysql" ["-uroot", "mydb"]) empty
```

... or you could use `&` (reverse function application), too:

```haskell
x & f = f x

empty & inproc "mysql" ["-uroot", "mydb"] & "zcat" ["file"]
```

However, I'm less excited about the latter combinator because I try to avoid non-associative operators (mainly as a rule of thumb to make the code more readable to beginners).

**Comment by 3noch** [comment]
Of course, didn't realize it was that simple. Any built-in way to elide `empty`?

**Comment by Gabriel439** [comment]
Probably the easiest way to elide `empty` is to define a variation on `sh`:

```haskell
sh_ :: (Shell Text -> Shell Text) -> IO ()
sh_ f = sh (f empty)
```

**Comment by codygman** [comment]
-- λ> view $ inshell "mysql -uroot temptest" (inshell "cat /home/cody/work/files/fourgigs.sql" empty)
-- ERROR 1435 (HY000) at line 3138: Trigger in wrong schema
-- (225.62 secs, 483373360032 bytes)

Would it have written any of my sql migration data out of order? I'm checking to see whether or not I get the error with:

```
cat /home/cody/work/files/fourgigs.sql | mysql -uroot temptest
```

If so, it was just an error with my migration.

**Comment by codygman** [comment]
Alright, looks like that worked out awesome. Here's a benchmark as well:

-- 496 MB compressed gzip
-- 9 gigabytes uncompressed
λ> view $ inshell "mysql -uroot temptest" (inshell "zcat /home/cody/project-31Dec2014.gz" empty)
(762.24 secs, 1720645577832 bytes)

Backing up a 9 GB database in 12 minutes from ghci isn't so bad ;)

Plus my workflow for these kinds of things will be write, tweak, test, verify correct, then compile with optimizations and put in $PATH. I've thought about wrapping runhaskell with a small turtle script that looks for -O3 and if present uses ghc to compile something to a temp directory, runs it, then exits as well.

From my perspective this issue can be closed.

**Comment by Gabriel439** [comment]
Awesome!  Just out of curiosity, what fixed the problem?

Also, did you get a chance to check out the new documentation here: https://github.com/Gabriel439/Haskell-Turtle-Library/pull/6

**Comment by codygman** [comment]
> Awesome! Just out of curiosity, what fixed the problem?

Sorry for not clarifying, the error about triggers being out of order was just a messed up database backup. It was **not Turtles fault**.

> Also, did you get a chance to check out the new documentation here: #6

Yes I did check it out, and I just checked it out again now. A few things:

At first I wasn't quite sure what stdout was for until I tried to run `inshell "ls" empty` without it and checked the type of stdout. Upon seeing the type `Shell Text -> IO ()` I thought "oh, it just takes the output of a text command and sends it to stdout" which I believe is correct.

I feel like the syntax is too different for me to be able to recommend to people I know that use shell scripts frequently. This led me to try and make a combinator for the usual way of shell scripting and I think I came up with something pretty nice:

```haskell
λ> let (-|-) c1 c2 = inshell c2 . inshell c1
(0.00 secs, 0 bytes)
λ> let stdout_ f = stdout $ f empty
(0.00 secs, 0 bytes)
λ> stdout_ $ "ls ~" -|- "grep tmp"
tmp
(0.09 secs, 2220720 bytes)
λ> -- ls | grep tmp | head -n 1
(0.00 secs, 0 bytes)
λ>  stdout (inshell "head -n 1" (inshell "grep tmp" (inshell "ls ~" empty)))
tmp
(0.18 secs, 1844752 bytes)
λ> stdout_ $ "ls ~" -|- "grep tmp"
```

I know you are trying to avoid operators so it's easier to learn, but in this case there is a well known operator I think you should try to emulate (|). I believe with typeclasses the definition of (-|-) above could use inproc or inshell, but then you might (will?) have ambiguity issues.

Just kind of brainstorming, let me know what you think.

**Comment by Gabriel439** [comment]
The issue with the `-|-` operator is that it only works for a pipeline with two commands.  In the general case you would still need to wrap each command line with some function or provide an `IsString` instance for `Shell Text -> Shell Text`.

**Comment by codygman** [comment]
What about:

```haskell
λ> let (-|-) = (flip (.))
(0.00 secs, 0 bytes)
λ> stdout (inshell "ls ~" -|- inshell "head -n 5" -|- inshell "grep 4" -|- inshell "head" $ empty)
400meg.sql.tar.gz
(0.27 secs, 3090952 bytes)
λ> stdout (inproc "ls" ["~"] -|- inproc "head" ["-n 5"] -|- inproc "grep" ["4"] -|- inproc "head" [] $ empty)
ls: cannot access ~: No such file or directory
Interrupted.
λ> stdout (inproc "ls" ["/home/cody"] -|- inproc "head" ["-n 5"] -|- inproc "grep" ["4"] -|- inproc "head" [] $ empty)
400meg.sql.tar.gz
(0.28 secs, 3051904 bytes)
λ> 
```

**Comment by Gabriel439** [comment]
There is an equivalent operator for that in `Control.Category`:

```
(>>>) = flip (.)
```

... so I could re-export that if you want.  I don't mind that operator because it's associative.

Also, I could provide a `run` function defined like this:

```
run sink f = sink (f empty)
```

... that you would use like this:

```
run stdout (inshell "..." >>> inShell "..." >>> inShell "...")

-- or:
run sh (inshell "..." >>> inShell "..." >>> inShell "...")
```

That way we don't have to duplicate every sink.

**Comment by codygman** [comment]
> ... so I could re-export that if you want.

It's not me I care about so much as potential newbies (mostly people with no Haskell experience) trying to use Turtle.

> There is an equivalent operator for that in Control.Category:
> (>>>) = flip (.)

That's awesome and I usually don't like duplicating things, but for someone who hasn't used Haskell which is more clear:

run stdout (inshell "..." >>> inShell "..." >>> inShell "...")
run stdout (inshell "..." -|- inShell "..." -|- inShell "...")

That's a very small issue and makes me look/feel pedantic... yeah it doesn't take much to remember to translate | (bash) to >>> (Turtle) but it's another thing to remember and raises the barrier to entry. Perhaps we could solicit others opinions on the matter somehow as well?

It really depends on what your goals are. Though it seems small, in my mind:

Re-exporting (>>>) is choosing "bash for Haskellers"
Providing (-|-) is choosing "Newbie friendly Haskell dsl for bash scripts".

All of these thoughts/ideas have came up while trying to rewrite the following using Turtle:
https://github.com/indrora/steam_latest/blob/master/scripts/steam.sh
http://www.commandlinefu.com/commands/browse
https://raw.githubusercontent.com/andreafabrizi/Dropbox-Uploader/master/dropShell.sh

**Comment by 3noch** [comment]
IMHO, saying `>>>` is Haskell's version of Unix `|` is not hard to grok. It also has the added benefit of making Haskell, in general, seem less scary since it's already got analogous ideas going on to Unix. Defining a separate operator still requires some translation, but doesn't lead them into the deeper beauty. ;)

**Comment by Gabriel439** [comment]
There's an advantage of `(>>>)` over `(-|-)`, which is that it clearly indicates the flow of information (left-to-right).  It also can be flipped (there is `(<<<)`), where as the `(-|-)` cannot be flipped.

**Comment by codygman** [comment]
3noch, I guess you are right. Gabriel, that is also a good point. Also, purescripts composition makes more sense now ;)
