### ISSUE TITLE
Expose and document `inplaceWith` (or some variation of it)

### ISSUE THREAD

**Issue by lambdadog** [Gabriel439/Haskell-Turtle-Library#403]
It would be useful to have some function exposed like `inplaceWith` that allows you to give a function `Shell Line -> Shell Line` and use it to modify a file in-place without having to essentially reimplement `inplaceWith`.

I don't think `inplaceWith` is the right function as it is, but if you removed the assumption that the `Shell Line -> Shell Line` function given to it also takes a pattern it would become very useful and only require minor changes to the exposed `inplace{Prefix,Suffix,Entire,}` functions.

**Comment by Gabriel439** [comment]
The fix is up here: https://github.com/Gabriel439/Haskell-Turtle-Library/pull/404
