### ISSUE TITLE
cd from ghci doesn't affect path completion

### ISSUE THREAD

**Issue by L-as** [Gabriel439/Haskell-Turtle-Library#406]
I.e. typing `"./<tab>` from doesn't show paths from the directory I changed to, but from the directory ghci was started in. I'm not sure this is a problem with turtle, but perhaps there is some fix?

**Comment by Gabriel439** [comment]
That is a `ghci`-specific issue.  The `turtle` package cannot control `ghci`'s support for auto-completion

**Comment by L-as** [comment]
Thank you for the response. It is indeed just an odd ghci issue, specifically, `/proc/self/cwd` when read from outside the repl in ghci doesn't seem to be affected by changing the directory inside the repl (even though when read from inside the repl `/proc/self/cwd` will be changed)
