### ISSUE TITLE
Nicer Shell and IO integration

### ISSUE THREAD

**Issue by int-index** [Gabriel439/Haskell-Turtle-Library#45]
It may be frustrating that functions such as `testfile` can't be called in the `Shell` monad. Yes, I can apply `liftIO`, but wouldn't it make sense to cut the noise and do it in the library, so `testfile` would have the following signature?
```haskell
testfile :: MonadIO m => FilePath -> m Bool
```

It could be run seamlessly from both `IO` and `Shell`. Same for other functions.

**Comment by Gabriel439** [comment]
Yeah, I will accept this, although it means that I will need to update the tutorial to explain how to read type signatures with `MonadIO`.  I feel like people will have to learn this anyway as part of learning Haskell, so I might as well cover that, too.

Could you write up the patch to generalize all the functions to `MonadIO`?  I can take care of updating the tutorial

**Comment by Gabriel439** [comment]
I think what I may end up doing is exporting monomorphic versions of these functions at the bottom of the `Turtle.Tutorial` module and then having people import that for the beginning of the tutorial and then switch to importing just `Turtle` later on.

**Comment by int-index** [comment]
Great. I'll send a pull request then.

**Comment by int-index** [comment]
`liftIO` invocations quickly became numerous. I defined some helper functions:

```haskell
liftIO_1 = (.) liftIO
liftIO_2 = (.) liftIO_1
```

It's either that or doing something like `(fmap.fmap.fmap) liftIO` or `((.).(.).(.)) liftIO`. Or abandoning neat point-free definitions.

Would it make sense to give them other names and export them (if yes, what names)?

**Comment by Gabriel439** [comment]
Are you sure you need them?  Can you give me an example of where you think it would help?

**Comment by int-index** [comment]
```haskell
-- | Move a file or directory
mv :: MonadIO m => FilePath -> FilePath -> m ()
mv = liftIO_2 Filesystem.rename
```

**Comment by Gabriel439** [comment]
Oh, in those sort of cases I would just expand out the arguments:

```
-- | Move a file or directory
mv :: MonadIO m => FilePath -> FilePath -> m ()
mv src dst = liftIO (Filesystem.rename src dst)
```

**Comment by int-index** [comment]
Fine, in that case I'll expand them where necessary.

**Comment by int-index** [comment]
Should we generalize the functions in `Turtle.Shell` as well? I'm talking about `fold`, `sh`, `view`. If we do, many functions in `Turtle.Prelude` become generalized automatically (only type signature needs to be changed). However, it also raises the question of whether `foldIO` needs to be somehow generalized (I don't feel that it's a good idea). We could rename `foldIO` to `runShell` and then create a wrapper:
```haskell
foldIO s f = liftIO (runShell s f)
```

**Comment by Gabriel439** [comment]
Yes, they should definitely be generalized (I frequently use `fold`/`sh`/`view` within larger `Shell` blocks).  Regarding `foldIO`, I would make the generalized one named `foldIO` (for consistency), then change the accessor in the newtype to `_foldIO`.
