### ISSUE TITLE
chmod: change file mode bits

### ISSUE THREAD

**Issue by int-index** [Gabriel439/Haskell-Turtle-Library#47]
I needed to make a file executable, so I've implemented `chmod` as follows:

```haskell
chmod :: MonadIO io => FilePath -> (Permissions -> Permissions) -> io ()
chmod path f = liftIO $ do
    let path' = encodeString path
    getPermissions path' >>= setPermissions path' . f
```

It can be used like so:
```haskell
chmod filepath (setOwnerExecutable True)
```

I'm not sure it's the best design because I have only one use-case. Any ideas to improve the definition to include it in the library?

**Comment by Gabriel439** [comment]
Maybe it could be made more concise:

```haskell
data Permission = R | W | X

data Permissions
    = Add Permission
    | Sub Permission
    -- Specify permissions exactly
    | OOO
    | ROO
    | OWO
    | OOX
    | RWO
    | ROX
    | OWX
    | RWX

chmod :: MonadIO io => Permissions -> FilePath -> io ()
```

**Comment by int-index** [comment]
I think we should reuse the `Permissions` data type from `System.Directory`. Then we could create a bunch of smart constructors to create `Permissions -> Permissions` functions like so:

```haskell
roo = setOwnerReadable True . setOwnerWriteable False . setOwnerExecutable False
rwx = setOwnerReadable True . setOwnerWriteable True . setOwnerExecutable True
```

**Comment by int-index** [comment]
For adding/removing permissions, something like this is possible:
```haskell
executable = setOwnerExecutable True
nonexecutable = setOwnerExecutable False
readable = setOwnerExecutable True
nonreadable = setOwnerExecutable False
```

It allows composing permission changes with `.`

**Comment by Gabriel439** [comment]
Yeah, I really like that idea.  Could you submit a pull request for that?

**Comment by int-index** [comment]
Sure.
