### ISSUE TITLE
support ^ behavior in sed

### ISSUE THREAD

**Issue by itcowed** [Gabriel439/Haskell-Turtle-Library#49]
it is often useful to match on the beginning of a line. i have found the bellow solution best for myself

this relatively small, and simple for me to have in my project, so perhaps it does not belong in turtle, but i believe the expected behavior and what for me is desirable is to have some way to match beginnings of lines at all

```
sed' pattern s = maybe "" snd . Text.uncons <$> do
    txt    <- s
    txt':_ <- return (match pattern' (Text.cons '\n' txt))
    return txt'
    where
    pattern' = fmap Text.concat
        (many (pattern <|> fmap Text.singleton anyChar))
```
i would prefer a better sentinel value than '\n', but i think the idea is communicated

**Comment by Gabriel439** [comment]
I think a more general solution would be to provide a variation on `prefix` named `begins`:

```haskell
{-| Match the entire string if it begins with the given pattern

    This returns the entire string, not just the matched prefix

>>> match (begins  "A"             ) "ABC"
["ABC"]
>>> match (begins ("A" *> pure "1")) "ABC"
["1BC"]
-}
begins :: Pattern Text -> Pattern Text
begins pattern = pattern <> chars
```

If you use `begins` instead of `prefix`, then `sed` does the right thing:

```haskell
>>> -- s/^ABC/123/
>>> view (sed (begins ("ABC" *> pure "123")) "ABCDEF")
"123DEF"
```

There would be a similar variation on `suffix` named `ends`:

```haskell
ends :: Pattern Text -> Pattern Text
ends pattern = chars <> pattern

**Comment by dnhgff** [comment]
yes, this is quite nice. i think this raises the concern that sed is maybe not documented enough to immediately know these kinds of semantics until you look at the code. i know that it kind of does "the most obvious thing" it could do given the types, but that might not be the first thing that comes to each users mind. "Replace all occurrences of a Pattern with its Text result" read to me at first as though i was substring-replacing over the underlying file contents as a whole, not as isolated lines

**Comment by Gabriel439** [comment]
Yeah, I can also clarify that the substitution is line-based
