### ISSUE TITLE
How about a simple getArgs?

### ISSUE THREAD

**Issue by dalejordan** [Gabriel439/Haskell-Turtle-Library#50]
I wrote the following script as a Turtle learning exercise and was pleased with how it turned out (after a lot of backing and filling over discovering Turtle features and figuring out what else had to be imported).  Supporting
Optparse-Applicative is a wonderful goal, but a simple addition of getArgs :: IO [Text] would go a long way towards cleaning up simple scripts.

    #! /usr/bin/env runghc

    {-# LANGUAGE OverloadedStrings #-}

    import qualified Data.Text as T
    import System.Environment (getArgs)
    import Turtle

    -- Search for haskell files using a given symbol a la unix grep.

    main = do
      [symS] <- getArgs
      let sym = T.pack symS
      dir <- fmap (</> "hs") home
      sh (do file <- find (suffix ".hs") dir
             let fn = dirname file </> basename file
             m <- grep (has (text sym)) (input file)
             liftIO . echo $ format (fp % ": " % s) fn m
         )

**Comment by Gabriel439** [comment]
That's a great idea!  Could you write up a pull request to add this?

**Comment by dalejordan** [comment]
Thanks, int-index.  I don't have the foggiest idea how to do a pull request, not having used git before.  Your code is much nicer than what I would have written.

**Comment by Gabriel439** [comment]
That's alright! :)

For future reference, you don't even need to install `git`!  Just navigate to the file you want to modify and click the pencil icon in the top-right corner of the file to edit it.  When you save the file contents it will fork the repository and create a new branch from your edits and then prompt you to create a pull request.  I use this trick all the time to submit tiny pull requests to other Haskell repositories (like bumping cabal version bounds and things like that).  Then you can rely on travis to compile and test your branch for you.  The whole process is pretty slick once you get used to it.
