### ISSUE TITLE
Feature Request: analogue of {m,n} in regexes for Patterns

### ISSUE THREAD

**Issue by rpglover64** [Gabriel439/Haskell-Turtle-Library#52]
Although the `count` combinator provides an analogue for {n} syntax, it is sometimes useful to have "match some number of times between two numbers inclusive".

**Comment by int-index** [comment]
That's relatively easy to implement (modulo efficiency):

```haskell
mfilter (\s -> length s >= m && length s =< n) (many p)
```

Do we really need a combinator for this specific case? Any suggestions how to name it?

**Comment by Gabriel439** [comment]
The main issue with filtering `many` is that it will risk non-termination (once you hit the end of the results it will loop indefinitely looking for another solution which will never come).  You can avoid the non-termination risk using something like this:

```haskell
bounded :: Int -> Int -> Pattern a -> Pattern [a]
bounded m n p = do
    x <- Pattern (lift [m..n])
    count x p
```

**Comment by int-index** [comment]
Can you show me an example that makes the `mfilter`/`many` solution hang?

**Comment by Gabriel439** [comment]
Also, if you want to use the public API to implement this, you can do:

```haskell
bounded m n p = do
    x <- choice (map pure [m..n])
    count x p
```

The case where the `mfilter`/`many` solution might hang is if the pattern can match the empty string as one of its alternatives.  For example, we would like this to return:

```
>>> match (prefix (bounded 1 2 "")) "A"
[[""],["",""]]
```

... but using `mfilter`/`many` it will hang.

**Comment by int-index** [comment]
I think your solution would cause too much backtracking. How about this?

```haskell
maxCount :: Int -> Pattern a -> Pattern [a]
maxCount n p = do
  x <- choice (map pure [0..n])
  count x p

bounded m n p = (++) <$> count m p <*> maxCount (n - m) p
```

I believe the performance of `maxCount` can be improved by implementing it without using `replicateM`.

**Comment by int-index** [comment]
These definitions seem to handle all edge cases properly (for non-negative bounds):
```haskell
maxCount :: Int -> Pattern a -> Pattern [a]
maxCount n p
    | n <= 0 = mempty
    | n == 1 = fmap pure p
    | otherwise = (:) <$> p <*> option (maxCount (n - 1) p)

bounded :: Int -> Int -> Pattern a -> Pattern [a]
bounded m n p
    | m == n = count m p
    | m  < n = (++) <$> count m p <*> option (maxCount (n - m) p)
    | otherwise = mzero
```

They aren't particularly elegant, though. I also feel a need for a benchmark suite — until we have it, I'd go with your definition (reads way nicer).

**Comment by Gabriel439** [comment]
I'm totally okay with your optimized version, even without the benchmark suite.  It seems pretty intuitive that it would be faster and it's still pretty readable.  We can always keep the my version in the documentation as an explanation for how it should behave.

**Comment by int-index** [comment]
I've done some measurements. My version is more than 30 times faster when evaluating `match (bounded 500 700 "abcde") (Text.replicate 650 "abcde")`. It's more than 70 times faster when evaluating `match (bounded 5000 7000 "abcde") (Text.replicate 6500 "abcde")`. I suppose it's an asymptotic improvement, so let's settle on it.
