### ISSUE TITLE
Provide /usr/bin/turtle

### ISSUE THREAD

**Issue by int-index** [Gabriel439/Haskell-Turtle-Library#55]
A simple wrapper around `runhaskell` that enables `OverloadedStrings` and maybe other extensions.

**Comment by int-index** [comment]
Given that `runhaskell` is a sh-script, maybe we should reimplement it using Turtle?

**Comment by Gabriel439** [comment]
It's important not to replace `runhaskell`, because relocatable GHC installations (like [GHC for Mac OS X](http://ghcformacosx.github.io/)) do fancy tricks with `runhaskell` to make the installation relocatable.  I think it's better to wrap `runhaskell`.

**Comment by int-index** [comment]
Fine, let's wrap `runhaskell`. Do you have any other things in mind that this wrapper might do? Right now I'm working on a simple interface to `optparse-applicative` (as requested in https://github.com/Gabriel439/Haskell-Turtle-Library/issues/13). I'd like it to be used like so:

```haskell
import Turtle.Options

data Options = Options
  { foo :: Integer
  , bar :: Text
  , baz :: Bool
  , quux :: Bool
  }

pOptions :: Parser Options
pOptions = ...

main = do
  Options{..} <- options pOptions
  ...
```

That means we would need to enable `RecordWildCards` too.

**Comment by 3noch** [comment]
Don't forget Windows! That means shying away from bash-specific features.

**Comment by int-index** [comment]
I'm not sure what bash-specific features you're talking about. The wrapper is to be written in Haskell.

**Comment by 3noch** [comment]
I suppose that would qualify then.

**Comment by Gabriel439** [comment]
It's turtles all the way down

:turtle: 
:turtle: 
:turtle: 
...

**Comment by int-index** [comment]
Here's an implementation I propose:

```haskell
module Main where

import System.Environment (getArgs)
import System.Process (callProcess)

main :: IO ()
main = do
    args <- getArgs
    callProcess "runghc" ("-XOverloadedStrings":"-XRecordWildCards":args)
```

Can someone verify that it works on Windows/OS X?

**Comment by 3noch** [comment]
@Gabriel439 :thought_balloon: :boom:

**Comment by 3noch** [comment]
@int-index It would be super helpful to have a `--help` that tells us what extensions are enabled. That seems pretty important when developing with this tool.

**Comment by int-index** [comment]
I'd rather document it elsewhere.

**Comment by 3noch** [comment]
Then perhaps at least a `--version` tag so that if/when these change, we can know which settings we have.

**Comment by int-index** [comment]
That sounds reasonable.

**Comment by int-index** [comment]
I don't think it's a good idea anymore. Feel free to close this.

**Comment by Gabriel439** [comment]
Alright, then I'll close this for now.
