### ISSUE TITLE
Weird link in slides

### ISSUE THREAD

**Issue by mausch** [Gabriel439/Haskell-Turtle-Library#58]
At the end of the section https://github.com/Gabriel439/Haskell-Turtle-Library/blob/master/slides/slides.md#before-class it says "Finally: go/checkin" with a link that goes to https://github.com/Gabriel439/Haskell-Turtle-Library/blob/master/slides/go.twitter.biz/checking (obviously invalid), but http://go.twitter.biz/checking (or even http://go.twitter.biz) doesn't exist either.

**Comment by Gabriel439** [comment]
That's because these are slides for an internal Twitter course and those links are internal links.  I'll just delete them.

**Comment by Gabriel439** [comment]
Fixed by 2a5e4ea6d0a60a5864accd273dfaa610af17b1e9
