### ISSUE TITLE
Grep --invert-match

### ISSUE THREAD

**Issue by xged** [Gabriel439/Haskell-Turtle-Library#60]
Newb question:
Keep all lines that **does not** match the given Pattern?
Eg **`not`**`grep (prefix "import") $ input "test.hs"`

**Comment by Gabriel439** [comment]
There's a very general way to do this, which is to provide an `invert` combinator that works for any `MonadPlus`:

```haskell
invert :: MonadPlus m => m a -> m ()
invert m = do
    m' <- (m >> return mzero) `mplus` return (return ())
    m'
```

In other words, if `m` succeeds then `m'` will be `mzero` and the computation will fail and if `m` fails, then `m'` will be `return ()` and the computation will return `()`.

With this combinator, you'd be able to write:

```haskell
grep (invert (prefix "import")) (input "test.hs")
```

Does that sound like an okay solution to you?

**Comment by xged** [comment]
That would sound as an excellent solution if `invert` would be defined in *Turtle*

**Comment by Gabriel439** [comment]
Alright, then I'll add this to `turtle` soon

**Comment by xged** [comment]
Actually a better solution would be to have `not :: Pattern a -> Pattern a`
instead of `invert :: Pattern a -> Pattern ()`

**Comment by int-index** [comment]
@xged Turtle tries not to conflict with Prelude.

**Comment by xged** [comment]
Then `not'`, `no` or `invert`(!).
Though I prefer qualified imports.
