### ISSUE TITLE
Exceptions are swallowed by stream ?

### ISSUE THREAD

**Issue by PierreR** [Gabriel439/Haskell-Turtle-Library#63]
While doing the examples from the `slides.md` I have been very surprised by this behavior (within ghci):

```
> stdout $ input "dontexist"
*** Exception: buld.sh: openFile: does not exist (No such file or directory)

-- Within a stream the exception disappears ...
> stdout $ input "dontexist" & inshell "nl"
```
Same with `shell`
```
-- in an unix shell
> nl < dontexist
zsh: No such file or directory : dontexist

-- in ghci
> input "dontexist" & shell "nl"
ExitSuccess
```

PS I have initially posted this in #34 but reading the discussion again it does not seem to be related.

I have checked it using a script file (runhaskell): same result.

**Comment by Gabriel439** [comment]
It looks like this is my mistake: I misunderstood how `withAsync` was supposed to behave.  I thought that `withAsync io f` would preserve exceptions thrown by the `io` action, but apparently not.  The solution seems to be to use `Control.Concurrent.Async.link` to ensure that exceptions are propagated to the current thread.  I'll fix this.

**Comment by PierreR** [comment]
Out of curiosity, what about `stream` (used by inshell & inproc) that does not use `withAsync` ?

**Comment by Gabriel439** [comment]
`stream` does use `withAsync` indirectly (via `fork`) so it should have the exact same problem.
