### ISSUE TITLE
"Text" is used for stdin and stdout

### ISSUE THREAD

**Issue by accelas** [Gabriel439/Haskell-Turtle-Library#68]
While it doesn't matter for a lot of use case turtle is designed for, it does mean I can't pipe binary as stdin/stdout. Even for textual content,  I think "Text" can only accept UTF-8/16/32 encoding. This severely restrict my ability to use "iconv" inside a shell pipe. I discovered this while trying to use "iconv -f GB2312 -t UTF-8" inside turtle.

**Comment by Gabriel439** [comment]
Sorry for the long delay on this question.

So it's important to clarify a couple of things first:

* Encoding is not an intrinsic property of `Text` or `ByteString`, but rather a description of how to convert between them.  In other words, it's correct to say that the encoding/decoding process is UTF8/UTF-16/UTF-32, but it's not correct to say that a `Text` value or `ByteString` value is UTF8/UTF-16/UTF-32.
* By default, all operations in `Data.Text.IO` decode bytes using UTF-8.  `turtle` uses these operations so `turtle` also decodes bytes using UTF-8 by default.

So it sounds like what you need is:

* Variations on `inhandle`/`outhandle` that work with raw streams of bytes:

```haskell
inhandle :: Handle -> Shell ByteString

outhandle :: Handle -> Shell ByteString -> IO ()
```

* Various codecs that convert between `Shell Text` and `Shell ByteString`:

```haskell
utf8Decode :: Shell ByteString -> Shell Text
utf8Encode :: Shell Text -> Shell ByteString
utf16Decode :: Shell ByteString -> Shell Text
utf16Encode :: Shell Text -> Shell ByteString
...
```

... and so on.  Does that sound like that would work for you?

**Comment by Gabriel439** [comment]
I will mark this closed for now, then.  If somebody wants to revive this ticket just let me know.

**Comment by jraygauthier** [comment]
The following fails miserably and there seem to be no readily made alternative to stream
binary data.

~~~
ghci>output "bob.png" $ inproc "plantuml" ["-pipe", "-tpng"] $ inproc "cat" ["test.txt"] empty
*** Exception: fd:14: hGetLine: invalid argument (invalid byte sequence)
~~~

proc / inproc / output and all binary (most likely bytestring) variants would definitely be useful.

**Comment by joelmccracken** [comment]
I actually just ran into this, with a situation very similar to what @jraygauthier lists.

**Comment by Gabriel439** [comment]
So for the scope of this issue I will stick to just reading and writing chunks of bytes if that's alright.  The main reason is that I want to avoid duplicating the entire library's utilities to provide `ByteString` versions of everything

**Comment by joelmccracken** [comment]
sounds good to me.

On Mon, Aug 22, 2016 at 11:41 PM, Gabriel Gonzalez <notifications@github.com

**Comment by Gabriel439** [comment]
Alright, so I began this in 4c19fd00962e3c53c1d6bda7b3faad10d5f119f0.  The summary is that I'm creating a new `Turtle.Bytes` module (not re-exported from `Turtle`).  The intention is that this module is imported qualified (i.e. `import qualified Turtle.Bytes as Bytes`).

This module provides `ByteString` replacements for some utilities in `Turtle.Prelude`.  These `ByteString` analogs are newline-oblivious; the input utilities ignore newlines and read in roughly 32 kB chunk sizes and the output utilities similarly don't insert newlines.

The only thing that's missing so far are the `ByteString` analogs of all the subprocess runners which I will add a followup commit for soon.

**Comment by joelmccracken** [comment]
makes sense. If I am employing tar or something that outputs a stream of bytes instead of text, i'd rather its type specify it as bytes, not text. similarly, if a utility accepts something as binary, this makes sense to also be bytes.

Cool!

**Comment by jraygauthier** [comment]
Nice. Thank you.

**Comment by joelmccracken** [comment]
Thanks!!!

**Comment by Gabriel439** [comment]
You're welcome!

**Comment by l-d-s** [comment]
Thanks -- I'm using Turtle in a bioinformatics application (integrating it with Shake) and ran into this error.
