### ISSUE TITLE
Which Prelude to use?

### ISSUE THREAD

**Issue by xged** [Gabriel439/Haskell-Turtle-Library#69]
Which is the most sane Prelude (default Haskell module) to use from a *Turtle*'s perspective?

`put on hold as primarily opinion-based :)`

**Comment by Gabriel439** [comment]
`turtle` is designed to work with the default Haskell Prelude as much as possible so all the names were chosen not to conflict with the Haskell Prelude.

However, if you want to try out alternative Preludes you could try out `basic-prelude`:

https://hackage.haskell.org/package/basic-prelude

I'm not really an expert on alternative Preludes (I use the default one), so I'll let others chime in who know more about this.

**Comment by xged** [comment]
Default String Grinds my Gears :(

**Comment by Gabriel439** [comment]
I'll mark this closed since I believe the question was answered and it looks like you decided on `basic-prelude`.
