### ISSUE TITLE
Problems with overloading to *FilePath*

### ISSUE THREAD

**Issue by xged** [Gabriel439/Haskell-Turtle-Library#70]
import           BasicPrelude hiding (find,(</>))
    import qualified Control.Foldl as Fold
    import qualified Prelude
    import           Turtle

    copyExtfiles :: Text -> IO [()]
    copyExtfiles filext = do
      files <- fold (find (star anyChar *> "." *> text filext) ".") Fold.list
      let dir = fromText $ "data__" ++ filext
      mkdir dir
      zipWithM cp files $ map ((dir </>) . fromText . show) [1..]
    
    tmp :: IO ()
    tmp = mkdir "data"

I have to use `fromText` in `copyExtfiles`, but not in `tmp`

**Comment by Gabriel439** [comment]
This has nothing to do with `do` notation.

Also, the title is misleading.  This type-checks, but gives an unexpected result.  I'm guessing you tried this and you got a slash inserted in between the `"data_"` and `fileext`.

I consider this a bug in the `FilePath` implementation from `system-filepath`.  The reason I consider it a bug is that I believe that any type that implements `IsString` and `Monoid` should satisfy these two laws:

```haskell
fromString (str1 <> str2) = fromString str1 <> fromString str2

fromString mempty = mempty
```

However, as you discovered the `FilePath` type does not obey the first law, leading to the confusing behavior of inserting a slash.

Fixing the `FilePath` type is outside the scope of the `turtle` library.  I may eventually introduce a new file path type later on (See #54), but for now we have to live with the bugs of the current `FilePath` type.

**Comment by Gabriel439** [comment]
Whoops, I realized that I made a mistake.  There was a type error, too.  The other problem is that `fileExt` is a `Text`, so at some point you have to convert it to a `FilePath` explicitly, either before concatenating it with a string literal or after.

**Comment by xged** [comment]
No such thing as Text Overloading?

**Comment by Gabriel439** [comment]
Haskell overloads literal values (like numeric literals and string literals) by representing them using a type class:

```haskell
1 :: Num a => a

"foo" :: IsString a => a  -- With OverloadedStrings enabled
```

Under the hood it's as if you had written:

```haskell
fromInteger (1 :: Integer) :: Num a => a

fromString ("foo" :: String) :: IsString a => a
```

So if you want to overload a string without using a string literal then you need to wrap the string with `fromString`.  In the case of `Text`, you would have to additionally `unpack` the value, too:

```haskell
fromString . unpack :: IsString a => Text -> a
```

**Comment by xged** [comment]
I found `fromShow :: (Show a, IsString b) => a -> b -- Defined in ‘BasicPrelude’`

    copyExtfiles :: Text -> IO [()]
    copyExtfiles fileExt = do
      files <- fold (find (star anyChar *> "." *> text fileExt) ".") Fold.list
      let dir = fromShow $ "data__" ++ fileExt
      mkdir dir
      zipWithM cp files $ map ((dir </>) . fromShow) [1..]

**Comment by Gabriel439** [comment]
That might not do the correct thing, though.  The `Show` instance of `Text` will produce quotes around the string, so you may get a file name with quotation marks.

**Comment by xged** [comment]
Yep, just figured that out. No Holy Grail for now.
