### ISSUE TITLE
File size

### ISSUE THREAD

**Issue by xged** [Gabriel439/Haskell-Turtle-Library#71]
1. Feature request: get the file size in characters like `wc -m` (`print the character counts`)
2. Document `du`, that it returns *KB* (?)

**Comment by Gabriel439** [comment]
Can you submit a pull request to document `du`?

**Comment by xged** [comment]
I will try :)

**Comment by xged** [comment]
size :: FilePath -> IO Int
    size s = sum <$> map Text.length <$> fold (input s) Fold.list

**Comment by Gabriel439** [comment]
Whoops, I forgot to mention the solution I was going to recommend for request 1:

````haskell
import qualified Control.Foldl as Fold
import qualified Control.Foldl.Text as FoldText


numLines :: Num n => Fold Text n
numLines = Fold.genericLength

numChars :: Num n => Fold Text n
numChars = (+) <$> FoldText.length <*> numLines
````

`FoldText.length` counts how many characters are in the stream, but the stream does not include newlines, so `Fold.genericLength`) counts how many lines there are and adds one character per line.

Then you can use the above fold to count the number of characters in any stream:

```haskell
fold (input s) numChars -- Count the number of characters in the stream
fold (input s) numLines -- Count the number of lines in the stream
```

We'd also need a `numWords` fold, too.

**Comment by xged** [comment]
Great. How about `countChars` `countWords` `countLines`?

Also an alternative way to your #79 proposal would be to have `countBytes` (as *Unix wc* has) instead of `du` and maybe function which deals with *kilo* (1024), *mega*, etc. Unless you want to expand `du` functionality in the future.

**Comment by Gabriel439** [comment]
Yeah, I like `countChars`,`countWords`,`countLines`.

Could you explain more what you mean about `du`?

**Comment by xged** [comment]
Basically to rename an existing `du` to `countBytes` to fit the pattern (and *Unix wc* functionality). And not to deal with KB,MB,GB.. the way you suggested or deal with it separately.

Alternative naming pattern (which I like less) could be `wcChars`, `wcWords`, `wcLines`, (`wcBytes`) for the resemblance of Unix nomenclature.

**Comment by Gabriel439** [comment]
I would like to keep the `du` name and keep the character/word/line counting functionality separate

**Comment by xged** [comment]
Understandable
