### ISSUE TITLE
Compiled script hangs, interpreted script runs

### ISSUE THREAD

**Issue by stschiff** [Gabriel439/Haskell-Turtle-Library#72]
I have a simple turtle script, called `turtle_test.hs`  which looks like this:

    #!/usr/bin/env runhaskell
    {-# LANGUAGE OverloadedStrings #-}

    import Turtle

    main :: IO ()
    main = do
        stdout . inproc "cat" [] . select $ ["hello", "world"]

When I run this script using the interpreter, i.e. `./turtle_test.hs`, it works fine, outputting

    hello
    world

However, when I compile it using `ghc turtle_test` and then run using `./turtle_test`, it hangs.
I am using Turtle 1.1.0.

**Comment by PierreR** [comment]
As a first check, did you compile it with `-threaded` ?

**Comment by stschiff** [comment]
Oh no... OK I see. When compiling with -threaded, it works fine. Sorry. By the way, how come it works, even though I don't pass `+RTS -N` to the executable?

**Comment by Gabriel439** [comment]
No apology necessary.  This seems to be a bug in how `process` interacts with the `async` library (in the implementation of `inproc`).  I'm thinking of hand-rolling what `async` does to work around this issue.

**Comment by 3noch** [comment]
@Gabriel439 No chances `process` could get fixed itself?

**Comment by Gabriel439** [comment]
I'm not sure whether the problem is with `process` or `async`.  My initial guess is that the issue is with `async` because I haven't encountered these problems in other contexts where I've used `process`

**Comment by 3noch** [comment]
Ok, I only ask because I see a common pattern of folk patching common libs and leaving them broke for the rest of us. :wink:

**Comment by Gabriel439** [comment]
If I figure out what the problem is I will contribute the solution upstream

**Comment by Gabriel439** [comment]
I stumbled across this lpaste today which might have a solution to this problem:

http://lpaste.net/136737

I haven't yet checked if this is related to the problem or not, but I'm recording it here to remind myself to investigate this
