### ISSUE TITLE
Add `cache`

### ISSUE THREAD

**Issue by Gabriel439** [Gabriel439/Haskell-Turtle-Library#74]
This lets the user specify that an expensive `Shell` computation should be cached so that repeated runs of the script go more quickly.  The type would be:

```haskell
cache :: (Read a, Show a) => FilePath -> Shell a -> Shell a
```

If the given file is present the values are read from the file using the `Read` instance.  If the file is not present the `Shell` is run and the values are saved to the file using the `Show` instance.

**Comment by 3noch** [comment]
This could be really helpful. It starts to feel like `shake` a bit. I wonder if "cache" is best term? That seems heavier duty than caching. I wouldn't expect a cache to be persisted across invocations normally. But that might just be me.

**Comment by Gabriel439** [comment]
Yeah, it doesn't have to be called `cache`.  Maybe `save`?

**Comment by 3noch** [comment]
I like `save`. `persist` could work too. `cache` is growing on me a bit, since it will always have a filename directly after it (e.g. `cache "download.cache"`).

**Comment by 3noch** [comment]
Perhaps even `cached`...

**Comment by PierreR** [comment]
Or `stash` ?
