### ISSUE TITLE
Is there a way to compensate for shell error?

### ISSUE THREAD

**Issue by AlexeyRaga** [Gabriel439/Haskell-Turtle-Library#80]
I see that in case if a shell command errors out the `Shell` monad produces `empty`. This aborts the shell actions sequence in the `do` block.

When using `inshell`, what would be the way of getting the result of the executed command as usual, but compensate with another action in case of an error?

**Comment by Gabriel439** [comment]
Unfortunately, this is not possible using the `Shell` type because there is no way to retrieve the exit code from a `Shell` stream.  Your best best is to either use the `procStrict` or `shellStrict` utilities or to use a more powerful library like `pipes` where `Producer` streams can end with a return value.

**Comment by AlexeyRaga** [comment]
Wow, that's a *very* big limitation :(
In some cases, where only the output matters, it is possible to use something like `T.empty <|> pure ""`.

But other may require to know whether the command succeeded or not...
Unfortunately even `stdout $ inshell "echo $?" (inshell "curl ppp" T.empty)` gives me `0` which doesn't seem to be correct.

**Comment by Gabriel439** [comment]
Oh wow, it didn't occur to me to use `echo $?`.  Actually, that would work, except you would run it like this:

```haskell
stdout (inshell "curl ppp" empty)
exitCode <- shell "echo $?" empty
```

**Comment by PierreR** [comment]
>stdout (inshell "curl ppp" empty)
exitCode <- shell "echo $?" empty

It looks like it still prints 0 ExitSuccess ?

**Comment by Gabriel439** [comment]
Yeah, you're right.  It doesn't preserve exit codes across shell invocations.  It looks like the only way to do this for now is `procStrict` or `shellStrict`

**Comment by PierreR** [comment]
Why isn't `shellStrict` the default ? Maybe I have missed something from the tutorial or doc ?

**Comment by Gabriel439** [comment]
You would be using `shellStrict "curl ppp" empty` if you wanted to retrieve the exit code.

The reason it's not the default is that it has potentially unbounded memory use.

**Comment by PierreR** [comment]
Well I believe I have tried everything ;-)
```
> do {shellStrict "curl ppp" empty >> shellStrict "echo $?" empty >>= liftIO . print}
0
ExitSuccess
```

**Comment by Gabriel439** [comment]
I mean skip the "echo $?".  Just get the exit code directly from the first shellStrict command

**Comment by PierreR** [comment]
Oh sure that would work ... with `shell` or `shellStrict`. I have been confused by the fact you mention it would work with `shellStrict` exclusively ;-)
So there is no way to get the error code with `$?` then.

**Comment by Gabriel439** [comment]
The reason I recommended `shellStrict` is he also wanted to collect the input

I'm guessing that the reason that `echo $?` always returns `0` is because each invocation of `shell` spawns a fresh shell.
