### ISSUE TITLE
/bin/sh: createProcess: fork: resource exhausted

### ISSUE THREAD

**Issue by AlexeyRaga** [Gabriel439/Haskell-Turtle-Library#82]
Maybe it is a bit extreme, but after executing ~478 shell commands using `turtle` I get the following error:

    /bin/sh: createProcess: fork: resource exhausted (Resource temporarily unavailable)

and the script terminates.

All I did is just a recursive method that does some `inshell`, checks the result, sleeps for 1 second and calls itself. 
Interestingly, having no sleep at all gives me about the same number of iterations, so it seems that it has nothing to do with concurrency or time needed for releasing resources.

**Comment by Gabriel439** [comment]
Do you have a simplified version of the recursive method that caused the resource exhaustion?

**Comment by Gabriel439** [comment]
The reason I'm asking for the example is that `Shell` is designed to release resources promptly.  If you do something like this:

```haskell
example :: Shell ()
example = do
    _ <- [1..10]
    _ <- using someResource
    ...
```

... then `Shell` will release the resource after each iteration of the loop.  The only way you can get a resource leak is if you recursively acquire a resource within the acquisition of another resource, like this:

```haskell
example2 = do
    _ <- using someResource
    example2
```

That second example will eventually exhaust the resource.

More generally, the intuition for how resource acquisition and release works is that:

```haskell
-- Step 1: Acquire Resource #1
-- Step 2: Release Resource #1
-- Step 3: Acquire Resource #2
-- Step 4: Release Resource #2
using resource1 <|> using resource2

-- Step 1: Acquire Resource 1
-- Step 2: Acquire Resource 2
-- Step 3: Release Resource 2
-- Step 4: Release Resource 1
using resource1 >> using resource2
```

Does that help answer your question?

**Comment by Trundle** [comment]
I think this is caused because `stream` never reads the exit code of the processes it creates, which leads to zombie processes hanging around.

The following program will create 5 zombie processes:

```haskell
{-# LANGUAGE OverloadedStrings #-}

import Turtle

main = do
  sh (inproc "ls" [] empty)
  sh (inproc "ls" [] empty)
  sh (inproc "ls" [] empty)
  sh (inproc "ls" [] empty)
  sh (inproc "ls" [] empty)
  getLine
```

Adding a `waitForProcess` call to `stream` should fix the issue:

```diff
diff --git a/src/Turtle/Prelude.hs b/src/Turtle/Prelude.hs
index 08f03de..5b3b952 100644
--- a/src/Turtle/Prelude.hs
+++ b/src/Turtle/Prelude.hs
@@ -405,12 +405,12 @@ stream p s = do
             , Process.std_out = Process.CreatePipe
             , Process.std_err = Process.Inherit
             }
-    (Just hIn, Just hOut, Nothing, _) <- liftIO (Process.createProcess p')
+    (Just hIn, Just hOut, Nothing, ph) <- liftIO (Process.createProcess p')
     let feedIn = sh (do
             txt <- s
             liftIO (Text.hPutStrLn hIn txt) )
     a <- using (fork feedIn)
-    inhandle hOut <|> (liftIO (wait a) *> empty)
+    inhandle hOut <|> (liftIO (Process.waitForProcess ph *> wait a) *> empty)
 
 -- | Print to @stdout@
 echo :: MonadIO io => Text -> io ()
```

Although this changes the behaviour of `stream` a bit

**Comment by Gabriel439** [comment]
Yeah, I think you identified the correct solution.  As I mentioned in another issue, this looks awfully similar to the problem and solution in this lpaste:

http://lpaste.net/136737

This might resolve a lot of issues that the library has been having with running external commands.
