### ISSUE TITLE
Add `cut` and `paste`

### ISSUE THREAD

**Issue by rpglover64** [Gabriel439/Haskell-Turtle-Library#95]
I don't think they're easily (or, in `cut`'s case obviously) implementable within the current library, and they're useful.

At the very least, they deserve to be examples.

I think `cut` could be implemented, inefficiently and with room for error in fiddly details, using the `sepBy` pattern to split the columns and some list munging to select the fields (carefully avoiding error in the case of too-short lists).

`paste` is basically `zip`, but `zip` isn't provided as a primitive on shells, nor in `foldl`.

I also found myself wanting something like `nl` (or python's `enumerate`).

**Comment by int-index** [comment]
```haskell
nl :: Num n => Pattern [a] -> Pattern [(Int, n)]
nl = fmap (zip [0..])
```
