### ISSUE TITLE
Cause `sed` to error instead of looping when given a pattern which matches the empty string.

### ISSUE THREAD

**Issue by rpglover64** [Gabriel439/Haskell-Turtle-Library#96]
I feel like a call to `error` or `die` is a more appropriate solution than a warning in the documentation. 

(Apparently, unix `sed` inserts the substitution at every possible point in the string, which is not a behavior I think we'd want to imitate)

**Comment by Gabriel439** [comment]
That sounds like a good idea.  Do you think you could submit a pull request to add this?

**Comment by rpglover64** [comment]
I'll try to get one in by tomorrow morning. If I don't, I probably got sidetracked doing other work.
