### ISSUE TITLE
Make it easy to extract a file path as Text from a FilePath

### ISSUE THREAD

**Issue by rpglover64** [Gabriel439/Haskell-Turtle-Library#97]
AFAICT, there's no easy (and discoverable) way to get a function `:: FilePath -> Text`; the closest thing I can find is `fromRight . toText`, which involves using the (now deprecated) package [`system-filepath`](https://hackage.haskell.org/package/system-filepath) directly as well as an unsafe function (which, apparently, is not provided by `base`).

**Comment by PierreR** [comment]
You can use `fp :: Format r (FilePath -> r)`
```
import Filesystem.Path.CurrentOS((</>))
format fp ("usr" </> "lib")
```
That said there is an issue about replacing `system-filepath` (#54)

**Comment by Gabriel439** [comment]
I think I should probably expand the tutorial to mention the `format fp` trick and maybe also include an example of its use in `Turtle.Prelude` to ensure that people don't miss this.  I agree that it's a pretty common idiom that is hard to discover.

**Comment by PierreR** [comment]
As a note, give p of type `FilePath` and t of type `Text`, the only way to safely handle the concatenation of these values is:
```
format fp (p </> fromText t)
```
I believe it is too much of a trouble for bash scripting but that's another story.
