### ISSUE TITLE
Clarify intended use of `using`

### ISSUE THREAD

**Issue by rpglover64** [Gabriel439/Haskell-Turtle-Library#98]
```
*Main> sh $ using (mktemp "." "foo") >>= \(a,h) -> outhandle h (return "asdf") >> stdout (input a)
*** Exception: ./foo1804289383846930886: openFile: resource busy (file is locked)
```
I expect this code to print "asdf"; I assume that my expectation is wrong and that this is not a bug, but I don't see anything in the documentation to explain how I would accomplish the intended behavior.

**Comment by Gabriel439** [comment]
Actually the problem isn't with `using`.  The problem is that you have to close the `Handle` returned by `mktemp` before consuming it using `input`.

I can add this to the documentation for `mktemp` and also re-export `hClose`, though

**Comment by rpglover64** [comment]
I guess that makes sense... is it really such an uncommon use case to write to a temp file and read from it at the same time? Especially since my understanding of `using` and `Managed` is that it they'll guarantee that the handle is closed when you exit the scope.

**Comment by Gabriel439** [comment]
Actually, even if it did guarantee that the handle is closed when you exit the scope, you'd still have an issue because you haven't even exited the scope yet.  The end of the scope is when the surrounding `sh` (or `with` or `runManaged`) completes.

However, I agree that the current API is a bit difficult to use.  I'm trying to think of an easier interface to work with.

**Comment by Gabriel439** [comment]
So it just occurred to me that a simpler API might be to just not return the `Handle` at all.  In other words, just change the type to:

```haskell
mktemp :: FilePath -> Text -> Managed FilePath
```

After all, it's not that hard for the user to just write to it using `output` anyway.  The drop in efficiency from closing and reopening the `Handle` is probably negligible.

How does that solution sound?

**Comment by rpglover64** [comment]
Sounds good. I'd also clarify `using` (I didn't realize how far the scope went) and maybe mention `with`. I might have benefited from seeing how to replicate Python's `with` in the tutorial (IIUC, this would involve `liftIO . runManaged`, but I'm not sure how to run `Shell` code within the `Managed` block).

**Comment by Gabriel439** [comment]
As a side note, `turtle` now re-exports `with` from the `managed` package, which is exactly analogous to Python's `with`

**Comment by rpglover64** [comment]
> As a side note, `turtle` now re-exports `with` from the managed package, which is exactly analogous to Python's `with`

Not exactly analogous. It does not work seamlessly with `Shell` values in that its second parameter is an `IO` action, not a `Shell` action.

```python
import tempfile
with tempfile.TemporaryFile() as f:
  f.write("asdf")
  f.seek(0) # Ideally I would have a read and a write descriptor, but there's no easy way to do so AFAICT
  print(f.read())
```

```haskell
{-# LANGUAGE OverloadedStrings #-}
import Turtle
import Control.Monad.Managed (with)
main = sh $ do
  -- I shouldn't always need to care about the arguments to mktemp.
  -- I'd probably provide a function that takes no parameters and one which uses some default arguments trick to let the user customize, but I understand that that is in contrast to `turtle`s goal of `turtle` is simplicity.
  liftIO {- [1] -} $ with (mktemp "/tmp" "foo") $ \fname -> sh {- [2] -} $ do
    output fname "asdf"
    stdout $ input fname -- No need to seek, but opens you up to a TOCTOU attack [3]
```

1. Since `with` returns an `IO` action, I need to `liftIO` it to work in a `Shell` context
2. But if I want to use a `Shell` within the `with`, I need to convert it to an `IO`; `sh` is the most straightforward way to do so, but if I want to return something, I need to resort to `fold`, which is necessarily somewhat involved.  
  This isn't a exactly downside w.r.t. Python; Python doesn't let you get a value from a `with` block, but it does let you set variables and use the result later (which we can do via `IORef`s, but those are, again, more involved than the Python equivalent).
3. I'd go with the simplified interface, but I'd make a comment that it's bad systems programming practice because it enables [TOCTOU](https://en.wikipedia.org/wiki/Time_of_check_to_time_of_use) vulnerabilities ([example](http://www.informit.com/articles/article.aspx?p=23947&seqNum=3)).

**Comment by Gabriel439** [comment]
The whole reason I didn't originally export `with` is precisely because it let you introduce a TOCTOU bug.  If you don't use, then the idiomatic way to use it to just bind the result in the `Shell` monad through `using`.

Actually, it's still possible to have a TOCTOU bug if you use `fold`, but it requires much more effort.

The direct answer your question is to just do this:

```haskell
example = do
    fname <- using (mktemp "/tmp" "foo")
    output fname "asdf"
    stdout (input fname)
```

That gives you full access to the `Shell` monad within the scope introduced by the `mktemp` statement.

**Comment by rpglover64** [comment]
Right. `Managed` embeds into `Shell`; I should have realized.

The cleaned up code you presented still has the same TOCTOU bug, though, if the attacker swaps out the file between `mktemp` and `output` or between `output` and `input`; the nominally "proper" way to do this would be to return a file handle (like `mktemp` used to), possibly without the file name (this is probably why [`System.IO.openTempFile`](https://hackage.haskell.org/package/base-4.8.1.0/docs/System-IO.html#v:openTempFile) has the return type it does).

> The direct answer your question is to just do this

Is there a way of ensuring that the file is deleted after `example` (since it doesn't happen automatically)? e.g.

```haskell
example2 = do
    output "/tmp/foo1234" "asdf"
    example
    example
    view $ find (prefix "/tmp/foo") "/tmp"
    -- I would like this to print only `FilePath "/tmp/foo1234"`
```

That's what I was looking for in `with`.

**Comment by Gabriel439** [comment]
The file is automatically deleted after `example2` when the `Managed` block completes (either at the end of a `runManaged` or `sh` call).  For example, the way I would structure your code would be to make one minor modification:

```haskell
-- This ensures that the temporary file's scope is localized to `example`
example :: IO ()
example = runManaged (do
    fname <- mktemp "/tmp" "foo"
    output fname "asdf"
    stdout (input fname) )

-- Now this would do the right thing
example2 = do
    output "/tmp/foo1234" "asdf"
    liftIO example
    liftIO example
    view $ find (prefix "/tmp/foo") "/tmp"
```

**Comment by rpglover64** [comment]
Perfect. Thank you!

**Comment by Gabriel439** [comment]
You're welcome!

**Comment by Gabriel439** [comment]
I just wanted to clarify that I decided to rename the more convenient version of `mktemp` into `mktempfile` and keep `mktemp` as the old, safer behavior.  That way it avoids a breaking API change and it also gives users the choice as to what level of safety/convenience tradeoff they are willing to make.
